### ISSUE TITLE
acme-client / security concern

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/plugins#100]
As discussed here https://github.com/opnsense/plugins/pull/91#pullrequestreview-28123494 and at the risk of forgetting about it, I thought it would be a good idea to open an issue for it.

Current situation seems to be that an arbitrary command can be executed through the webgui using the underlaying scripting, which we should try to avoid.

Related code https://github.com/opnsense/plugins/blob/a3520c7c24c4a772201dbbb08fe94f9e31f08084/security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php#L1053-L1090

@fichtner what is your idea on this subject?

**Comment by fichtner** [comment]
The basic question is what is it used for? If the answer for normal plugin operation is "nothing at all" it should be removed. I guess without the use case(s) we can't replace it, just delete. ;)

**Comment by fraenki** [comment]
It's meant as an equivalent to the "hooks" that can be used in _many_ LE clients. These hooks make LE clients much more flexible and allow you to use the certificates in a way that suit your environment. For example, check-in certificates in a repository (to allow other hosts to access and use them), copy certificates to another host and restart remote services, etc.

I'm OK with removing this functionality, but I'd vote for a two-step approach, because it may already be used by some users:

- next release should provide a warning, that this functionality is being removed and that alternative features may be requested on GitHub; I'll add the warning to the GUI, bit it would help to have it in the release notes too
- one release later the functionality should be removed (with a final warning in the release notes)

**Comment by fichtner** [comment]
People can easily revert to the older package if they want... I don't think the warning will matter much in terms of making people aware of a migration they have no opportunity to handle differently.

    # opnsense-revert -r 17.1.3 os-acme-client

**Comment by fraenki** [comment]
OK. I've created #103 and I'm going to merge it if nobody has objections.

**Comment by fichtner** [comment]
ok 👍
