### ISSUE TITLE
Feature Request: BGP Peer Group Support

### ISSUE THREAD

**Issue by elizandropacheco** [opnsense/plugins#1006]
Peer group:

In order to avoid reconfigurations in many neighbors that have the same asn, there is the peer-group resource that could be added to the web interface. In this case, some parameters like remote-as are not mandatory (since they are set in the group and not neighbor).

https://www.labn.net/frr.html/BGP-Peer-Group.html

https://www.labn.net/frr.html/BGP-Configuration-Examples.html

**Comment by mimugmail** [comment]
Peer Groups would be a major change in BGP. This would need intensive testing. Would you be available for this?

**Comment by elizandropacheco** [comment]
I am available whenever you wish, I can pass on my contacts if you prefer.

**Comment by mimugmail** [comment]
I'll ping you here when I think I'm finished, but I have to bring some other stuff first.

**Comment by elizandropacheco** [comment]
No problem, I'll wait and hope to be contributing.

**Comment by rootwyrm** [comment]
I can provide additional assistance here. This is an extremely critical item for anycast configurations.

**Comment by mimugmail** [comment]
Ok, I had a look at yours and a look at my production setup (only CLI based). 
For me, it seems you can put any value in group which is also possible for neigbor.

I'd propose a new tab colled peer-group, all options besides IP are also there and the orignal neighbor grid gets a new dropdown box for peer-group. 

Templating config should be trivial then ... 

Opinions?

**Comment by rootwyrm** [comment]
So quick clarification on that.

A peer group can contain any number of prefix-lists and route-maps.
A neighbor can contain any number of peer-group entries.
Also note that peer-groups must be defined before real address neighbors.

So the following would be valid:
```
neighbor demo1 peer-group
neighbor demo1 prefix-list DEFAULT in
neighbor demo2 peer-group
neighbor demo2 prefix-list DEFAULT in

neighbor 1.2.3.4 remote-as 65500
neighbor 1.2.3.4 description example1
neighbor 1.2.3.4 peer-group demo1
neighbor 1.2.3.4 peer-group demo2
```

However, this also increases the importance of being able to select interfaces, so that needs to be added as well. For example, I have a configuration where I need to be explicit about the network interface, such as this:

```
neighbor 1.2.3.4 remote-as 65500
neighbor 1.2.3.4 update-source vmx1
neighbor 1.2.3.4 peer-group demo1

neighbor 5.6.7.8 remote-as 65500
neighbor 5.6.7.8 update-source vmx2
neighbor 5.6.7.8 peer-group demo1
```

New tab for peer group sounds like a good solution here, and then add a drop-down for peer-group and an entry box for interface (nothing if left blank, giving all interfaces.)

**Comment by mimugmail** [comment]
Like this?

![image](https://user-images.githubusercontent.com/20438689/55326917-318ba980-5489-11e9-9f2c-6f6423f60ff0.png)

![image](https://user-images.githubusercontent.com/20438689/55326943-436d4c80-5489-11e9-8643-15867bb1565e.png)

**Comment by rootwyrm** [comment]
Almost perfect. Need to remove the update-source from the peer group however. Use of `update-source` is only valid in `neighbor` blocks.

**Comment by mimugmail** [comment]
Ok, easy. Could there be more options in peer groups than in neighbor (already)?

**Comment by rootwyrm** [comment]
Theoretically, yeah, but these are largely going to be edge-cases (specifically around capability negotiation.) There's definitely room for more improvement, but I don't know how deep down that rabbit hole we necessarily want to go here. I would argue the stuff beyond 'add peer-groups' should probably be a separate issue since there's a lot more work involved.

**Comment by mimugmail** [comment]
I saw that we use internally also remote-as for peer-groups as we have plenty if iBGP peers. Will add this. Currently I'm stuck at templating .. too many if enabled and contain ':' but peegroup is undefined yadda yadda .. I'll finish tomorrow at work :)

**Comment by rootwyrm** [comment]
Oh yeah. Like I said, it's a very deep rabbit hole. (And FRR's documentation straight up sucks. It literally has no list of what's valid or invalid in `peer-group`, and not all items are valid.) With a GUI it's even worse because of all those checks. 

I suppose in the interim if there's any users requiring more than what's provided here, a free-form text box, one config item per line, just dump it in with `neighbor $PEER_GROUP peer-group $TEXT_LINE` with no validation would cover all their use cases.

**Comment by mimugmail** [comment]
> I suppose in the interim if there's any users requiring more than what's provided here, a free-form text box, one config item per line, just dump it in with `neighbor $PEER_GROUP peer-group $TEXT_LINE` with no validation would cover all their use cases.

This is only for legacy code .. have to do it once and good the hard way. 

We never get close to perfection compared to plain CLI, but I'm sure 90% of all use cases will fit.

**Comment by mimugmail** [comment]
This templating is so annoying, you can only guess which lines go to `router bgp` and which are under `address-family`

Still need some time ...

**Comment by NielsPiersma** [comment]
@mimugmail,

Michael, I was curious if you ever got BGP Peer groups working/implemented? BGP peers are something that would help us out. One of our customers has two 10Gb leased lines, and we have set up a DEC3680 cluster running OPNSense in front of it.

Using the CLI, I can get it working fine; it fails over and uses the other line within one second.

Our test configuration works.
---
router bgp 65407
 bgp router-id 192.168.222.1
 no bgp ebgp-requires-policy
 bgp graceful-restart
 neighbor 10.1.32.2 remote-as 65406
 neighbor 10.1.32.2 update-source igb1
 neighbor 10.1.32.2 timers 1 3
 neighbor 10.1.32.2 timers connect 10
 neighbor 10.1.33.2 remote-as 65406
 neighbor 10.1.33.2 update-source igb0
 neighbor 10.1.33.2 timers 1 3
 neighbor 10.1.33.2 timers connect 10
 !
 address-family ipv4 unicast
  network 192.168.222.0/24
  neighbor 10.1.32.2 route-map TEN_LOCAL_PREF out
  neighbor 10.1.33.2 route-map TWENTY_LOCAL_PREF out
 exit-address-family
!
!
route-map TWENTY_LOCAL_PREF permit 20
!
route-map TEN_LOCAL_PREF permit 10
!
!
line vty
-----

However, I can't find a way to get this configuration loaded/injected via the GUI. We run with CARP and HA enabled, and it will revert to the provisioned configuration at a fail-over or reboot.

Using the local frr package works, but I won't have CARP and HA fail-over.

I don't like to move back to PFSense, which currently has BGP Peer groups.

Thanks in advance,

NIels

**Comment by mimugmail** [comment]
Sorry, I started with it and never got finished. In my profile should be a branch for it.
TBH, I don't see any group config in your config you posted and when using only 2 eBGP's I also dont see a reason to start with groups. Maybe I misunderstand your posting?

**Comment by NielsPiersma** [comment]
Michael,

Thanks for reaching out. You are right; I don't have any "group" defined,
but let me try to explain.

We want to redundantly connect two BGP-enabled routers using one 2Gb line
and one 1Gb line (for backup).

When using OPNSense's GUI to configure BGP neighbors or peers, it is
possible to configure two or more peers with the same BGP AS number.
However, when I do that, only the LAST configured neighbor will end up in
the configuration file, overwriting the first neighbor.

That's why I used vtysh. When using vtysh, I can add the configuration I
posted before, which worked fine. But it will not survive a reboot and will
not correctly synchronize to the CARP partner.

So what I am looking for is a way to add two neighbors via the GUI, with
the same BGP AS number, configure one line to have preference over the
other, fine-tune the fail-over timers. And most important, have it working
with HA ;).

Hope you can guide me.

NIels













Op do 2 dec. 2021 om 09:12 schreef Michael ***@***.***>:

**Comment by mimugmail** [comment]
Ah, ok, you need to update to latest version. FRR 1.23 had a bug to not allow more than 1 BGP peer. This is not related to BGP peer groups which is a totally different topic :)

**Comment by NielsPiersma** [comment]
Yeah i just figured that one out when I was trying to reproduce the problem.
Now it seems to be working fine.
Only want to play with the timers :) but I think I can find that.
many thanks
Niels

Op do 2 dec. 2021 om 17:27 schreef Michael ***@***.***>:
