### ISSUE TITLE
www/c-icap: make error templates look&feel of OPNsense

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#1021]
This one goes out to @noname12123 ... Rene, you asked some days ago about new projects.
Since you mentioned that you use transparent proxy, you probably want to redesign the error pages when virus was found with c-icap?

/usr/local/share/c_icap/templates/virus_scan/en/VIRUS_FOUND

Could be a new challenge for you to make the virus scanner more integrated into the system :)

**Comment by opnsenseuser** [comment]
@mimugmail shure.I'll take a look at it this evening

**Comment by opnsenseuser** [comment]
@mimugmail can you assign it to me?

**Comment by fabianfrz** [comment]
@mimugmail @opnsenseuser I do already have some templates in the nginx plugin. Maybe you can reuse them slightly modified:

https://github.com/opnsense/plugins/tree/master/www/nginx/src/etc/nginx/views

**Comment by opnsenseuser** [comment]
@mimugmail 

you have to explain a few things to me.
I find in the directory you mentioned 5 files.
![grafik](https://user-images.githubusercontent.com/34602360/48983118-390e0100-f0eb-11e8-9c93-5a99b55ab427.png)



What is the difference between the files?
Where is my task or what should I do exactly?
Are there any requirements?
Sorry for the many questions but I have to read only in the task!

best regards
René

**Comment by mimugmail** [comment]
Check Out virus_found. This is the Page displayed when a Virus is detected. The variables in the file should stay, but perhaps you can make the look more like OPNsense.

On eicar.org you can Download a Test Virus to check

**Comment by fabianfrz** [comment]
@mimugmail this would be the same style as the nginx plugin has (note that github does not allow files without a file suffix) and I have replaced the term virus by malware because viruses are very uncommon:

[VIRUS_FOUND.txt](https://github.com/opnsense/plugins/files/2613521/VIRUS_FOUND.txt)

**Comment by mimugmail** [comment]
@fabianfrz thx :) I'd use the same grey as used in OPNsense and not black, perhaps also the font type ...

**Comment by fabianfrz** [comment]
@mimugmail It is hard to reuse everything because you cannot really load an external resource because you cannot even be sure that you can reach the web interface. So stability reasons, everything has to be in a single file which is delivered by C-ICAP.

So, for sure the colors may be adjusted for your needs but it will be hard to load the web fonts etc. from the standard theme.

If you want to serve your own resources, you will need an always reachable web server which in case of OPNsense is either the web interface if you open it via a custom FW rule or via an internal web server like nginx.

BTW: I like the black danger pages in nginx because it is very likely a huge contrast to the website loaded previously.

**Comment by opnsenseuser** [comment]
@mimugmail 
@fabianfrz 
I tried to make my own picture of the "problematic".
I think that this is also a matter of personal taste.
To be honest, I would generally make the pages in one color and not use colors adapted to the Opnsense template.
Black is good, because the user immediately realizes that something is wrong, and second, it is easy to read.
I have to say honestly, even though I'm very grateful to you (Michael) for giving me a new job, but I really did not know what to do better. I think fabian's idea of ​​taking the page layout and black as a background is really good. In addition, I would find it good if you could give the administrator of the firewall the opportunity to provide some of these pages with their own text, or could upload their own logo in addition, then place this logo anywhere in addition to the opnsense logo somewhere on the page ,
We should also consider other plugins (for example Squid) to give the administrator at least the option to add their own logo or even small texts to the warning pages. In a company, it is also good for the end user to know if he/she receives a warning, for example to get a text, that he can contact the support by calling  xxxxx or write an email to xxxx@xxx.com.

**Comment by opnsenseuser** [comment]
@mimugmail 
@fabianfrz 

maybe it would also be advantageous to be able to customize the colors of the warning pages by the firewall administrator so that they match the company intranet better. This in turn would help the enduser of the company to identify problems more easily, and thus the administrator would also get the information faster. Especially with virus warnings of the terminals in a network certainly advantageous, even if the end user recognizes faster that there is a problem here.

**Comment by opnsenseuser** [comment]
but if the admin already has a gui, then he should also have the benefits of a gui and allow the admin an input of the background color or the foreground color as hex or rgb via an input field. at least for a few areas of the warning page. Important areas should remain static, such as the Opnsense logo and the texts we specify. but little things should be customizable.

**Comment by fabianfrz** [comment]
@opnsenseuser that's exactly what I wrote. It's not hard to use this file as a template like the others for configuration.

**Comment by mimugmail** [comment]
I'll try to template some stuff when I have time :)

**Comment by opnsenseuser** [comment]
These options should only serve to better integrate into the company intranet not for customization to the firewall theme. no user knows how or what a firewall is and what the web interface looks like. that does not interest the end user at all

**Comment by opnsenseuser** [comment]
@fabianfrz yes but customizable via an input field and not again any xml date. as I said, why is there a gui?

**Comment by fabianfrz** [comment]
@opnsenseuser The system is split up in the backend and the frontend (GUI) the backend does not access the frontend so this is separate. At the end you need both but templates in OPNsense involve the config.xml, configd and some template files (if you want to count them, some python libs and some custom scripts).

The frontend in contrast are the PHP, VOLT, CSS, JS etc. files, which store the settings in the config.xml.

**Comment by opnsenseuser** [comment]
@fabianfrz OK, too bad! :-(

**Comment by fabianfrz** [comment]
@opnsenseuser I just want to tell you that the rendering does not depend on the web interface. This effectively means that the template can be made while there is no web interface for it and the web interface can be added later.

**Comment by opnsenseuser** [comment]
@fabianfrz thanks for the information. too bad that this does not work. But security is still more important!

**Comment by opnsenseuser** [comment]
@fichtner @fabianfrz @mimugmail 👍
