### ISSUE TITLE
Quagga: Set a global password for service management via CLI

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#116]
If you want to configure some features by hand via the CLI you have to telnet to localhost and then port 2601 for zebra, or e.g. 2605 for bgg, but local management is only available when there's a password configured in the *.conf.

root@OPNsense:~ # telnet localhost 2605
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Vty password is not set.
Connection closed by foreign host.

Perhaps we can set a password in general which is copied to all enabled conf files via a helper?

**Comment by fabianfrz** [comment]
I don't want it to be available on the net - it is just attack surface. If you want to configure it remotely, a user with `vtysh` set as shell is far a better option because the connection would be encrypted.

The configuration should be done via the GUI and all changes are undone at reboot / changes in the GUI.

Opening the port is bad...
* for security reasons
* for management reasons

However you can discuss that with @fichtner and @AdSchellevis .

**Comment by mimugmail** [comment]
No, no need for such a discussion :) With your fix #114 vtysh is way easier to use.
