### ISSUE TITLE
security/acme-client: user feedback

### ISSUE THREAD

**Issue by chani** [opnsense/plugins#1173]
Hi there,

we're using the letsencrypt plugin a lot and noticed a few issues. I might open separate issues - please let me know if you prefer that.

1. (Bug) Requesting a new certificate leads to "pending". It seems clicking "Issue/Renew certificates" does not suffice; we have to forcefully renew the certificate and/or we need to do this twice. The first request always fails. The second request succeeds and we're able to select the certificate in HAProxy.

2. (Bug) Moreover, we're able to choose certificates in HAProxy which show "validation failed" - They're just working fine, though.

3. (Feature Request) Since one validation/request process produces quite some information, is it possible to increase the amount of loglines shown in "Log" within the OPNSense or probably make it choosable to view the last 10, 100, 1000 log entries? That'd be nice and pretty helpful.

4. (Usability Issue) If you copy a certificate, remove the fqdn, name and description it will appear again within a few seconds. That happens up to 5 times. I usually have to wait ~20-30 seconds once I'm able to enter new information without them being replaced with the old ones :^)

5. (Feature Request) Synchronization in HA-Setups would be great.

Jean

**Comment by fraenki** [comment]
> 1. (Bug) Requesting a new certificate leads to "pending" [...]

Known issue, I think this is caused by a bug in acme.sh (the Let's Encrypt client we're using). Once acme.sh is updated to 2.8.x we'll see... (https://github.com/opnsense/ports/issues/64)

> 2. (Bug) Moreover, we're able to choose certificates in HAProxy which show "validation failed"

That's not a bug. Once a certificate was successfully created and verified with Let's Encrypt, it is automatically imported to OPNsense's certificate storage. So this means even ff the certificatefails to renew at a later point in time, it can still be found in OPNsense' certificate storage and thus can still be used.

Just for clarification: The HAProxy plugin does _not_ show entries from the Let's Encrypt _plugin pages_, but instead shows all certificates from _OPNsense's certificate storage_.

> 3. (Feature Request) [...] make it choosable to view the last 10, 100, 1000 log entries?

I'm not sure if this is supported by the underlying framework. I'll investigate if this is possible.

> 4. (Usability Issue) [...] I usually have to wait ~20-30 seconds 

Unfortunately there is nothing I can do about it. This is an issue of your local instance, it's not reproducable for me. I've seen this _once_ on a testserver though, but have no idea what may cause this issue.

> 5. (Feature Request) Synchronization in HA-Setups would be great

That's not supported and there are currently no plans to implement it. See #589 for a more detailed explanation.

**Comment by chani** [comment]
Thanks for your response. I believe this issue can be closed then. In case you're up for enhancements: something which would indicate that a certificate (which is available to other plugins since its in the opnsense certificate storage) is broken/invalid/etc might be useful. 

About the choosable log entries: Noticed that there is a global flag which I may use for that. So, might not be required.

**Comment by fraenki** [comment]
> In case you're up for enhancements

Absolutely yes. Please don't stop suggesting enhancements, even if suggestions get rejected :)

> something which would indicate that a certificate (which is available to other plugins since its in the opnsense certificate storage) is broken/invalid/etc might be useful

Hm, the **certificate storage** does not provide many ways to implement this... there's only the name/description field which could hold this information. So in case of a failing renewal attempt, we could change the name of the certificate from `www.example.com (Let's Encrypt)` to `www.example.com (Let's Encrypt) [renewal failed]` (or a similar text, I'm open for other options).

On the downside this would require to update the certificate storage, even if the certificate was not changed. And it adds a some complexity to the plugin code, but the user may very well _still_ fail to notice the error in-time. Furthermore the certificate name would be rather lengthy, it's not guaranteed that the error message is still visible everywhere.

Maybe it would be a better approach to use the integrated **Monit** (Services: Monit: Settings) to send alerts if renewal of a certificate fails? I'd prefer this solution because it would provide a clean solution with good usability. I think I could add this feature to Monit in one of the upcoming releases.

Does this make sense to you?
