### ISSUE TITLE
mail/postfix: add Sender Authentication

### ISSUE THREAD

**Issue by AndyX90** [opnsense/plugins#1193]
In the Postfix plugin there is only the option for smtp-authentication against a smart-host.
It would be great to have the same option for authenticating a local sender against postfix.

**Comment by mimugmail** [comment]
TBH, I don't want to add user management via sasldb. When using auth for outgoing mail it's ok since it's only a hash file, but as smtpd this is no fun to implement.

**Comment by AndyX90** [comment]
Hmm okay, I'm not a postfix specialist.
But what about this:
https://www.df.eu/de/support/df-faq/cloudserver/anleitungen/smtp-authentifizierung-mit-postfix-debian/
Maybe we can add a local user via Webinterface and add it in a group "maybe postfix-senders".

**Comment by mimugmail** [comment]
For this we'd need saslauthd pkg in addition. This would be plenty of work for such a small specific feature.

**Comment by EugenMayer** [comment]
@mimugmail i think you might need to clarify that this postfix is considered to be an MSA only, not an MTA - in this regard, its rather usual to have no authentication but use ip based relay setups - maybe this would help here too.

Also, postfix allows to have multiple smarthosts upstreams and also mapping the "smarthost to use" using the senders `from` address - not sure this is out of scope, but this could help here too

**Comment by mimugmail** [comment]
Smarthost can be chosen by recipient domain, this is the more usual way, but I'm open for config snippets

**Comment by EugenMayer** [comment]
I would argue with the sender/recipient but as usual, it depends on the case and we seem to have different ones :)

What i have in that manner is very complicated, especially if you want to have different authentication methods like TLS on 465, SSL, TLS on 587 and 25 plain ( no auth ) - all at the same time for multiple different smarthosts. One needs to define new service type per configuration type, esp. because of `wrappermode` or not and `smtp_tls_security_level`.
Also adding `sender_transport_map` and `sasl_password` ( the latter you will also have ) and all this is a relation way - i would not really drag you into this task .. its overcomplicating things. 

So in the end, supporting multiple upstream smarthosts can become a burden with there encryption type differs or one is non auth and one is auth ( i would argue that for a proper smarthost setup, there is no sane reason to have one non-auth .. but we have those customers too... ). But having wrappermode tls and normal tls could very much happen and this quickly gets out of control. So you should either limit it to "same port, same enc" or just use the RFC and use "MSA port only, so 587 only" - or you could just go down this very ugly road on having custom service types in the end.

I think though, for a OPNsense postfix, a simple 1 smarthost/no auth case is the most useful one - it would most probably suite this "system level notification" like cron or other systems sending out emails without auth, and maybe for smaller needs in smaller companies for real "persons" MSA (but i would rather doubt it). 

Depends on where you see your plugin go, all this features! Good work though, i really like this one, very handy!

**Comment by mimugmail** [comment]
I'd vote for closing this one, I dont want to add user auth, this use can be handled via IP Filter and trusted networks
