### ISSUE TITLE
www/nginx: add support for listen default_server

### ISSUE THREAD

**Issue by Zauberfisch** [opnsense/plugins#1218]
if no hostname is matched, nginx will by default take the first server block from the top. And since there is currently no way to manually sort the servers, it means it's currently not possible to specify a default server.

however, it's possible to specify a default server with:

    listen 80 default_server;

See: http://nginx.org/en/docs/http/request_processing.html

**Comment by fabianfrz** [comment]
I don't want to support this due to a feature, which is currently not available in the frontend:

https://github.com/opnsense/plugins/blob/master/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/webgui.conf

When you kill lighttpd and uncomment this [line](https://github.com/opnsense/plugins/blob/master/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf#L42) and restart nginx, you will run the web interface over nginx so you can share the port with the web content behind it easily.

The reason why this feature is not available is because the original core PR was rejected and I did not put a bigger amount of work into it to make a better purposal.

**Comment by Szeraax** [comment]
Yes, I too would like the front end to be able to specify the default_server option.

**Comment by Szeraax** [comment]
I should also note that I believe doing a server name of "" is functionally equivalent to default_server. 

See http://nginx.org/en/docs/http/server_names.html

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by PatrickHuetter** [comment]
I also think this feature is really important since otherwise the nginx could automatically expose websites that don't filter for a server_name from one of the upstreams. I think the nginx should serve a default page or nothing if no server_name matches.

**Comment by timolow** [comment]
@PatrickHuetter Could not agree more, I like the default behavior in haproxy plugin where it will generate an error page if no hostname is matched in the config.

**Comment by rmrfus** [comment]
This is the only feature that prevents me from migration from separate container to this plugin.
I want to have honeypot for all requests coming by IP or to bogus hostnames.

**Comment by nuggie** [comment]
Hi there,

thanks for the merge! One thing I'm still missing is the possibility to also set default_server for https.

Any plans to also implement this feature?
