### ISSUE TITLE
net/unbound REST plugin - merge into /plugins?

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/plugins#1226]
I am running https://github.com/EugenMayer/opnsense-unbound-plugin for about 1 year in production now and recently migrated it to 19.1, too - so it's at least a little battle proven

It does offer a part of Unbound as a MVC based plugin in term to offer a REST api to create / remove DNS entries. It does not cover any UI, it just uses the current core plugin as the core and offers a REST interface for some parts (to be extended).

Surely the plugin might need clarification in its name or it confuses the user with the core plugin ( its rather a companion yet, not a replacement).

Also this plugin could be a starting point for a migration of the "Unbound legacy plugin" to an MVC plugin. 

Let me know if there is any interest in merging it into the community plugin repository, i am happy to do so

**Comment by fichtner** [comment]
I will take a look what we could do about it...

**Comment by EugenMayer** [comment]
Is there any way to contribute without the sidetone? This is nothing for me - still you obviously took it that way. 

So if that is a burden, just close the issue and we are good to go. I have it running, i keep it running. I was just sharing, but it seems, there is simply no way to do that without stepping on whoever toes why ever.

I guess once a tone is set, you cannot get rid of it - well we are all humans after all.

**Comment by fabianfrz** [comment]
@EugenMayer we review everything to ensure that there are not many bugs inside and to see if it fits into the product.

For example, your code needs some changes as it contains some bugs / coding errors:

* when it is not called via POST, you respond with 500, which is an internal server error but the server responds correctly as this is a client error. In this case use 405 or the generic 400.
* the library code should not be in the controller directory (move to library).
* the xml configuration very likely can be encapsulated in a model for new and old style classes to work with the OPNsense interal MVC components.
* you are printing data and exit with 0 instead of just returning an associative array, in which case all the encapsulation is done for you by the framework.
* and probably some more

**Comment by mimugmail** [comment]
Eugen, I added a unbound-plus Plugin to insert mvc code via config includes. Are you still using this feature? Adding a domain section for creating A records should be quite easy, just like overrides
