### ISSUE TITLE
security/acme-client: OCSP Must Staple checkbox state is not honored

### ISSUE THREAD

**Issue by nikaro** [opnsense/plugins#1568]
**Describe the bug**
I had OCSP Must Staple enabled and it was working fine. But recently my Firefox ESR (68.2.0) failed to open the Web UI with the error `MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING` due to an OCSP issue. So i unckecked `OCSP Must Staple` in the certificate settings and re-issued it. OCSP must staple extension was still in the certificate after that.

I took a look in `/var/etc/acme-client/home/ubicast.net/ubicast.net.conf` and there was `Le_OCSP_Staple='0'`, i changed it manually to `'1'` and re-issued the certificate, and now it is working as expected.

**Screenshots**
![Certificate OCSP Must Staple Extenstion](https://i.imgur.com/pqhY4XH.png)

![Web UI](https://i.imgur.com/cliFaQZ.png)

```
# cat /var/etc/acme-client/home/ubicast.net/ubicast.net.conf
Le_Domain='ubicast.net'
Le_Alt='ubicast.net,*.ubicast.net'
Le_Webroot='dns_ovh'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''

Le_Keylength='4096'
Le_OCSP_Staple='1'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/63585208/1448974948'
Le_DNSSleep='120'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/0358b508ffeb9b3618474147769648468564'
Le_CertCreateTime='1573028079'
Le_CertCreateTimeStr='Wed Nov  6 08:14:39 UTC 2019'
Le_NextRenewTimeStr='Sun Jan  5 08:14:39 UTC 2020'
Le_NextRenewTime='1578125679'
Le_RealCertPath='/var/etc/acme-client/certs/5d56d1b984bec6.94253487/cert.pem'
Le_RealCACertPath='/var/etc/acme-client/certs/5d56d1b984bec6.94253487/chain.pem'
Le_RealKeyPath='/var/etc/acme-client/keys/5d56d1b984bec6.94253487/private.key'
Le_ReloadCmd=''
Le_RealFullChainPath='/var/etc/acme-client/certs/5d56d1b984bec6.94253487/fullchain.pem'
Le_RenewalDays='60'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/63585208/1448974948'
```

**Environment**
OPNsense 19.7.6-amd64
FreeBSD 11.2-RELEASE-p14-HBSD
OpenSSL 1.0.2t 10 Sep 2019

**Comment by fraenki** [comment]
> I took a look in /var/etc/acme-client/home/ubicast.net/ubicast.net.conf and there was Le_OCSP_Staple='0', i changed it manually to '1' and re-issued the certificate, and now it is working as expected.

Indeed, acme.sh does not remove `Le_OCSP_Staple=1` from the certificate configuration file.

However, this is not required, because for acme.sh the command-line parameters take precedence. In order words: the OPNsense Let's Encrypt plugin runs acme.sh without the OCSP command-line parameter and as a result the certificate will be generate without this extension.

This can be verified by checking the CSR configuration instead: `/var/etc/acme-client/home/CERTNAME/CERTNAME.csr.conf`. When "OCSP Must Staple" is enabled in the GUI, the file contains the following line:

`1.3.6.1.5.5.7.1.24=DER:30:03:02:01:05`

This line is missing when "OCSP Must Staple" is disabled in the GUI.

> So i unckecked OCSP Must Staple in the certificate settings and re-issued it. OCSP must staple extension was still in the certificate after that.

Please note that you must first **revoke** the certificate, otherwise you will (in most cases) simply receive the cached certificate from Let's Encrypt again.

AFAICT everything is working as expected, I cannot find any bug here.
