### ISSUE TITLE
security/acme-client: Renewing certificates suddenly stopped working

### ISSUE THREAD

**Issue by SamuelNitsche** [opnsense/plugins#1590]
**Describe the bug**
Acme worked perfectly fine until recently. Whenever I try to renew my certificate, it fails. I looked through the log files. You can find it here: https://pastebin.com/raw/YFHDNzyw

When I try the exact same configuration in the staging environment, everything works. I noticed that acme uses ipv6 in production but ipv4 in staging. Logs from a successful staging renew can be found here: https://pastebin.com/raw/6eva5piG

Has someone else experienced this issue and can help?
Thanks in advance!

**To Reproduce**
1. Go to 'Services' -> 'LetsEncrypt' -> 'Certificates'
2. Click on 'Renew'
3. See error 'valdiation failed'
4. Go to 'Services' -> 'LetsEncrypt' -> 'Settings'
5. Switch to staging environment
6. Go back to 'Services' -> 'LetsEncrypt' -> 'Certificates'
7. Click on 'Renew' again
8. See 'Ok'

**Expected behavior**
SSL Certificate gets renewed correctly.

**Environment**
OPNsense 19.7.7-amd64
acme-client v1.28

**Comment by fraenki** [comment]
Looking at the log...

```
[Fri Nov 22 19:14:15 CET 2019] gw.samys.network:Verify error:Invalid response from https://gw.samys.network/?url=/.well-known/acme-challenge/DPX_Y15ZnXHPd09fkNJ_-a9fvdVlbYjoPI-NkbwGdPU [2a01:4f8:13b:2744::17]:
...
[Fri Nov 22 19:14:15 CET 2019] url='http://gw.samys.network/.well-known/acme-challenge/DPX_Y15ZnXHPd09fkNJ_-a9fvdVlbYjoPI-NkbwGdPU'
```

...your host does not repsond properly. Maybe it is not configured to serve ACME challenges over IPv6.
Either fix the configuration or remove the IPv6 address from the DNS record.

**Comment by SamuelNitsche** [comment]
Yeah, that's what I saw, too. Unfortunately, this doesn't help. From my understandings the configuration is correct. The same configuration works in the staging environment (ipv4) with the correct ip address on the same interface.

**Comment by fraenki** [comment]
> From my understandings the configuration is correct.

I don't think that this is the case. From an IPv4-only setup your host is unreachable.
I have not idea why it's behaving differently for LE Staging and LE Production, so this is likely a good question for the [LE Community](https://community.letsencrypt.org/).

**Comment by SamuelNitsche** [comment]
> I don't think that this is the case. From an IPv4-only setup your host is unreachable (at least in my quick test).

My host has two public ipv4 addresses. I think you may tested the wrong one. When using ipv4 in the staging environment, everything works perfectly fine. I think that the plugin doesn't listen on the correct interface/ip address.

**Comment by fraenki** [comment]
> My host has two public ipv4 addresses.

And you also have an IPv6 DNS record for your host. Is this IPv6 address supposed to work?

> I think that the plugin doesn't listen on the correct interface/ip address.

This depends on your configuration... especially the "Validation method" and what you've configured there...

**Comment by fraenki** [comment]
So I've searched an IPv6-capable test host and tried to get the ACME challenge from your host and got this reply:

```
< HTTP/1.1 301 Moved Permanently
< Location: https://CLOAKED_HOST/.well-known/acme-challenge/DPX_Y15ZnXHPd09fkNJ_-a9fvdVlbYjoPI-NkbwGdPU
< Content-Length: 0
< Date: Mon, 09 Dec 2019 17:05:47 GMT
< Server: OPNsense
```

I think this is the main issue, because in the acme.sh.log the ACME server was also redirected to HTTPS:

```
Verify error:Invalid response from https://CLOAKED_HOST/?url=...
```

So this reveals another issue: your OPNsense WebGUI is exposed to the internet, which it shouldn't.

**Comment by SamuelNitsche** [comment]
> And you also have an IPv6 DNS record for your host. Is this IPv6 address supposed to work?

Exactly.

> This depends on your configuration... especially the "Validation method" and what you've configured there...

The validation method is configured like this.

<img width="921" alt="Bildschirmfoto 2019-12-09 um 18 10 26" src="https://user-images.githubusercontent.com/24483576/70456894-6091fa80-1aaf-11ea-8bfc-48ee381f8e3e.png">

**Comment by fraenki** [comment]
> The validation method is configured like this.

Ah, the wonders of automatic configuration. :D (TBH, the plugin tries it's best to guess what it needs to do, but it may fail in certain situations.)

Maybe it fails to setup the port forward (which it needs to proxy requests to the internal webservice that is serving the ACME challenges).
Please try again and check _System: Log Files: General_ and _System: Log Files: Backend_ for messages that contain the "AcmeClient" keyword (or errors before/after these messages).

**Comment by SamuelNitsche** [comment]
> Ah, the wonders of automatic configuration. :D (TBH, the plugin tries it's best to guess what it needs to do in automatic mode, but it may fail in certain situations.)

So I should disable IP Auto-Discovery and manually specify the public ipv4 and ipv6 adresses?

**Comment by fraenki** [comment]
> So I should disable IP Auto-Discovery and manually specify the public ipv4 and ipv6 adresses?

No, first please try again and provide the additional logs. If it's a bug that can be fixed then let's fix it.
You could also check `/var/etc/acme-client/acme_anchor_rules`, these are the auto-generated firewall rules that are used during an acme.sh run. If they look odd or are plain broken than this would indicate a bug.

**Comment by SamuelNitsche** [comment]
> You could also check `/var/etc/acme-client/acme_anchor_rules`, these are the auto-generated firewall rules that are used during an acme.sh run.

This file doesn't even exist on my system. Is this intended?

**Comment by fraenki** [comment]
> This file doesn't even exist on my system. Is this intended?

If you have just tried to renew the certificate it should exist. What messages are in the additional logs?

> Please try again and check System: Log Files: General and System: Log Files: Backend for messages that contain the "AcmeClient" keyword (or errors before/after these messages).

**Comment by SamuelNitsche** [comment]
> If you have just tried to renew the certificate it should exist. What messages are in the additional logs?

There are no entries in the _Backend_ log but I found this interesting piece in the _General_ log.

![Bildschirmfoto 2019-12-16 um 13 45 24](https://user-images.githubusercontent.com/24483576/70908004-8452c480-200a-11ea-871f-1b374804715a.png)

**Comment by fraenki** [comment]
> rule expands to no valid combination
> pfctl: Syntax error in config file: pf rules not loaded

@SamuelNitsche Thanks, I was able to reproduce this issue. The current implementation of the "automatic port forward" lacks support for IPv6. You can test the following patch:

`opnsense-patch -c plugins 9e005176`

Please let me know if it fixes your issue.

**Comment by SamuelNitsche** [comment]
It has changed the error, but it is not fixed yet. See the new logs here.
https://pastebin.com/raw/HnU0nruK

**Comment by fraenki** [comment]
Well, that's basically the [same](https://github.com/opnsense/plugins/issues/1590#issuecomment-563178078) ACME error. Could you please check the OPNsense logs again for other errors?

**Comment by SamuelNitsche** [comment]
There are no errors or even other information in the logs. Sorry.

**Comment by fraenki** [comment]
Did you click the `Apply` button in `Services: Let's Encrypt: Settings` before testing again? In this case the rules would work, but the ACME webserver would not be able to use IPv6. Since ACME received a timeout error, this may be the case here.

What's the content of the acme_anchor_rules file?

Can you try to load the rules manually?
`/sbin/pfctl -a acme-client -f /var/etc/acme-client/configs/XXX_ID_XXX/acme_anchor_rules`

If they loaded successfully, please try to access a ACME URL:
`curl -v http://XXX_HOSTNAME_XXX/.well-known/acme-challenge/DPX_Y15ZnXHPd09fkNJ_-a9fvdVlbYjoPI-NkbwGdPU`
(Do NOT run this command on your OPNsense firewall! We want to test if the port forward is working as expected.)

If possible please test with both IPv4 and IPv6-capable client.

After all tests are done you may want to remove the ACME rules again:
`/sbin/pfctl -a acme-client -F all`

Thanks.

**Comment by SamuelNitsche** [comment]
I just deleted all acme-client rules with the command `/sbin/pfctl -a acme-client -F all` and saved all my configuration files. After a retry, the certificate was issued correctly.

I think the issue is fixed.

**Comment by fraenki** [comment]
It bugs me that we couldn't figure out what went wrong (except the IPv6 bug), but I'm glad it's working again.

**Comment by Aarklendoia** [comment]
Since switching to OPNsense 19.x, I can no longer renew my certificate for the OPNsense web interface. Each time I get an error during the challenge: 

`[Sat Jan  4 15:56:25 CET 2020] xxx.sample.com:Verify error:Invalid response from https://xxx.sample.com/?url=/.well-known/acme-challenge/6xfI1QvzmOn5r4afcPp04nzE66qse9WAPtaSZ0XYIrQ [2a01:cb00:41d:8200:x:x:x:x]:
[Sat Jan  4 15:56:25 CET 2020] pid
[Sat Jan  4 15:56:25 CET 2020] No need to restore nginx, skip.
[Sat Jan  4 15:56:25 CET 2020] _clearupdns
[Sat Jan  4 15:56:25 CET 2020] dns_entries
[Sat Jan  4 15:56:25 CET 2020] skip dns.
[Sat Jan  4 15:56:25 CET 2020] _on_issue_err
[Sat Jan  4 15:56:25 CET 2020] Please check log file for more details: /var/log/acme.sh.log
[Sat Jan  4 15:56:25 CET 2020] url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/30853155/fLpvsA'
[Sat Jan  4 15:56:25 CET 2020] payload='{}'
[Sat Jan  4 15:56:26 CET 2020] POST
[Sat Jan  4 15:56:26 CET 2020] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/30853155/fLpvsA'
[Sat Jan  4 15:56:26 CET 2020] _CURL='curl -L --silent --dump-header /var/etc/acme-client/home/http.header  -g '
[Sat Jan  4 15:56:26 CET 2020] _ret='0'
[Sat Jan  4 15:56:26 CET 2020] code='400'`

I installed the patch and removed the rules as shown above, but it always fails.
