### ISSUE TITLE
security/acme-client: The dnsapi files are missing

### ISSUE THREAD

**Issue by reneschuster** [opnsense/plugins#1678]
I tried to validate a domain via DNS-01, but that failed because the dnsapi files are missing. 

After manually downloading the right dnsapi file to /var/etc/acme-client/home/ the acme client was able to validate the domain and to create the certificate.

https://github.com/Neilpang/acme.sh/tree/master/dnsapi

Please also integrate the dnsapi files in the plugin, 

OPNsense 20.1.r1 (amd64, OpenSSL)
os-acme-client 1.29

**Comment by fraenki** [comment]
@reneschuster Pleas describe the steps to reproduce the behavior.

**Comment by reneschuster** [comment]
As Validation Method choose any DNS Service and it will not work, because the dnsapi files are not installed with the plugin. 

For each DNS Service listed in the dropdown a dnsapi is required. Please check also the [dnsapi dev guide](https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide) where that is explained.


![image](https://user-images.githubusercontent.com/1628654/73304582-d5b0bf00-4218-11ea-957c-857b9ede0f9a.png)

**Comment by reneschuster** [comment]
The error message from the log:

[Tue Jan 28 13:03:27 CET 2020] d_api
[Tue Jan 28 13:03:27 CET 2020] Can not find dns api hook for: dns_inwx
[Tue Jan 28 13:03:27 CET 2020] You need to add the txt record manually.

**Comment by fraenki** [comment]
Indeed, we've missed an [upstream change](https://reviews.freebsd.org/D23209) and this results in missing dnsapi files. This will be fixed in OPNsense 20.1.0 or 20.1.1.

**Comment by reneschuster** [comment]
I created the /var/db/acme/.acme.sh/dnsapi directory like in your commit and copied the files into it but I still get the error: _Can not find dns api hook for: dns_inwx_

For me it's only working when the dnsapi directory is inside /var/etc/acme-client/home/

**Comment by reneschuster** [comment]
It must be the **acme home directory** and in the plugin code I found this:

https://github.com/opnsense/plugins/blob/9e45c51384e276a785ac09502e10f7faf20739c9/security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php#L401

**Comment by fraenki** [comment]
> I created the /var/db/acme/.acme.sh/dnsapi directory like in your commit

That's not how the os-acme-client plugin is supposed to work. Please don't do this. It makes supporting you pretty much impossible.

> It must be the acme home directory and in the plugin code I found this:

No, your assumption is wrong. Have a look at the acme.sh source code:

https://github.com/Neilpang/acme.sh/blob/552a49a6801fa3c144856d95b3a8a2c8f121cf31/acme.sh#L3596-L3602

As you can see, acme.sh also searches in other locations.

However, since we are using the FreeBSD port of acme.sh, the following symlink is automatically created:

```
root@opnsense:~ # ls -l /var/db/acme/.acme.sh/dnsapi
lrwxr-xr-x  1 root  wheel  51 Oct 31 04:44 /var/db/acme/.acme.sh/dnsapi -> ../../../../usr/local/share/examples/acme.sh/dnsapi
```

See also:
https://svnweb.freebsd.org/ports/head/security/acme.sh/Makefile?revision=523497&view=markup#l62
https://svnweb.freebsd.org/ports/head/security/acme.sh/pkg-plist?revision=523497&view=markup#l137

However, this simlink may currently be missing because of the previously mentioned upstream change. The only proper fix is to revert to the old version.

**Comment by reneschuster** [comment]
Ok, thanks for the clarification.
