### ISSUE TITLE
security/acme-client Add Ability to Retrieve SSL Certificates via REST API

### ISSUE THREAD

**Issue by Shackelford-Arden** [opnsense/plugins#1685]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Describe the solution you'd like**
I would find it extremely useful to be able to extract both the private key and the actual certificate via the REST API that currently exists.

One option could be that on this endpoint that currently exists:

`/acmeclient/certificates/get/:id`

We get the cert/key content included in the response. Or if we don't want that too cluttered, we could do something like:

`/acmeclient/certificates/get/:id/key`
`/acmeclient/certificates/get/:id/cert`

And the response contains this specific information.

To me this provides greater flexibility vs the SFTP option that's currently available for when a certificate is renewed. It makes it so I only have to worry about looking in one place that's more dependably online that other hosts. 

**Describe alternatives you've considered**
I know some alternatives that more or less already exist are:

- SFTP via Automation Actions post-renewal
- Straight up pulling the cert off the OpnSense host via SSH/SFTP myself.

**Comment by fraenki** [comment]
@Shackelford-Arden Thanks for the detailed description. I agree that it would be useful to retrieve certs/keys via API. However, I don't think this should be added to the ACME plugin (or any other OPNsense plugin).

The ACME plugin uses the OPNsense cert manager to expose certs/keys for use in other applications. So I think the correct way to implement this would be to add API support to the OPNsense cert manager instead.

That being said, the OPNsense cert manager is still legacy code and I think it would first need a rewrite to convert it to OPNsense's MVC framework. AFAIK, there's currently nobody working on this.

I'll close this issue, because it is pretty unlikely that this will be implemented in the near future. However, I'll add the "help wanted" label, because code contributions could of course make a huge difference and probably change priorities too. :)
