### ISSUE TITLE
unbound-plus: list parsing problems, not working any more

### ISSUE THREAD

**Issue by marunjar** [opnsense/plugins#1699]
It seems like the new script for unbound-plus (https://github.com/opnsense/plugins/pull/1647) has broken many of the predefined lists.

**To Reproduce**
1. Go to 'Services: Unbound DNS: Blacklist'
2. under 'Type of DNSBL' select one after the other of the follwing predefined lists:
* EMD Malicious Domains List
* hpHosts Ads
* hpHosts FSA
* hpHosts PSH
* hpHosts PUP
* Steven Black List
* Simple Tracker List
3. Save
4. try to access any not blocked page:
5. check the generated dnsbl.conf

**Current behaviour**

For some lists there is an nearly empty list generated, eg. hpHosts Ads
dnsbl.conf contains only: "localhost #IPv4 localhost\r A 0.0.0.0"

For some lists there is an empty list generated, eg. Simple Tracker List

For some files there are entries with comments added, e.g. Steven Black List

It seems that the reason lies in new regex used for finding valid entries
https://github.com/opnsense/plugins/blob/master/dns/unbound-plus/src/opnsense/scripts/OPNsense/Unboundplus/dnsbl.py#L33
In this case i think it would be a little better if the regex only checks for valid domain name chars instead of any chars:

`re_blacklist = re.compile(r'(^127\.0\.0\.1\s|^0\.0\.0\.0\s)([\w.-]+)|^([\w.-]+$)', re.I)`

**Expected behavior**
Blocked sites should not be reachable, not blocked sites should be reachable.
At the moment this is not the case anymore because for many of the lists there is generated bogus dnsbl.conf and therefore the blocking breaks and in worst case all sites are blocked.

**Environment**
OPNsense 20.1.1 (amd64, OpenSSL).
os-unbound-plus-devel 0.4

**Comment by pkejval** [comment]
Sorry about that. Should be solved by https://github.com/opnsense/plugins/pull/1694

**Comment by marunjar** [comment]
thanks, it is a lot better now but yet not completely safe.

According to https://tools.ietf.org/html/rfc1035 there are less characters allowed than are captured by `[^\s]+`.

eg. following two lines are valid entries with the current regex even though they should not be.

```
0.0.0.0 coin-hive.*.com#asdfasd
0.0.0.0 coinhiasdfv.*./%&§()e.com
```
eg. following line is not valid although it should be

```
AuThedMine.cOm
```

**--> i would propose a change to `(^127\.0\.0\.1[\s]+|^0\.0\.0\.0[\s]+)([\w.-]+)\s|^([\w.-]+$)`**

So `[\w.-]` includes all characters, all digits, `_`, `,` and `.` but nothing else.
It may happen that a domain name is cut if it contains #/%&§ or something else but at least it would not lead to any problems with unbound.

**Comment by pkejval** [comment]
Thanks for suggestion! Looks very promising: https://regex101.com/r/bKDk93/1 I'll test further at my machines.

**Comment by pkejval** [comment]
First observation: My dnsbl.conf size before applying your suggestion was 33 955 kB, after is 18 351 kB.

**Comment by pkejval** [comment]
@marunjar Does my pull request solved reported bug? Can we close issue?

**Comment by cioby23** [comment]
Is this fixed ? I have installed OPNsense 20.7 and the Unbound DNSBL are not working at all. I select several lists from the dropdown and I still see the ads or domain which should be blocked are still reachable.

**Comment by pkejval** [comment]
It should be working. Which lists are you using? Can you test it with dig or nslookup command against your OPNsense DNS server?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cioby23** [comment]
I was doing some tests with the AdAway and BlockList.site Ads list. I checked for example **tpc.googlesyndication.com** locally on OPNsense shell and also from my PC behind the LAN

OPNsense shell
------------------------------------------------------------------
nslookup tpc.googlesyndication.com 127.0.0.1
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:   tpc.googlesyndication.com
Address: 0.0.0.0

LAN PC behind OPNsense
-------------------------------------------------------------------
nslookup tpc.googlesyndication.com 192.168.40.1
Server:         192.168.40.1
Address:        192.168.40.1#53

Name:   tpc.googlesyndication.com
Address: 0.0.0.0

It is strange because it resolves to 0.0.0.0 but when I browse for example to speedtest.net I still see the ads on the page and the domain tpc.googlesyndication.com returns 200 OK when I inspect the page content.
![image](https://user-images.githubusercontent.com/7124193/89101018-fa266780-d404-11ea-9eb2-45bac7fe615b.png)

**Comment by cioby23** [comment]
Ok after doing some more tests it appears to be working when using Chrome and Firefox in incognito/private mode. I tried clearing cache before but somehow it did not work as it should.

**Comment by pkejval** [comment]
Check browser settings. I suspect that your browser is using DNS-over-HTTPS instead system DNS.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
