### ISSUE TITLE
Plugin Request: PeerVPN (full mesh topology)

### ISSUE THREAD

**Issue by ghost** [opnsense/plugins#173]
opnsense provides different internal services and plugins for creating a virtual private network between different hosts. A lot of people use OpenVPN because you may use it for small "remote access scenarios" or to connect "big business networks".

## General

A few months ago, I found a really small tool which is names "PeerVPN", which creates a peer-to-peer vpn with a full mesh topology. So you do not need some kind of central entry point and nodes can go down without shutting down the whole vpn.

PeerVPN is maintained by Tobias Volk (@tobiasvolk / @peervpn) and it also have an official website https://peervpn.net

#### About PeerVPN

PeerVPN is a software that builds virtual ethernet networks between multiple computers. Such a virtual network can be useful to facilitate direct communication that applications like file sharing or gaming may need. Often, such direct communication is made impossible or very difficult by firewalls or NAT devices.

Most traditional VPN solutions follow the client-server principle, which means that all participating nodes connect to a central server. This creates a star topology, which has some disadvantages. The central node needs lots of bandwith, because it needs to handle all the VPN traffic. Also, if the central node goes down, the whole VPN is down too.

A virtual network built by PeerVPN uses a full mesh topology. All nodes talk directly to each other, there is no need for a central server. If one node goes down, the rest of the network is unaffected.

Configuring PeerVPN is easy. You just need to configure a network name, a password and the contact information (IP address and port) of another PeerVPN node. Adding a new node to an existing network doesn't require the existing nodes to alter their configuration, because its IP address is automatically distributed across the whole virtual network.
 
#### Features

- Ethernet tunneling support using TAP devices.
- IPv6 support.
- Full mesh network topology.
- No NAT reconfiguration necessary, only one node with a public address is required.
- Shared key encryption and authentication support.

#### Documentation

There is a small tutorial that explains how to setup a simple VPN. The configuration options are explained in the sample peervpn.conf that is bundled together with the program.

#### Platforms & Dependencies

PeerVPN is available for Linux and FreeBSD. Additionally, one of the following crypto libraries is required:

- LibreSSL (recommended)
- OpenSSL v.1.0.x (note: the 1.1.x series introduced incompatible API changes and will unfortunately not work)
 
#### License

PeerVPN is licensed under the terms of the GPLv3.
 
#### Contact

If you have any questions or bug reports, contact me at mail@tobiasvolk.de.

_(Copied from https://peervpn.net)_

## OpenSSL 1.1.x

Tobias Volk says that OpenSSL 1.1.x is not supported but I wrote a patch for PeerVPN 0.044 which adds support for 1.1.x and higher. I also informed the author but he says it will take some time to merge it into upstream because he currently works on another project. So in a few weeks, PeerVPN may contain this fix.

Patch: https://wevcode.de/snippets/3

## Possible or not?

So it is possible to add PeerVPN **as a plugin** to opnsense? I would try to work on it, because I really want to use it on my installations. But I do not want to work on a project which has no chance to be integrated (project goals, licences, other criteria).

**_Let's add a really small but powerfull functionality to opnsense!_**

**Comment by wevcode** [comment]
@fichtner You already helped me working with opnsense development. Maybe you can write a small statement as an answer to this request. Thank you!

**Comment by fichtner** [comment]
@wevcode sure :)

First we need to add a binary port for peervpn, after that I can help with general direction of a plugin, not a lot with coding.

There are no issues with OpenSSL/LibreSSL, this fits perfectly. One question though, is peerpvpn still actively developed?

**Comment by wevcode** [comment]
@fichtner Great!

Oh this might be easy, I have some experience with building it on different platforms. :)

Well, my patch only adds support for 1.1.x but it does not remove support for older versions, so it might be usefull for upcoming releases.
Yes, but only by Tobias Volk. It is only a small and simple solution so there is not a lot of code to maintain and nothing makes it unstable. But I am also currently reading the whole code because I am interested in its basic idea and I might want to add some features for me.

Can you give me a hint where to add a binary port?

**Comment by fichtner** [comment]
here is an initial port... https://github.com/opnsense/ports/commit/68d715dc0db7baa06586103a7d2bda1ad44cd822

You can install this with:

    # opnsense-code tools ports
    # cd /usr/ports/opnsense/peervpn
    # make install

We can include your patch, but it will only be useful if we push it to FreeBSD ports. We don't intend to use OpenSSL 1.1 any time soon as there are too many compatibility issues with our bundled software. Some tools just aren't ready yet.

**Comment by wevcode** [comment]
@fichtner So it will download 0.044 from peervpn.net when I run `make install`? Does not really undestand opnsense port system.

I would include it, so **if** you want to switch to 1.1.x, you have one port less which has to be modified.

I think I will use _tinc_ as an example plugin to create the peervpn one. 👍

**Comment by AdSchellevis** [comment]
@wevcode this looks quite similar to TincVPN (https://www.tinc-vpn.org/) for which we have a plugin available, I don't want to stop your quest, but if you don't know it yet, it might be worth investigating.

**Comment by fichtner** [comment]
@wevcode yes, the ports framework will download, configure, build and install. If you have LibreSSL on your OPNsense it will build against that, otherwise OpenSSL. Very simple and effective although the full tree is a bit heavy.

This is so that when 17.1.9 comes out, you'll be able to install the package from the binary repository instead and don't have to worry about building at all:

    # pkg install peervpn

Please send your OpenSSL 1.1 patch (franco@opnsense DOT org), and I'll add it to the build. :)

@AdSchellevis the program is really tiny and has no dependencies... we'll see if this will be a plugin, but OTOH it's easily configured from the command line as well.

**Comment by AdSchellevis** [comment]
@fichtner just saying there are alternatives, certainly don't want to stop your quest :)

**Comment by wevcode** [comment]
@AdSchellevis You are right, tinc can do the same. But PeerVPN makes it possible to simply put multiple nodes with one shared secret together, so you have a mesh vpn in 1 minute. See @fichtner .

@fichtner You can download it from the given url. :)

**Comment by fichtner** [comment]
@wevcode ah, thanks, sorry, missed that!

**Comment by wevcode** [comment]
@fichtner No problem! You might also want to include this patch: https://wevcode.de/snippets/4

PeerVPN logs dropped packets, which can occour because of UDP and full buffers. I spoke to the author and he said that it is a normal behavior. Nevertheless it might fill up our logs quickly so you can disable this by applying this patch. _It will not disable any other warnings!_

**Comment by wevcode** [comment]
@fichtner Sorry, snippet error. Now it should be correct. :)

**Comment by fichtner** [comment]
Second batch: https://github.com/opnsense/ports/commit/4c72afdb6f7104

Can get the latest via:

    # opnsense-code ports && cd /usr/ports/opnsense/peervpn && make clean reinstall

**Comment by wevcode** [comment]
@fichtner Thank you! I will try to start with the plugin itself. :)

**Comment by wevcode** [comment]
@fichtner PeerVPN is now installed but how can I set up my own plugins repository so I see all changes in realtime? `make mount`does not work.

**Comment by fabianfrz** [comment]
I work this way:
```
cd src
scp -r opnsense root@192.168.1.1:/usr/local/.
```

This works well too.

**Comment by fichtner** [comment]
@wevcode I am guessing you have a plugin directory ready?

To install the files:

# make install

To remove the files:

# make remove

To collect changes from the files installed into the plugins dir:

# make collect

**Comment by mimugmail** [comment]
Is there some progress? 

I looked at the example conf but I'm missing an option to inject routes in order to tunnel local subnets, or multicast in order to use OSPF within the VPN.

**Comment by fichtner** [comment]
closing this until there is new progress :)

**Comment by bmullan** [comment]
I'd worked with PeerVPN previously to interconnect LXD/LXC containers in a auto-learning Mesh VPN with Host container servers on AWS EC2, my Lab and Digital Ocean.

Tobias Volk (PeerVPN developer) was a Computer Science PHD candidate at the time but has since taken a job in EMEA with a large company.   I found Tobias easy to communicate with regarding questions etc.

PeerVPN was very easy to configure and the auto-learning worked great & didn't require any "central" node.   

Once I configured the 1st two Peers so they connected then every new Server only had to be configured to connect to at least one of the existing mesh VPN servers and the new server would auto-learn all of the other servers that were part of "that" mesh.

I could also configure multiple mesh VPNs each isolated from the other on servers.   My goal was to get LXD/LXC containers on any Host server to have an L2 or L3 connection to any other containers on any other Host server.

My last config was to set a single DHCP source for each "mesh" so containers within that Mesh got their IP addresses from that range of addresses configured for that particular mesh.  This all worked well.

I had previously tried Tinc but found it much more difficult to setup/manage than PeerVPN or ZeroTier.
