### ISSUE TITLE
net/haproxy: service fails to start when real server DNS does not resolve

### ISSUE THREAD

**Issue by ssbarnea** [opnsense/plugins#1787]
I do have several backend servers (real servers) which are accessible only when VPN is up, which is not 100% of the time. These DNS entries can be resolved only when the VPN is up.

I observed that haproxy service fails to start when any of the DNS entries from that list fails to resolve, and that has serious reliability issues. 

I am not sure if this is haproxy specific bug but it clearly worth being documented. Maybe someone known how to implement a workaround for this?

IMHO, DNS failing to resolve should be treated the same as an offline server.

**Comment by fraenki** [comment]
> I am not sure if this is haproxy specific bug but it clearly worth being documented. 

It's not a bug, it's the way HAProxy is designed. The HAProxy developers decided that it would be better to abort startup when the configuration is not working (which is the case when DNS names can't be resolved) instead of starting with an incomplete or nonfunctional configuration.

You should try to solve your DNS resolution issue. Either by setting up a local DNS cache/slave/whatever or by using IP addresses instead of DNS names in HAProxy's configuration.

**Comment by fraenki** [comment]
I have to correct myself. While I'd _personally_ prefer the way HAProxy behaves in it's default configuration, an option is available to control HAProxy's behaviour with regards to DNS resolution:

```
defaults
    # never fail on address resolution
    default-server init-addr last,libc,none
```
Source: http://cbonte.github.io/haproxy-dconv/2.0/configuration.html#init-addr

I'll add support for this option in one of the next releases.

**Comment by ssbarnea** [comment]
Indeed, for the moment I replaces the two DNS entries with statip IPs and this should workaround the issue.

I have ~10-15 backend servers there (containers), the chance of having one down when haproxy starts is clearly bigger than 1%. Being able to configure this behavior is probably the best approach. Thanks.

**Comment by ovv** [comment]
While setting `default-server init-addr last,libc,none` would allow HAProxy to startup it will never retry the DNS resolution. Meaning that even if your container resolves after a while HAProxy won't start proxying requests.

I believe a better fix would be to create a resolver https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#5.3.2 . Sadly this is not possible yet in the web UI.

This would also make proxying to backend registered to OPNSense via DHCP work more reliably.

**Comment by fraenki** [comment]
> I believe a better fix would be to create a resolver

Could you provide an example for a resolver section that would solve the OP's issue?

**Comment by ovv** [comment]
I believe this should work:
```
resolvers local
  nameserver local 127.0.0.1:53
```
and
```
resolvers local
```
in the server line like:
```
server s1 app1.domain.com:80 check resolvers mydns
```

I can try to test this next weekend to see if it integrates well with DNS & DHCP

**Comment by fraenki** [comment]
In the upcoming release 2.24 of os-haproxy the following new features will be available:

`Settings -> Default Parameters -> DNS Resolve Order`

This new option should resolve the OP's issue. You just need to add "none" at the end of the list. Now unresolveable hosts are no longer a FATAL error, but will only issue a WARNING instead. This allows HAProxy to startup even when DNS does not resolve.

Next add a "resolver". This way HAProxy should retry to resolve the address:

`Advanced -> Resolvers -> Add`

You probably need to use a high number for retries, but I haven't tested this.
Finally add the resolver to your "Backend Pool" (advanced option) and apply the configuration changes.

I'd love to get some feedback, because in my environment I oculd not fully test the "resolvers" feature.

**Comment by ovv** [comment]
@fraenki I can looks into testing this but I'm not familiar how to install development version of the plugins.

**Comment by fraenki** [comment]
@ovv This time there is no easy way to test, because there are too many changes in the pipeline. Besides that the new version involves a change to the configuration model (XML), and this probably breaks backwards-compatibility with previous versions. So I'm absolutely fine if you would test the final version of os-haproxy 2.24 when it becomes available. :)
