### ISSUE TITLE
Quagga: updating networks/interfaces tabs doesn't update ospfd.conf

### ISSUE THREAD

**Issue by backerman** [opnsense/plugins#184]
Steps to reproduce:

1. Enable ospfv2.
2. Add a network or interface configuration.

Expected: `/usr/local/etc/quagga/ospfd.conf` contains the configuration as entered into the GUI.

Actual: `/usr/local/etc/quagga/ospfd.conf` is not updated. If the user then unchecks and re-checks the "Enabled" box in the General tab, the configuration is then updated as expected.

Tested using:

- OPNsense 17.1.8-amd64
- FreeBSD 11.0-RELEASE-p10
- LibreSSL 2.4.5
- os-quagga 1.2.0

**Comment by fabianfrz** [comment]
@backerman The configuration is currently updated after clicking the save button of the general form. You should not have to uncheck or recheck anything.
This is currently in any routing protocol that is supported but I have not documented this behaviour because I have designed it to work this way. The reason was that adding Networks, Interfaces etc. should not put much load on the neighbours.

**Comment by fichtner** [comment]
Works as expected, needs "Apply/Save".
