### ISSUE TITLE
postfix: Support for LDAP / recipient verification

### ISSUE THREAD

**Issue by jd77777777** [opnsense/plugins#1926]
If using postfix as a mail gateway to a backend mail server (e.g. Exchange), it would be useful to have a recipient verification using ldap or ActiveDirectory. postfix already supports this using postfix-ldap, but the opnsense plugin currently doesn't support this extension. If this extension is available, the configuration may look like this.

main.cf:

relay_recipient_maps = ldap:/etc/postfix/ldap_relay_recipient_maps.cf

ldap_relay_recipient_maps.cf (example):

server_host = ad-01.example.com
              ad-02.example.com
search_base = dc=example, dc=com
version = 3

bind_dn = CN=postfix,CN=Users,DC=example,DC=com
bind_pw = password

query_filter = (proxyAddresses=smtp:%s)
result_attribute = mail

**Comment by mimugmail** [comment]
@fichtner this would require postfix-ldap pkg, for me it's ok. Leave the decision to you :)

**Comment by jassonmc** [comment]
May I propose a more universal solution?

In my current OPNsense 20.7.1 setup, Postfix is missing an extremely vital instruction in its main.cf:
smtpd_recipient_restrictions  ->  reject_unverified_recipient

Since OPNsense is only a Postfix gateway and not the final destination, it should never, ever accept mails, which are afterwards non deliverable to it's final destination.

If the final destination is a Postfix mail server, nothing else needs to be configured.

If the final destination is Exchange 2013 or higher, you will need to:
Install AntiSpamAgents (& $env:ExchangeInstallPath\Scripts\Install-AntiSpamAgents.ps1)
Enable-TransportAgent "Recipient Filter Agent"
Get-RecipientFilterConfig | FL Enabled,RecipientValidationEnabled (Should show enabled)

Above example will use the final destination mail server also as the verification server, which should be usable for most single mail server installations.

**Comment by jd77777777** [comment]
@jassonmc: I am not really getting your point. My idea is that if the opnsense (postfix gateway) checks the recipient against the active directory or some other ldap server, the opnsense could already reject the messages without having unnecessary load on the email server behind (e.g. exchange). In my opinion it would reduce the load on the "real" mail server in case of a DDoS attack.

**Comment by mimugmail** [comment]
@jd77777777 A DDoS would then flood your AD cause of massive LDAP queries :)

**Comment by jassonmc** [comment]
@jd77777777 
Exactly what I thought, when @mimugmail mentioned it.
I'd rather have my mailserver DDoSed for some time then my critical authentication infrastructure.
