### ISSUE TITLE
net-mgmt/zabbix-agent version 5.0 LTS and zabbix-agent2

### ISSUE THREAD

**Issue by psanwald** [opnsense/plugins#1938]
Zabbix 5.0 LTS is out since a few months. Also there's a new zabbix-agent2 feature. I did not test, if the actual agent plugin (version 4.0.21) works with a zabbix server 5.0, but since they normally need to be of the same major version, I do not think so. Does anybody know, if there's a plan to upgrade the zabbix agent plugin or add a corresponding one? Also there is a os-zabbix-agent (version 1.7) package of which Iam not sure, what it's to be used for. I want to upgrade my zabbix system from 4.2 to 5.0 soon and I'd be glad if somebody could enlight me. And: Yes, I already checked the forum and the github infos.

**Comment by fraenki** [comment]
Link #1830

**Comment by Starkstromkonsument** [comment]
The agent usually does not need to be the same major version as the server/proxy (See: https://www.zabbix.com/documentation/current/manual/installation/upgrade/packages/debian_ubuntu). It can happen that some new features of zabbix are not supported by hosts running older agents though.

The agent2 is a completely rewritten agent that will probably require a new plugin and it is not available from ports so far. The former agent is not EOL as far as I know and the version 5.0 LTS will be supported for the next three years.

**Comment by fraenki** [comment]
I think these are two topics that should be handled individually. First, we will update os-zabbix-agent to Zabbix 5 soon. But zabbix-agent2 is a completely different topic that I'm not going to tackle anytime soon.

**Comment by fraenki** [comment]
We will upgrade to Zabbix Agent 5 with the release of os-zabbix-agent 1.8, which will probably arrive with OPNsense 20.7.2 in a few weeks.

I'll close this issue now. Please open a new feature request for zabbix-agent2 if you think it's worth it, but be aware of the previously mentioned limitations (no FreeBSD port, no contributor).

**Comment by simplerezo** [comment]
Why did you upgrade the Zabbix Agent and do not create a new plugin "zabbix5-agent" as for Zabbix Proxy ?
Agent 5.0 cannot connect to Zabbix Proxy or Server 4.0.... to a basic upgrade breaks a working configuration... :(

https://www.zabbix.com/documentation/4.0/manual/appendix/compatibility

**Comment by fraenki** [comment]
@simplerezo In my experience newer Zabbix Agents work well with older Zabbix Servers and Proxies.

**Comment by simplerezo** [comment]
Officially it's not the case:
"Note that Zabbix agent newer than 4.0 cannot be used with Zabbix server 4.0."
(see my previous link...)

**Comment by Starkstromkonsument** [comment]
@simplerezo I never experienced problems with the agents versions either.

- Is your "broken" agent being monitored by server or proxy? Which versions do they have?
- Can you post some logging output to get an idea of the exact errors please?

**Comment by fraenki** [comment]
I kindly ask you to discuss specific issues this in the forums instead. :)

**Comment by mimugmail** [comment]
@simplerezo only new values offered by zabbix-agent 5 are not reported to zabbix 4 server. I have couple of v5 agents running fine against v4 server.

**Comment by barzog** [comment]
According to documentation https://www.zabbix.com/documentation/current/manual/discovery/low_level_discovery
ANY discovery rules on zabbix-agent 4.2+ is not compatible with zabbix-server 4.0 (in my case this was vfs.fs.discovery and net.if.discovery
Old agents (4.0) returns data in this format:
[oleg_ga@zabbix ~]$ zabbix_get -s 127.0.0.1 -k net.if.discovery
**{"data":**[{"{#IFNAME}":"ens192"},{"{#IFNAME}":"lo"}]}
Newer ones omits data:
root@opnsense:~ # zabbix_get -s 127.0.0.1 -k net.if.discovery
[{"{#IFNAME}":"em0"},{"{#IFNAME}":"enc0"},{"{#IFNAME}":"lo0"},{"{#IFNAME}":"pflo                                                                               g0"},{"{#IFNAME}":"pfsync0"},{"{#IFNAME}":"ovpns1"},{"{#IFNAME}":"ovpns2"}]
root@opnsense:~ #

Exactly as stated in doc:
Note that since Zabbix 4.2, the format of the JSON returned by low-level discovery rules has been changed. It is no longer expected that the JSON will contain the "data" object. Low-level discovery will now accept a normal JSON containing an array, in order to support new features such as the item value preprocessing and custom paths to low-level discovery macro values in a JSON document.
As a result of the changes above, newer agents no longer will be able to work with an older Zabbix server.

So, pls revert those changes back and go in a way as simplezero suggested: zabbix4-proxy+zabbix4-agent for those with 4.0 servers and zabbix4-proxy and zabbix5-agents for new one.

**Comment by fraenki** [comment]
I've locked this issue now. If someone is willing to maintain os-zabbix-agent with version 4.x, please submit a pull-request for review.
