### ISSUE TITLE
OpnSense postfix as secure mail gateway

### ISSUE THREAD

**Issue by XtraLarge** [opnsense/plugins#2020]
Hello,

I've tried to use OpnSense as a secure smtp gateway. 

My problem is that I've some different domain names. Every one with a single certificate. I ve found a way to import the certificates, but I've found no way to choose some of them!!! 

Only one is possible, is that that true?!?! ..... 

Hint. I read that postfix can use some certificates, if you paste them in the same file.

**Comment by mimugmail** [comment]
Where is the link to this doc for using multiple certs? How does this handle different keys in one file?

**Comment by fichtner** [comment]
Not sure virtual hosting is a valid concept for mail servers, especially since for HELO/EHLO you get the host name mismatch.

Generally what you can do is use HAProxy or Nginx to build this kind of setup....

As for "secure mail gateway" I think you have your concepts not properly worked out: a secure mail gateway uses mail encryption (PGP, S/MIME) on top of transport encryption (TLS). A mail server with TLS support is just a mail server in the 21st century. ;)


Cheers,
Franco

**Comment by jassonmc** [comment]
We are also using OPNsense and it's Postifx plugin as mail gateway for multiple mail domains.
The important bit here is, that you would point your MX records for those mail domains to your WAN DNS name of your OPNsense. This way only 1 cert is needed, which is also correct.
We are talking here only about SMTP, not any Webmail, IMAP, POP3 or the like.
For everything non-SMTP you would, as @fichtner already mentioned, use HAProxy, which is capable to present different certs, depending on defined rules.

**Comment by fichtner** [comment]
@jassonmc's solution using proper MX is indeed preferable as it would not mask the actual hostname of the server :)

**Comment by XtraLarge** [comment]
> Where is the link to this doc for using multiple certs? How does this handle different keys in one file?

I've found a description for sni at https://technikfreak.net/tipps-tricks/postfix-3-4-lets-encrypt-und-server-name-indication-sni/

**Comment by XtraLarge** [comment]
> We are also using OPNsense and it's Postifx plugin as mail gateway for multiple mail domains.
> The important bit here is, that you would point your MX records for those mail domains to your WAN DNS name of your OPNsense. This way only 1 cert is needed, which is also correct.
> We are talking here only about SMTP, not any Webmail, IMAP, POP3 or the like.
> For everything non-SMTP you would, as @fichtner already mentioned, use HAProxy, which is capable to present different certs, depending on defined rules.

OK, it's right that you must configure an working mx record for the domains, but how did you configure that postfix choose the right certificate for every domain? .... That's my point?

**Comment by jassonmc** [comment]
You should probably perform an internet search on the topic SMARTHOST.
Let's make an example:

Your OPNsense WAN IP is 1.2.3.4
Your DNS A record for that IP is gw.mybusiness.xyz
You have two mail domains: mybusiness.xyz and mypleasure.xyz
You define for both domains a single mx record that points to gw.mybusiness.xyz
The mx record tells an outside party, where your mail infrsatructure entry point is, which in this case is gw.mybusiness.xyz

When I am sending you na an email to XtraLarge@mypleasure.xyz, my sending mail server will make an mx lookup for domain mypleasure.xyz and will identify gw.mybusiness.xyz as the mail exchanger. So my mail server will contact that mx, which will present its single postfix certificate, which corectly states, that it's name is gw.mybusiness.xyz.
Your OPNsense Postfix plugin now takes that mail and will deliver it to the mail server you have defined in the Postfix plugin settings. You might have a domain entry that says domain: mypleasure.xyz  and destination: 10.11.12.13
in case the same mail server is hosting also your other domain, you will point that other domain to the same destination.
Technically, my sending mail server will never talk directly to your internal mail server, which is located at 10.11.12.13, so I only care for your mail infrastructure entry point, which is your gw.mybusiness.xyz.

Now the other way round; you are sending a mail to me to lets say jassonmc@otherbusiness.xyz.
You will have to configure a smart host entry on your sending mail server, so that mails are not sent directly to the internet, but are sent via smart host feature to your OPNsense Postfix plugin. In the above example that could be the LAN IP of your OPNsense firewall, which could be 10.11.12.1.

Since you're always communicating with the outside world always through that OPNsense Postifx mail gateway, an outside party will never have to talk to one of your internal mail servers directly.

If you're still confused; it's very common, that the mx server does NOT have the same domain name as the mail domains it's serving. A shared mail hosting providers daily business.
That's also where SPF DNS entries come into play, where you can define who is allowed to send mails on your behalf, which could be any server on earth, which does not have to share the same domain name as you.

Keep in mind, that mail domains and domains assigned by an A record to a public IP are two different things and there is no need for a match. In super small scenarios, it can, but there is no must.

**Comment by XtraLarge** [comment]
OK, I think i understand it. 
You bypass the certificate proplem in the way you give the smtp gateway only one dns name. All Other domains choose that name as the mx gateway. I think this will work, but it isn't so "nice", because anyone can identify the domains are working together and they are not seperated every by it's own.

But you're right it is a way!! .... Thanx a lot!

**Comment by jassonmc** [comment]
If you want to hide the fact, that your mail gateway is related to one of the mail domains you're hosting, then you could ofc use a totally unrelated domain for the gateway.
If you want to hide the fact, that multiple of your mail domains have the same mx, then it will become more complex.
An mx can ever only respond to a single fqdn, since the so called reverse dns entry will always have to match your forward dns entry.
You could setup 2 OPNsense gateways, each with it's own public IP, but that's not very efficient in terms of operations effort.
