### ISSUE TITLE
os-git-backup: Do a `git pull` first

### ISSUE THREAD

**Issue by lattera** [opnsense/plugins#2083]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
The os-git-backup plugin doesn't do a `git pull`, when it likely should. I'm using a config backup repo that is shared among other servers (like, our web server, storing the nginx config from that in the same repo).

**Describe the solution you'd like**
Before adding the new config to the git repo and committing that, it might be best to do a `git pull`.

**Describe alternatives you've considered**
Alternatively, we could do a `git fetch origin` after the commit and a `git rebase origin/master`. But that's two commands instead of the one above.

**Comment by AdSchellevis** [comment]
it's intentional https://docs.opnsense.org/manual/git-backup.html#conflict-resolution

**Comment by lattera** [comment]
This ticket isn't about resolving conflicts, though.

**Comment by AdSchellevis** [comment]
It's in the same area as conflict resolution, what happens if the pull isn't possible, how to handle configuration changes, etc, etc. When you perform conflict handling command line, it's all simple, things tend to get very complex if every action should result in a guaranteed consistent state. 

I don't mind if someone describes a rocket proof addition for this to happen, without risking a lot of corner cases. Just noting that how it functions now is exactly how it was intended. The upstream should be bare as described (which can be any new branch, dedicated for your just configured box).

**Comment by lattera** [comment]
If the git pull isn't possible, neither is the git push. Just check for an error state after git pull, and report the error to the user for manual resolve via ssh.

I can submit a PR to do just that, if you'd like.

**Comment by AdSchellevis** [comment]
you can always push to a (new) bare repo (which is automatically created when choosing a new branch as well). The current setup doesn't require any manual interaction when used as intended. You can add a PR, but if it's just adding a pull, don't bother doing so since as explained in the docs its not the intended use-case. 

Maybe I'm overlooking a sequence of actions that will always reach a consistent state, if that's the case I gladly review the PR.

**Comment by lattera** [comment]
I'm also curious about why there would ever be a merge conflict. If I push other configs to the repo, like my nginx.conf, the nginx.conf file will never confict with opnsense's config.xml.

Effectively, if I structure the repo in such a way that a merge conflict never happens, then the argument about merge conflicts is moot.

So doing a git pull would then be beneficial. I think you're trying to make things too complicated, when they're in fact really simple.

**Comment by AdSchellevis** [comment]
Let’s agree to disagree. Since you can change destinations easily, history might collide, enforcing what we do now is simple an always works, no matter how the remote is setup (a branch is dedicated for a box).

When offering other possibilities, one should be able to handle them from the ui.

**Comment by lattera** [comment]
So, effectively, I'm going to need two repos to store config files for my infrastructure? That's two repos I need to ensure incredibly tight security of?
