### ISSUE TITLE
os-git-backup: Broken in newest release

### ISSUE THREAD

**Issue by qdrop17** [opnsense/plugins#2105]
**Describe the bug**
This plugin does not seem to work after updating to OPNsense 20.7.4. When clicking on Setup/Test Git, the changes get pushed properly. When just doing changes, nothing happens, nothing gets pushed.

**Logs**
```
Nov 12 08:44:01 gw-devzh-01 configctl[9814]: event @ 1605167041.18 msg: Nov 12 08:44:01 gw-devzh-01.intranet.digitec config[66028]: config-event: new_config /conf/backup/config-1605167041.1785.xml  
Nov 12 08:44:01 gw-devzh-01 configctl[9814]: event @ 1605167041.18 exec: system event config_changed 
Nov 12 08:44:06 gw-devzh-01 configctl[9814]: event @ 1605167046.31 msg: Nov 12 08:44:06 gw-devzh-01.intranet.digitec config[66028]: config-event: new_config /conf/backup/config-1605167046.3093.xml  
Nov 12 08:44:06 gw-devzh-01 configctl[9814]: event @ 1605167046.31 exec: system event config_changed 
Nov 12 08:44:44 gw-devzh-01 configctl[9814]: event @ 1605167083.63 msg: Nov 12 08:44:43 gw-devzh-01.intranet.digitec config[68712]: config-event: new_config /conf/backup/config-1605167083.6259.xml  
Nov 12 08:44:44 gw-devzh-01 configctl[9814]: event @ 1605167083.63 exec: system event config_changed
```

**Environment**

OPNsense 20.7.4-amd64
FreeBSD 12.1-RELEASE-p10-HBSD
OpenSSL 1.1.1h 22 Sep 2020

**Comment by AdSchellevis** [comment]
The automatic push happens once a day (as all backup tasks), add+commit after changes 

ref: 
https://docs.opnsense.org/manual/git-backup.html

https://github.com/opnsense/core/blob/51489f83de93840f2771fd65938658cd25f5a01c/src/etc/inc/plugins.inc.d/core.inc#L199
https://github.com/opnsense/core/blob/4e9a8abf9872e8b56afca1b209c1482886961fd3/src/etc/inc/system.inc#L962-L963

**Comment by FingerlessGlov3s** [comment]
Hi Ad,

Would it be possible to add more logging to the git backup? To say if it finished successfully saying with no commits pushed or x commits pushed?

Would make testing and debugging easier.

Backup code
https://github.com/opnsense/plugins/blob/master/sysutils/git-backup/src/opnsense/mvc/app/library/OPNsense/Backup/Git.php

**Comment by AdSchellevis** [comment]
@FingerlessGlov3s One could parse the output of the git push, but to be honest, it doesn't really provide you much more detail than it already does (all known error situations are returned already).

https://github.com/opnsense/plugins/blob/8db3b0e5eca43e4aa485fb06a539dd8c6d06e802/sysutils/git-backup/src/opnsense/mvc/app/library/OPNsense/Backup/Git.php#L169-L179

Easiest option to debug issues is to use git manually, one could add a section to the docs (https://docs.opnsense.org/manual/git-backup.html) how to use git for that matter, I wasn't really planning on doing that myself since all pointers are already in there.

The config hook doesn't really have additional logging, but I haven't seen flows where these actions in normal circumstances can fail myself, and if they do, you're likely better of inspecting /conf/backup/git with git manually. 

https://github.com/opnsense/plugins/blob/master/sysutils/git-backup/src/etc/rc.syshook.d/config/10-git-backup#L70-L75

**Comment by bramevo** [comment]
Should really add a notification inside the plugin information that updates will only be pushed once a day. I was also confused by this and took me some trial and error to figure this out. Is also not visible in the cron section.

By simply mentioning this in the plugin or better in the GUI in the configuration block, it will avoid a lot of confusion.

**Comment by AdSchellevis** [comment]
the manual often is a good place to check for details https://docs.opnsense.org/manual/git-backup.html#concept , although the standard scheduled task and the ability to schedule additional ones using cron might be good to clarify some more (https://docs.opnsense.org/manual/backups.html). So anyone up for the job, can improve the documentation here https://github.com/opnsense/docs
