### ISSUE TITLE
Nginx reverse proxy filters DAVx⁵ Android app

### ISSUE THREAD

**Issue by molusk** [opnsense/plugins#2175]
Hi,

I could not access anymore to my contacts and calendars from my phone since I migrated from Apache2 reverse proxy on my NAS to opnsense and Nginx.
I ended up finding DAVx⁵ uses a user-agent which triggers bot protection in opnsense implemetation of Nginx :

`DAVx5/3.3.7-ose (2020/11/30; dav4jvm; okhttp/4.9.0) Android/10\r\n`

**okhttp** is one of the string matching [line 220 of http.conf](https://github.com/opnsense/plugins/blob/b2d5d685e32968604feea055b8d6285211d4d0e1/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf#L220) file.

The workaround is obviously the disable bot protection option and it is ok for me until I want to access my Nextcloud instance from outside my network.

I can think of an if/else dirty fix and may propose a Pull request for it but if anyone has a nicer solution, it may be better.

I also published the issue on [DAVx⁵ forum](https://forums.bitfire.at/topic/2448/davx-user-agent-filtered-by-opnsense-nginx).

**Comment by molusk** [comment]
opnsense version: 20.7.7
nginx plugin version: 1.19

To replicate the issue you have to install DAVx⁵ on an android phone or emulator and try to access a nginx protected server with bot protection activated. The request should be immediately blocked by nginx. No request reaches the web server and the phone appears after a few minutes in the nginx ban list.

**Comment by molusk** [comment]
A nicer way to fix this and allow anyone to sort it out would be to allow users to whitelist some user-agents but I am not able to develop this.

**Comment by kulikov-a** [comment]
@molusk 
you can try to disable bot protection and add custom "if ($http_user_agent...return" via server _pre hook
https://github.com/opnsense/plugins/blob/b2d5d685e32968604feea055b8d6285211d4d0e1/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf#L281

**Comment by sjjh** [comment]
The issue seems still existing as of today.

> The workaround is obviously the disable bot protection option and it is ok for me until I want to access my Nextcloud instance from outside my network.

Disabling the bot protection for the http server seems strangely not to work for me.

> you can try to disable bot protection and add custom "if ($http_user_agent...return" via server _pre hook
@kulikov-a Would I be able to whitelist the UA with the _pre hook? And could you please elaborate a little on how this would look like or point me to some documentation. Thx!

**Comment by kulikov-a** [comment]
@sjjh Hi

> Would I be able to whitelist the UA with the _pre hook? 

Disabling bot protection in the GUI should definitely have worked if that was the cause.
Bot UA can be edited in the GUI since version 1.33.
Hooks usage in general described at  https://forum.opnsense.org/index.php?topic=21154.msg99523#msg99523
but..I mentioned using a hook with the idea of ​​creating a custom UA set when disabling bot protection (and before 1.33). If you only need to disable bot protection - disabling it in UI should definitely be enough

**Comment by sjjh** [comment]
Thx for the quick feedback! Disabling bot protection and restarting nginx via the GUI somehow did not work for me. As a dirty hot fix, for now I have removed the UA from the list in the configuration file via the shell. As an update is overdue anyway, I assume that I can solve it permanently by editing the bot UA in the GUI after the update to 1.33. I'll report back, if I'm having further trouble.
