### ISSUE TITLE
Feature Request - plugin for AbuseIPDb.com firewall filtering and reporting

### ISSUE THREAD

**Issue by LPJon** [opnsense/plugins#2183]
**Is your feature request related to a problem? Please describe.**:
Currently I must filter these IPs at my web-server. That means that all other services are NOT filtered with this service. I want to be able to add this protection to my entire network with this service.

**Describe the solution you'd like**:
I want to be able to use abuseipdb.com's API in the form of a plugin to filter IP's that are known for abuse. It needs to use the API of AbuseIPDB.com to collect a list of IP's based on a specified confidence value (Percentage) and a scheduler to update that list. **It should NOT check every IP in real-time by default** which is a service they provide. This would use way too much bandwidth/throughput and even worse create high delay times in connections. It would however be nice to have the option to filter in real-time if desired. This feature should work on both incoming and outgoing connections. This helps protect users inside the network as well when getting email viruses/malware an the user accidentally activates it, as well as device based viruses/malware. Stopping the attack at the network level (No calling out to malware, trojan, or scammer networks from within your network).

This plugin should also have the ability report offending IPs to AbuseIPDB.com if desired.

**Describe alternatives you've considered**:
I don't have any. The only other way to use this service is write scripts that download the list and manipulate the firewall on each back-end server. **You are also not able to setup a script to filter with windows servers at all unless you are a PowerShell wizard.** This option is too difficult to maintain and very unrealistic.

**Additional context**:
AbuseIPDB.com's API also allows for reporting of IPs which are offenders. Actively participating in threat notification is essential to fast reaction times of 0 day threats. I really believe this would give OPNSense a real boost in the IT network security world because I have had really good luck with using this service and it's natively awesome at filtering email scammers. 

**Helpful API documentation for AbuseIPDB.com in order of most valid to least valid:**
https://docs.abuseipdb.com/#introduction
https://www.abuseipdb.com/api.html
https://www.abuseipdb.com/pricing
https://www.abuseipdb.com/csf

**Possible GitHub project that may help implementation** 
https://github.com/vsecades/AbuseIpDb

**Comment by mimugmail** [comment]
Why dont you use firehol alias to block them?

**Comment by LPJon** [comment]
> 
> 
> Why dont you use firehol alias to block them?

I do use firehol as well as 5 other lists, but we still have issues with spam and web site attacks. Only when adding abuseIPDB lists with it do we actually filter about 98% of offending IPs. Without it, it's about 60%. Their lists update very quickly and cool down slowly so this seems to work very well.

**Comment by LPJon** [comment]
So is this request dead in the water or is anyone at least looking into it?

**Comment by LPJon** [comment]
I'm not sure who is in charge here so I don't know who to call on. I have a script installer I just finished writing that utilizes the API of OPNsense to install a cron job and an alias after downloading the IP blacklist form AbuseIPDB. Is anyone interested in helping develop a frontend for this in OPNsense so I can get an actual interface in the webui for it? I could work that out on my own but I'm a noob at OPNsense DEV. Not even sure how I would install the plugin once it's written on other OPNsense firewalls my company has running. Where would I submit it for review by the OPNsense team to get into the repositories? Please is anyone interested?

**Comment by LPJon** [comment]
Wrote my own software to do this and control it through cron jobs. Very disappointed that no one responded to this request. I really expected more from a project this big. I love this software but I do not like DEVs who don't listen or respond to customer requests. Let me ask....why should I keep paying for support if no one is listening or responding? Part of paying for that is for development. I run an IT business and we are/were using your product with our customers. I'm seriously asking myself if we should keep paying for your product. I'm closing this issue since it wasn't worth the time I spent to open it or the time I'm spending now to comment on it.

**Comment by fraenki** [comment]
Instead of writing your own software you could have created a community plugin. This would have been beneficial for other users too.

**Comment by fraenki** [comment]
Thing is, this issue did not get much attention, so your request for help wasn't heard. Besides that it's a good idea to ask precise questions, i.e. describing exactly which issue you are facing when trying to develop something on/for OPNsense. This makes it much easier for others to help. However, asking for help in an issue tracker tends to get unnoticed. I think it's not the right tool for the job.

I'd suggest to use the [forums](https://forum.opnsense.org/) to ask for help, including questions regarding plugin development. Besides that a lot people are available in the #opnsense IRC channel and many of them have contributed code in the past (but it's recommended to linger for several days, because people live in different timezones). I've also found the [example plugin](https://docs.opnsense.org/development/examples/helloworld.html) a good description to learn how to code on OPNsense.

From my personal experience the developers and contributors are friendly and try to help as much as they can. It didn't work out this time, that's a pity, but to be honest, that's understandable if you consider just how many requests are coming in. I was reacting to your comment because I think it was unfair towards the OPNsense project and developers. Not getting enough attention for my personal proposal or issue is possible in any open-source project. Yes, it may lead to frustration, but that's an obstacle to take when using free software, at least in my personal experience.

That being said, this request does cover topics that I'm not familiar with, so I can't help with that. But others in the forum or IRC channel may very well be able to help. Or people on the forums may provide workarounds or alternatives, it tend to be more chattier in the forums.

**Comment by LPJon** [comment]
Now that comment was worth gold. I'll try hopping on the forums then and see what happens. Thank you for pointing me in the right direction. That in it self is a big help.
