### ISSUE TITLE
NUT: Unable to get APC Smart UPS to configure

### ISSUE THREAD

**Issue by Taomyn** [opnsense/plugins#2262]
**Describe the bug**
Whenever I connect via USB and try to configure my APC Smart-UPS 750, the NUT service does not see the UPS and causes the whole firewall GUI to repeatedly stall until I disable NUT. The diagnostic section remains empty.

The UPS works just fine on my Windows 10 PC using Powerchute for Business, but I want to move it to the firewall so it can control it.

**To Reproduce**
1. Plug in Smart-UPS 750, can see it appear on the console
2. Configure is USBHID device
3. Start NUT
4. Nothing

**Expected behavior**
UPS is detected

**Relevant log files**
Tell me what other logs and where they are and I will upload them

```
2021-03-06T12:47:17 | upsmon[30879] | UPS FirewallUPS is unavailable | -- | -- | -- | --
2021-03-06T12:47:17 | upsmon[30879] | UPS [FirewallUPS]: connect failed: Connection failure: Operation timed out |  
2021-03-06T12:45:57 | upsmon[30879] | Communications with UPS FirewallUPS lost |  
2021-03-06T12:45:57 | upsmon[30879] | UPS [FirewallUPS]: connect failed: Connection failure: Operation timed out |  
2021-03-06T12:44:42 | upsmon[24046] | Startup successful |  
2021-03-06T12:44:42 | root[85756] | /usr/local/etc/rc.d/nut: WARNING: failed precmd routine for nut
```

**Environment**

OPNsense 21.1.2-amd64
FreeBSD 12.1-RELEASE-p13-HBSD
OpenSSL 1.1.1j 16 Feb 2021
Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 cores)
os_nut v1.7_1

**Comment by gbakeman** [comment]
This is still an issue, minus the web GUI hanging. I'm trying to connect a Back-UPS NE 670M1. It's setup as a USBHID device, but if I try to restart the nut service:

**service nut restart**
```
nut not running? (check /var/db/nut/upsd.pid).
Network UPS Tools - UPS driver controller 2.7.4
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
No matching HID UPS found
Driver failed to start (exit status=1)
/usr/local/etc/rc.d/nut: WARNING: failed precmd routine for nut
```

**usbconfig**
`ugen0.2: <American Power Conversion Back-UPS NS 675M1 FW:930.a8 .D USB FW:a8> at usbus0, cfg=0 md=HOST spd=FULL (12Mbps) pwr=ON (2mA)`

Someone on the forums may have [narrowed the solution down](https://forum.opnsense.org/index.php?topic=20218.0) to just being a permissions/access issue to the device. Hopefully this can be accounted for in the plugin.

**Comment by Taomyn** [comment]
@gbakeman have you tried the fix? As it's from 2020 I'm not sure how relevant it would be to the later builds of OPNsense. I haven't retried setting up my UPS for some time but it would still be nice to get it working.

**Comment by gbakeman** [comment]
Yes, I can report success and other NUT clients on my network are able to communicate with the NUT server and query information about the UPS.

The first step is to run `usbconfig` on your host (opnsense) to see how the UPS is connected and get its identifier. After that, I'm just going to copy+paste what ittchmh wrote on the forums:

**/etc/devfs.conf**
```
perm    [device ID here] 0770
own     [device ID here] uucp:wheel
```

**/etc/devfs.rules**
```
[nut_usb=10]
add path '[device ID here]' group wheel user uucp mode 0770
```

**/etc/rc.conf**
`devfs_system_ruleset="nut_usb"`

**Restart service to read new config**
`/etc/rc.d/devfs restart`, or `service devfs restart`

I had to create `devfs.rules` and `rc.conf` as new files, but otherwise that's all you need.

As far as solving this issue goes, I'm not very familiar with *BSD-type systems so I can't offer much advice. It seems apparent to me that this comes down to a permissions issue, and as ittchmh discovered through testing, running NUT as root is one way to get around it. I'm not sure if running the daemon as root is desirable though, so this plugin may need to be designed to detect a connected UPS and configure the system so that NUT can communicate with it.

**Comment by djl** [comment]
This also happened to me upon upgrading to 22.1.7. Had to add the `devfs` rules manually to get it working again.

Not sure why this didn't appear until 22.1.7 for me.
