### ISSUE TITLE
DynDns for Wireguard

### ISSUE THREAD

**Issue by lfirewall1243** [opnsense/plugins#2268]
If I use a DynDns name as Endpoint in Wireguard it only resolves the Name when i restart the whole Wireguard Service or disable/enbale the Endpoint.

It would be good if Wireguard is resolving the Name on every Handshake or so.
#2277

**Comment by mimugmail** [comment]
Try to ask at wireguard mailing list, as there is no daemon I'm quite sure this will never be implemented.

**Comment by jkellerer** [comment]
Also found this issue with one of my tunnels. 

Would it make sense to add an api (e.g. cli script with args) that allows to detect the condition that the latest handshake of an endpoint having an endpoint address set, is more than x seconds (hours) old?

That way one could use monit to restart WireGuard.

**Comment by mimugmail** [comment]
If one site has a static IP you can leave the endpoint name empty

**Comment by jkellerer** [comment]
Yes, only one side needs an endpoint address set. The issue only exists when it’s the wrong side or when connecting home networks (dynip with dynip). 

Was thinking an api similar to ‘wg-grep “.+dyn.org” --with-handshake +3600’ might be helpful to trigger Monit. But this is more a nice to have since the same can be achieved by monitoring connectivity through VPN instead.

**Comment by lucas12433** [comment]
Created a cron Job which is rebooting the Wireguard Service after 00:01 where the IP changes always
