### ISSUE TITLE
[os-telegraf] Support Wireguard input plugin

### ISSUE THREAD

**Issue by Sebclem** [opnsense/plugins#2270]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
It will be interesting to add option for the `inputs.wireguard` plugin.
We only need one option that is `devices` (the interface name to monitor).
More info here : https://github.com/influxdata/telegraf/blob/release-1.17/plugins/inputs/wireguard/README.md

**Describe the solution you'd like**
Add this plugin in the telegraf config GUI 

**Describe alternatives you've considered**

**Additional context**

**Comment by mimugmail** [comment]
Did you test it if it works when adding manually? Mostly there are missing permissions like with pf input

**Comment by Sebclem** [comment]
I have tested but it seems there is permission issue: i got this in logs: 
```
E! [inputs.wireguard] Error in plugin: error enumerating Wireguard devices: dial unix /var/run/wireguard/wg0.sock: connect: permission denied
```
In doc there are talking about [this](https://github.com/influxdata/telegraf/blob/release-1.17/plugins/inputs/wireguard/README.md#error-operation-not-permitted), but i don't think it's suitable here.
It's maybee related to permission on  `/var/run/wireguard/wg0.sock`:
```
srwx------  1 root  wheel  0 Mar 12 14:59 /var/run/wireguard/wg0.sock
```

I don't know if it's a good idea to add the `wheel` group to the `telegraf` user...

**Comment by spcqike** [comment]
i also wanted to use wireguard input, because i want to see what peer causes how much traffic (consumes how much bandwith)

as workaround, i wrote a shell script, that i execute every minute per cronjob

`!/bin/sh
#Dump wireguard log, cut first line
VAR=$(wg show wg0 dump | awk '{if(NR>1)print}')

#cut arrays out of log, cut last character from peer ("=" makes problems)
PEER=($(echo "$VAR" | awk '{print substr($1, 1, length($1)-1)}'))
HANDSHAKE=($(echo "$VAR" | awk '{ print $5}'))
RX=($(echo "$VAR" | awk '{ print $6}'))
TX=($(echo "$VAR" | awk '{ print $7}'))

#create raw data string "wg,peer_tag handshake,rx,tx"
for (( i=0; i<${#PEER[@]}; i++ ))
do
STRING+='wg,peer='${PEER[$i]}' handshake='${HANDSHAKE[$i]}',rx='${RX[$i]}',tx='${TX[$i]}$'\n'
done

#publish to influx
curl \
  --request POST "http://<IP>:8086/api/v2/write?org=<ORG>&bucket=<BUCKET>&precision=s" \
  --header "Authorization: Token <TOKEN>" \
  --data-raw "$STRING"`

just leaving this here, maybe someone can need it :)

**Comment by mimugmail** [comment]
https://docs.opnsense.org/troubleshooting/hardening.html

Please try if disabling group separation helps

**Comment by mimugmail** [comment]
@Sebclem Did you try to run telegraf as root? There is now an option in the UI

**Comment by Sebclem** [comment]
Very strange, I have just tried to add the Wireguard input config and I don't have any error but I don't have any Wireguard metrics in my influxDB...
I'm using the `wireguard-kmod` so it's maybe related to this ?

**Comment by hardwareadictos** [comment]
> Author

Same here, added it manually on telegraf.conf, no errors on logs but not metrics reported. Would be nice to know if someone managed this to work

**Comment by cgeolaz** [comment]
Same here. I could not make it work even if I run telegraf as root
