### ISSUE TITLE
security/acme-client: add a -4 "IPV4" only option to the plugin 

### ISSUE THREAD

**Issue by ysguy** [opnsense/plugins#2286]
Issue: When renewing / issuing licenses using Namecheap API and your WAN address is both IPv4 and IPv6, the call via curl to ifconfig.co/ip will retrieve an IPv6 instead of IPv4. 

This is a problem because the Namecheap API requires an IP address be registered but DOES NOT allow IPv6 addresses. Thus the issue/renew will fail every time. 

Editing the file: /usr/local/sbin/acme.sh and changing line1748 from

    _ACME_CURL="curl --silent --dump-header $HTTP_HEADER "

TO
    _ACME_CURL="curl **-4** --silent --dump-header $HTTP_HEADER "

Resolves the issue. 

As i know an upcoming update would overwrite acme.sh, it would be nice to have a GUI option to choose this override. with this change i was immediately issued an LE cert for my domains.

**Comment by taxilian** [comment]
I'm running into this problem as well -- my cert was requested no problem in March, but now I can't renew it. Particularly frustrating is that there is a field for "Source IP" which I would expect to be used instead of checking `ifconfig.co` (or anything else) but it seems to be ignored.

This isn't just a feature request -- it's a full on bug because until one of those two issues are fixed it's not possible (as far as I can tell) to use namecheap DNS validation at present and if it's not fixed before my certs expire I'll have to renew them by hand.

**Comment by cstrachan88** [comment]
Also having this problem and I also thing this is a bug, not a feature request. Since there is no way to force ipv4, and the `Source Ip` field is ignored, there is currently no way to use namecheap dns validation if you have an ipv6 address returned by the ifconfig.co/ip.

Either adding a toggle with the code fix ysguy proposed, and/or fixing the `Source IP` field to actually use the supplied ip address should fix this issue. Both options should be added in my mind.

**Comment by rumbcam** [comment]
I am also running into this issue and would love to get it fixed

**Comment by fraenki** [comment]
> Editing the file: /usr/local/sbin/acme.sh and changing line1748 from

You are proposing to update acme.sh, so you need to request this feature on their issue tracker:
https://github.com/acmesh-official/acme.sh/issues

This cannot be fixed in OPNsense, we are just using acme.sh and rely on the features that are available.
