### ISSUE TITLE
security/acme-client: keep Let's Encrypt as default CA

### ISSUE THREAD

**Issue by fraenki** [opnsense/plugins#2361]
On 01.08.2021 all new releases of acme.sh will [use ZeroSSL as default CA](https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL). In preparation for acme.sh v3 we should do the following:

* Add a new setting to allow users to select their preferred CA (either Let's Encrypt or ZeroSSL)
* Set the default CA to Let's Encrypt
* Update the inline documentation to describe how changing the CA will (not) affect existing certs
* **TBD:** probably rename the plugin from "Let's Encrypt" to "ACME Client" to reflect that other CAs beyond Let's Encrypt are supported

**Comment by lazyoldbear** [comment]
Is it possible to allow configuring the CA instead or in addition to selecting? 
I would like to use Buypass (another free ACME) instead of both ZeroSSL and LE. 
Besides, there are commercial ACME services, their support would be very nice to have. 

Right now binding to LE makes a very good plugin useless if one does not want LE specifically...

**Comment by fraenki** [comment]
The upcoming release 3.0 of os-acme-client will add support for the recent changes in acme.sh and also adds support for all ACME CA's that are currently supported by acme.sh.
