### ISSUE TITLE
chrony plugin stopped WebUI

### ISSUE THREAD

**Issue by tho-gru** [opnsense/plugins#2427]
Dear OPNsense team,

This is my first issue I report here. Please let me know if something is wrong.

I already have some discussion at [https://forum.opnsense.org/index.php?topic=23492.msg111698#msg111698](https://forum.opnsense.org/index.php?topic=23492.msg111698#msg111698)

I want to test the chrony plugin.

My current version info is:
OPNsense 21.1.6-amd64
FreeBSD 12.1-RELEASE-p16-HBSD
OpenSSL 1.1.1k 25 Mar 2021

I freshly installed 21.1.5 from OPNsense-21.1-OpenSSL-serial-amd64.img on a APU ([specification](https://pcengines.ch/apu4d2.htm)) an did an update to 21.1.6. The only other plugin installed is os-dyndns (uninstalled it first to get rid of the "misconfigured" message). The dyndns plugin was uninstalled before the final tests are executed which are covered by the logs.

The matter is, that the WebUI simply do not respond to any clicks outside the chrony "pane".

https://user-images.githubusercontent.com/13496906/121790544-c7cac680-cbe0-11eb-993b-2cc242e81dd3.mp4

The above video give you an visual impression:
1. I viewed the dashboard (about 3 seconds)
2. I navigate to the chrony pane in the menu (until 6.166)
3. I change to several pane within the chrony general pane (until 8.916)
4. I clicked on the OPNsense-Logo to switch to the dashboard (round about 10.0)
5. after this the WebUI hang, the activity indication of Firefox seems to show activities, the dashboard will "never" appear.

Hopefully this description explains the issue better.

I installed the chrome browser in a virtual machine running windows 10. I was able to reproduce the issue. Furthermore I was not able to connect to my OPNsense from an other pc.

BUT after a long time (I would guess more than 10 minutes, I did not measure because some shopping took my focus) I can connect to the WebUI again. Based on this discovery I did further tests.

I established three connections to the WebUI of my OPNsense:

1. from chrome browser in my VM
2. from Firefox browser in my VM
3. from Firefox browser on my real PC

I used the following procedure to do some measurements:

1. Navigate to some pane for within each browser
2. in chrome click though the chrony plugin, test if dashboard is reachable
3. if dashboard is answering, continue with step 2
4. take the time until browsers display correct WebUI pane

Please find attached the logs. Here are the timestamps which are relevant for the tests:

- at 19:00 I restarted OPNsense to get a working test environment
- around 20:40 all three browser hung for 30 up to 60 seconds
- at 20:47 all browser hung for about 4.5 up to 5 minutes
- from 20:56 the 3rd connection hung for about 60 seconds, the 2nd connection hung for 90 seconds and the 1st connection hung for 140 seconds
- after  these tests I rebooted OPNsense to get rid of the delays during navigation.

[20210612-audit.log](https://github.com/opnsense/plugins/files/6642973/20210612-audit.log)
[20210612-configd.log](https://github.com/opnsense/plugins/files/6642974/20210612-configd.log)
[20210612-lighttpd.log](https://github.com/opnsense/plugins/files/6642975/20210612-lighttpd.log)
[20210612-system.log](https://github.com/opnsense/plugins/files/6642976/20210612-system.log)

**Comment by mimugmail** [comment]
Does this also happen when you enable the chrony daemon?

**Comment by tho-gru** [comment]
Hi Michael,

I did not apply an changes to the NTP settings. 

I only changed the settings of chrony as displayed in the attached screen shot and pressed SAVE:
![20210615-000919-General _ Chrony _ Services _ router home thogru de](https://user-images.githubusercontent.com/13496906/121966597-33db3500-cd6f-11eb-9be5-8fb27744deb7.png)

The WebUI hang after pressing SAVE. After resetting the OPNsense  the chrony plugin does not display any change on its General pane.

Kind Regards
Thomas

**Comment by xbb** [comment]
It hangs because, while you browse that configuration page, there are some XHRs requesting the status of chronyd, even when not running, every 5 seconds.

https://github.com/opnsense/plugins/blob/f7bc50c/net/chrony/src/opnsense/mvc/app/views/OPNsense/Chrony/general.volt#L98-L101

The API calls are hanging if chronyd is not running because the `chronyc` client has a longer than 5 seconds overall timeout.

https://github.com/opnsense/plugins/blob/e89c921/net/chrony/src/opnsense/mvc/app/controllers/OPNsense/Chrony/Api/ServiceController.php

In the meanwhile more calls are queued via `setInterval`. If you close the page it should unblock itself after a while, depending how many calls are waiting.

If you enable the service before the 5 seconds interval that should prevent the issue, then you can make the required configuration changes.

What I would do:

- call the chronyc commands with timeout, for example `timeout 0.1 /usr/local/bin/chronyc tracking`
  or maybe better `chronyc -m 'timeout 100' 'retries 0' tracking`

  https://github.com/opnsense/plugins/blob/70497698e08900c7d6926402a19b36168a4d3572/net/chrony/src/opnsense/service/conf/actions.d/actions_chrony.conf

  this already should mitigate the problem

	  ```
	  [chronysources]
	  command:/usr/local/bin/chronyc -m 'timeout 100' 'retries 0' sources
	  parameters:
	  type:script_output
	  message:show chrony sources
	  
	  [chronysourcestats]
	  command:/usr/local/bin/chronyc -m 'timeout 100' 'retries 0' sourcestats
	  parameters:
	  type:script_output
	  message:show chrony sourcestats
	  
	  [chronytracking]
	  command:/usr/local/bin/chronyc -m 'timeout 100' 'retries 0' tracking
	  parameters:
	  type:script_output
	  message:show chrony tracking
	  
	  [chronyauthdata]
	  command:/usr/local/bin/chronyc -N -m 'timeout 100' 'retries 0' authdata
	  parameters:
	  type:script_output
	  message:show chrony authdata
	  ```

- find a way to not query the various statistics if the daemon is not running

**Comment by mimugmail** [comment]
Thx for digging into this, totally forgot about this one.
