### ISSUE TITLE
sysutils/node_exporter: Expose tls_server_config/basic_auth_users settings 

### ISSUE THREAD

**Issue by BlueSpaceCanary** [opnsense/plugins#2497]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[✅] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[✅] I have searched the existing issues and I'm convinced that mine is new.

[✅] When the request is meant for an existing plugin, I've added its name to the title.

**Describe the solution you'd like**
The version of node_exporter in the opnsense node_exporter plugin supports TLS and basic auth (added [here](https://github.com/prometheus/node_exporter/pull/1683)). It would be nice to expose this in the plugin settings page rather than having to manually configure it via `/etc/rc.conf` (which would override the generated `node_exporter_args`, I think?)

**Describe alternatives you've considered**
nginx can be set up as a reverse proxy in front of node_exporter, though I haven't actually tried yet so I have no idea how well-supported that is by the nginx plugin

**Comment by jkellerer** [comment]
I've considered this, but didn't provide it PR since it would require running `node_exporter` as a user and not "`nobody`" as it currently runs. This is necessary to provide the cert and key to node_exporter. As long as it runs as `nobody`, it has minimal rights and cannot read private keys. 

As a workaround you can however always run node_exporter on localhost and put nginx or haproxy in front to get https and authentication.
