### ISSUE TITLE
[os-nut] make available the setting FINALDELAY in upsmon.conf

### ISSUE THREAD

**Issue by gorechild** [opnsense/plugins#2724]
In my opinion this is a important setting to let opnsense wait until all slaves are shut down, 
before starting own shutdown process. 
This allows connected slaves to save data over network before shutting down.

**Comment by mimugmail** [comment]
On heady-duty UPS most of the time the 10% battery warning isn't even enough to let the systems power down, don't you think this is your issue?

**Comment by gorechild** [comment]
Hi,

in my case opnsense is shutting down too fast after battery limit is reached.
network devices are connected on different network segments on different ports of opensense and when opensense
goes down immediately, these network segments cannot communicate with each other anymore and servers can not
write required data to other servers on different segments. these servers take forever to run into timeouts and orderly shutdown.
i tested it putting the option into the file manually with delay of 300 and tested again: this time all
servers where able to write their data within 1 minute and orderly shut down whitout any problems.
after that opensense hardware shut down and everything was in perfekt order. so there might be quite a
few scenarios, where this option is a great help so delay shutdown of master and have slaves shutdown first.

**Comment by Starkstromkonsument** [comment]
Your setup sounds kind of complex. Have you had a look at [upssched](https://networkupstools.org/docs/man/upssched.html) and [upssched.conf](https://networkupstools.org/docs/man/upssched.conf.html) to trigger timebased cascaded shutdowns on the clients side before LB / FSD is reached?

e.g.

1. Trigger shutdown of "normal" servers after 60s on battery
2. Trigger shutdown of database / storage servers and/or NAS after 240s on battery
3. Trigger shutdown of master / UPS at LB / FSD (the plugin for OPNsense does not support upssched so far)

**Caveat: If the Power comes back before your master shuts down the UPS, the servers won't come back up automatically!** This could be fixed by adding upssched support to the plugin though.
