### ISSUE TITLE
several plugins - Upgrade to 22.1 breaks "Log File" view in WebUI

### ISSUE THREAD

**Issue by Starkstromkonsument** [opnsense/plugins#2786]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
Upgrading to OPNsense 22.1 breaks the Log File views in the WebUI of several plugins. The WebUI only displays "No results found!". 

List of affected plugins (might not be complete, as I don't use all available plugins):

- C-ICAP
- ClamAV
- QEMU Guest Agent
- Zabbix Agent
- Zabbix Proxy
- Web Proxy

**To Reproduce**
1. Upgrade OPNsense to version 22.1
2. Go to Services --> [Plugin XYZ] --> Log File
3. Set severity filter to Debug
4. See error: No results found!

**Expected behavior**
Display the contents of the corresponding log file.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/53019449/151677215-1734417b-e419-4d97-9413-d4a674f9f82f.png)

**Relevant log files**
See above.

**Environment**
OPNsense 22.1-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1m 14 Dec 2021
Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 cores, 4 threads)

**Comment by jkellerer** [comment]
This is caused by the severities filter in combination with a generic log file format that is not directly supported in the built-in log viewer (part of core and reused by many plugins). As a temporary workaround one can unselect all severities (enable "Multiselect" in drop down and unselect all).

See also: https://github.com/opnsense/plugins/issues/2776#issuecomment-1025000937
