### ISSUE TITLE
net/haproxy: default server timeout is pretty aggressive with 30s

### ISSUE THREAD

**Issue by EugenMayer** [opnsense/plugins#279]
I was fighting an intransparent issue with opnsense for a while, on some boxes i could not get the "check for updates" button to work - it had a gateway timeout. All my opnsense frontends are behind the HAproxy plugin

I was never able to find the cause, until i debugged a different application behind the haproxy of opnsense, which i knew very well. I could see that the server reacted on a client-disconnect, not really causing the timeout itself. So i went for HAproxy issues and found it, it was server timeout.

Applying the same to the opnsense problem, i was able to get the "check for updates" button to work again https://goo.gl/CwDCp4

We should probably adjust the default to something else then 30s , maybe 60s .. and if not, we should make this issue way more transparent. See the other issue

**Comment by fraenki** [comment]
> We should probably adjust the default to something else then 30s , maybe 60s .. 

Well, I do understand that it is annoying to waste so much time on such a simple issue.
On the other side, this is curse with all _default_ values: They won't work for every use-case.

I'm not keen on changing the default value just because it wasn't a good value for this specific use-case. After all, waiting 30 seconds for a server to respond isn't _that_ wrong. :)

**Comment by fraenki** [comment]
I'm closing this now. Since the default value is not _wrong_, there's no urgent need to change it.
Feel free to comment or reopen this issue.
