### ISSUE TITLE
Dynamic DNS/ddclient Add Support for Azure DNS

### ISSUE THREAD

**Issue by bumasl** [opnsense/plugins#2844]
Would it be possible for support for Azure DNS to be added to the ddclient plugin within OPNsense?

Ccurrently Dynamic DNS
![image](https://user-images.githubusercontent.com/20816899/154571643-7f417a57-08a7-4e9b-b508-8723132c6039.png)

**Comment by t3nk3y** [comment]
I'm also affected by this issue, and have opened a ticket using a template.  Please close this one, and optionally link it to my ticket: #2849

**Comment by emaba** [comment]
I'm asking the same. It's something that we need.
Thank you.

**Comment by hauserkristof** [comment]
Yes, we would need this please!

**Comment by filmar25** [comment]
Yes me too.

Required for me.

Thank you !

**Comment by jortfal** [comment]
Hi guys,

as this issue is incomplete I have created a new one to see if you will listen to us and add this functionality to the new Dynamic DNS plugin..

I leave the link to the new issue  [#5901](https://github.com/opnsense/core/issues/5901) in case you want to leave your support

Thanks.

Regards.

**Comment by emaba** [comment]
What's the plan to reintroduce Azure? We need it, and it's very important for a lot of people.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/plugins/issues/3037#issuecomment-1183645274
