### ISSUE TITLE
os-ddclient - Gateway group as monitored interface in Multi WAN configurations

### ISSUE THREAD

**Issue by buzzkillingtonne** [opnsense/plugins#2899]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
os-ddclient is not currently allowing selection of a gateway group when using muti WAN, only one individual WAN interface can be selected. The os-dyndns plugin is capable of this, and it allows it to check the IP of the currently active interface in the gateway group.

**Describe the solution you'd like**
I would like the ability to select a gateway group as the monitored interface so that when the WAN fails over the DNS gets updates with the new IP address.

**Describe alternatives you've considered**
Using os-dyndns, but that package will be removed in 22.7 as it is currently deprecated.

**Additional context**

**Comment by AdSchellevis** [comment]
Apparently you could still select a group, it just doesn't really do anything other then choosing the default gateway (see https://github.com/opnsense/plugins/commit/0454288b11fdee919546941ac3259d082b5d6782), which is the default behaviour.

**Comment by buzzkillingtonne** [comment]
I just tested and selected my primary WAN interface to monitor, since I cannot select the group. This results in it not seeing an IP when I test my WAN failover causing DNS to not get updated with the IP of the secondary WAN interface. I also tried none as the interface to monitor out of curiosity and as expected got the same result.
`WARNING: unable to determine IP address`

If I select my secondary WAN interface to monitor, it at least tries to change the IP, but I'm having other issues with it that are causing it to fail.
`WARNING: file /var/tmp/ddclient.cache, line 4: Invalid Value for keyword 'ip' = ''`

**Comment by hauserkristof** [comment]
Dear @AdSchellevis !

I have also tested this on:
| Key | Value |
| -- | -- |
| Type | opnsense-business |  
| Version | 22.4.2 |  
| Architecture | amd64 |  
| Flavour | OpenSSL |  
| Commit | f350d31bc |

With os-ddclient version: 1.7_2

I also cannot select a GW Group:

<img width="929" alt="Képernyőfotó 2022-07-19 - 10 07 47" src="https://user-images.githubusercontent.com/1770194/179700485-4e0ac741-e774-43f5-9bf7-40627877b7a0.png">


<img width="974" alt="Képernyőfotó 2022-07-19 - 10 08 50" src="https://user-images.githubusercontent.com/1770194/179700537-ad3a8ea2-6718-4b2e-91c8-c53de3b74d14.png">

This is also a step backwards from the legacy ddclient plugin 😞

**Comment by NigelWhatling** [comment]
I'm confused. Are you saying that the legacy functionality didn't work? (certainly did for me) Or is it that the new (using ddclient not dyndns??) doesn't work?

**Comment by hauserkristof** [comment]
Hi @NigelWhatling:
With the new one (ddclient) I cannot set GW groups

Thanks @AdSchellevis , I understand that you do not maintain the old dyndns option anymore, and the reasons are clear too.

I just would like to have nearly the same functionality in the new ddclient, because at my site it is really useful. I'm not trying to poke anyone, just to get information and features.

Thank you for the recommendation, if I will have the proper time, I may open a PR to discuss this.

Best regards,

Kristóf

**Comment by NigelWhatling** [comment]
@hauserkristof, that pretty much sums up my experience, too.

It had only just clicked with me last night that it wasn't a case of re-writing an existing plugin but more wrapping a new base project. I'm assuming that it's the underlying ddclient project that does not support GW groups and not just that the plugin doesn't allow selection. That's a shame because I, like you, have found that legacy functionality incredibly useful.

Would love to help out with this somehow. But I'm not sure I understand enough about how the networking/configuration works to know what to ask for. Certainly wouldn't have a hope of assisting development-wise with a Perl project. 🙁

**Comment by buzzkillingtonne** [comment]
I found that I get a least some of the functionality by using freedns as the method and checking force SSL and monitoring none for interface. Unfortunately this means I must rely on a third party for the DNS check but it works at least.

I use CloudFlare as my provider.

**Comment by putnam** [comment]
I use this and am surprised it is not part of the new client. I'm using the old one for now but the warning about its deprecation is spooking me. It's very useful to be able to point a ddns client to a gateway group. If you are in a multi-wan setup you generally will want the currently-functioning IP to be represented by your hostname. Seems not too difficult to add support for this considering it's in the old plugin.

**Comment by Podden** [comment]
Is there any chance someone will implement this? Just updated our Firewall and now I'm forced into the new dyndns plugin.  Now incoming connections do not work when our WAN fails over to the other connection. :(

**Comment by joshs85** [comment]
+1
