### ISSUE TITLE
os-ddclient - Feature request: select IPv4 or IPv6 for Google DDNS

### ISSUE THREAD

**Issue by archer007** [opnsense/plugins#2943]
As described in [Google's DDNS documentation](https://support.google.com/domains/answer/6147083), Google Domains supports either IPv4 or IPv6 for DDNS records, but not both at once. Therefore os-ddclient needs an option to select the IPv4 or IPv6 address of an interface to send for DDNS updates when using Google Domains DDNS.

Currently, os-ddclient appears to only support IPv6 when an interface has an IPv4 and IPv6 address

**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
As described in [Google's DDNS documentation](https://support.google.com/domains/answer/6147083), Google Domains supports either IPv4 or IPv6 for DDNS records, but not both at once. 

**Describe the solution you'd like**
os-ddclient needs an option to select the IPv4 or IPv6 address of an interface to send for DDNS updates when using Google Domains DDNS.

**Describe alternatives you've considered**
There appear to be no alternatives other than changing DDNS provider which is impractical and may simply shift the problem to another provider's DDNS settings

**Additional context**

**Comment by meyergru** [comment]
Did you notice https://github.com/opnsense/plugins/pull/2897 ? Since os-ddclient 1.5, you can choose whether to use IPv6 for updates. If the DDNS service is able to have a fixed suffix (which it should for the EUI64 interface part plus the IPv6 Prefix ID for the tracking interface), the /56 prefix can be set from the outgoing IPv6 if the update is done via IPv6.

**Comment by archer007** [comment]
Thanks for the reply @meyergru. I think there might be a misunderstanding. I want the functionality of choosing to send only the IPv4 external address assigned to an interface. That checkbox appears to only control whether the update itself can _take place_ over IPv6, not give you the option to send only the assigned IPv4 address of the interface in an update.

I have dual stack connectivity through Comcast and request a /60 IPv6 block, a /128 IPv6 IP, and an IPv4 address. I've noticed that the DDNS client will only send my assigned IPv6 address to DDNS. I hope that makes sense, and if it doesn't please let me know so I can clarify it. Thank you!

**Comment by meyergru** [comment]
I also use DS and noticed that I do not have control over which address type was sent (I actually do not remember which it was), so I chose to use the custom update and just take the IP of the sender address. By choosing to employ IPv4 or IPv6 for the connection, I can have whatever I want.

However, that is a quick fix which is only possible because I have my own DDNS service. It would be good to be able to choose between the IPv4 or IPv6 address like you requested.
