### ISSUE TITLE
dns/ddclient: add regfish

### ISSUE THREAD

**Issue by gertfriend** [opnsense/plugins#2975]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Please add regfish IPv4 and IPv6 to ddclient

**Describe the solution you'd like**
Please add regfish: https://www.regfish.de/domains/dyndns/dokumentation

**Describe alternatives you've considered**

**Additional context**

**Comment by gertfriend** [comment]
Time ago you set a status on entries. The status never changed so i was thinking the entries will be ignored.
I have only basic programming level so i didn't know where to take a look and having difficulties to analyze the code.

**Comment by high-voltages-git** [comment]
Hi @ all,

what is the plan or the suggestion how to handle dns providers like regfish?
I am using regfish to and I don't want to change something at this point.
with to old implementation it was possible to use urls to do these kind of customisation. This I have used for ipv6 and because the menu entry regfish ipv6 does not works for me.

If there where someone how can tell me were these missing part have to be added, I can imagine to support in coding or do research for the implementation.

**Comment by high-voltages-git** [comment]
If I get it right, it have to be implemented in ddclient source and its configuration file?

**Comment by gertfriend** [comment]
Implemented and testet by me in ddclient on github. Waiting the code to be merged in the main code and for public next main release.
