### ISSUE TITLE
os-nginx: no proxy_redirect parameter setting via GUI

### ISSUE THREAD

**Issue by linwalth** [opnsense/plugins#3007]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I cannot set `proxy_redirect off` via GUI - using hooks for custom configuration is out of the picture for me, as I configure a lot via GUI and I would overwrite the custom parameter every time i refresh. The reason I need to turn it off is because if the HTTP server presented port is the same as the upstream server presented port - thus NginX cuts out the port from the URI towards the upstream server. I need the upstream to be spoken to with the port in the URI, though.

**Describe the solution you'd like**
I'd like thus to be able to turn off proxy_redirect via GUI.

**Describe alternatives you've considered**
Another probable solution would be to make it possible to set custom parameters via proxy_set_header like `proxy_set_header Host $host:$server_port;`

**Additional context**
None so far.

**Comment by kulikov-a** [comment]
Hi!
Are you sure that `proxy_redirect` is the right solution for this? Could you please describe in more detail the problem of port number cutting with an example?
(afaik `proxy_redirect off` only stops `proxy_redirect` action from uplevel settings. and proxy_redirect is not set on http or server level?)

> I configure a lot via GUI and I would overwrite the custom parameter every time i refresh

If I understand correctly, this shouldn't be a problem, since the directives added via the hooks don't disappear after GUI changes.
