### ISSUE TITLE
Nginx server names are not sanitized

### ISSUE THREAD

**Issue by mreiche** [opnsense/plugins#3024]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
When pasting a server name like `www.example.com   ` (with trailing spaces), the UI replaces it with a trimmed chip label.
![Bildschirmfoto 2022-06-30 um 11 07 30](https://user-images.githubusercontent.com/572453/176638753-3a62e4bf-fcad-41e1-b260-a36918147613.jpg)

But it actually breaks the configuration in nginx.conf:

```
invalid number of arguments in "ssl_certificate_key" directive in /usr/local/etc/nginx/nginx.conf:1790
```
```
ssl_certificate_key /usr/local/etc/nginx/key/www.example.com     .key;
```

```
unknown log format ".access.log" in /usr/local/etc/nginx/nginx.conf:1795
```
```
access_log  /var/log/nginx/www.example.com    .access.log main;
```

**To Reproduce**
1. Go to Services -> Nginx -> Configuration -> HTTP -> HTTP-Servers
2. Create a new server
3. Paste an "invalid" server name
4. No errors in the UI
5. Errors in Nginx global errors view

**Expected behavior**
I expect that the server name is sanitized correctly.

Please keep in mind, that that Nginx supports also:
* Regular expressions in server names like `~^(www\.)?example\.com$`
* That behaviour above also happens when you add multiple hostnames (around 10)

**Environment**
OpnSense 22.1.9
os-nginx 1.28
nginx 1.20.2_9,2

**Comment by kulikov-a** [comment]
definitely sounds like a potential problem. @fabianfrz , maybe it makes sense to just use the server uuid for logs names (i can try to make a pr after 1.32)?

**Comment by fabianfrz** [comment]
@kulikov-a I did choose to use the first hostname to have it reasonably searchable for humans in the file system. If there are spaces in the config, I guess the config is in an illegal state since they should be filtered out in first place. What do you think?

BTW: I guess it would just work if we would quote the strings in the config - but the problem is that there are actually spaces in the config..

**Comment by kulikov-a** [comment]
@fabianfrz , Hi! Thanks for response
Now the `servername` field is not validated
https://github.com/opnsense/plugins/blob/cc42b5287871edb4dabd8384841ef3ad44705d4f/www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml#L658-L660
and the template generates a log file name from the entire field set.
https://github.com/opnsense/plugins/blob/cc42b5287871edb4dabd8384841ef3ad44705d4f/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf#L168
(`single_servername` is used for certs naming only?)
so IIUC this can lead to an 'invalid number of arguments' error due to a spaces (or some other error if we quote the string), an '63: File name too long' error (if there are many names), and an 'invalid variable name' error (if a regex is used).

At first glance, the solution seems to me:
- change log-files naming to uuid by default,
- add model migration to preserve existing settings on working configs,
 -add a log filename prefix field to the gui (if users like me like to look at the logs in the file system ;) ),
- add the uuid field to the grid (for the convenience of a possible server - log naming search),
 -add an additional NgxServerNameConstraint constraint to validate server name values.
What do you think?

**Comment by fabianfrz** [comment]
for the last point - if it is only to validate a list of servernames -> put it to core. Then other plugins could use it as well and likely will at some point. For the prefix - I have no idea what the prefix should be. `<http|stream|mail|…>.<uuid>.access.log` would be likely the most stable one however it would be hard to identify it quickly.
