### ISSUE TITLE
HaProxy { upgrade-to-stable 2.6 } 

### ISSUE THREAD

**Issue by xkpx64** [opnsense/plugins#3025]
HTTP/3 support added -> https://github.com/haproxy/haproxy/issues/680#issuecomment-1169779455 <3

**Comment by fraenki** [comment]
Thanks for the heads-up. The 2.6 release series of HAProxy is still very new, so it's unlikely to be included in OPNsense during 2022. I follow the HAProxy development closely in order to find the right time for this upgrade.

I've added a new issue to allow everyone to track the progress on this matter:
https://github.com/opnsense/plugins/issues/3026

Don't be disappointed by the ETA, I usually try to focus on stability to reduce the risk of breakage for our users.
