### ISSUE TITLE
net/postfix: SMTP relay / Antispam, Antivirus gateway as a plugin

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#304]
Hi,

this issue is to discuss features and software in general to use for a new plugin to make smtp routing and AS/AV available to OPNsense.

ATM my candidates are:

- Postfix: Well documented, probably biggest user base on the net
- rspamd: Relatively young project but very active. It doesn't rely on Spamassassin but you can use your old rules. Has an own WebUI to see whats going on and it's amazingly fast.

Alternatives:

- OpenSMTPd: Already onboard, very easy, not that big user base
- Amavisd-new/Spamassassin: State of the art for fighting spam in opensource world. Last update of SA in  2014, amavis still active

Any other ideas or opinions are very welcomed :)

**Comment by fbrendel** [comment]
We have Postfix running since 15 years without issues. I love it :smiley: 

Currently I evaluate rspamd too because the construct with spam filter, gray listing, virus scanner and associated milters is quite complicated.
On the other hand rspamd combines it in a single service.
This is important for admins and plugin developers :wink:
I have no idea how stable it is. But as you sad it is currently maintained. Important too.

**Comment by mimugmail** [comment]
https://listi.jpberlin.de/pipermail/postfixbuch-users/2017-September/065340.html

Read this, they are vey experienced, I think this is production ready :)

**Comment by fichtner** [comment]
I'll add rspamd now. We will not have many issues with it, the author is a FreeBSD committer. It also supports Hyperscan on amd64 like Suricata for fast pattern scans.

**Comment by fbrendel** [comment]
@mimugmail thank you for the link. Good thread!
That's exactly why I am looking for alternatives and rspamd seems to bee one.

**Comment by fabianfrz** [comment]
This is in progress and split up into
* #342
* #345
* #332
ant therefore I am closing this ticket. See the corresponding pull requests / tickets for the current progress.
