### ISSUE TITLE
Vnstat: Statistics tabs not showing

### ISSUE THREAD

**Issue by MichaelTrip** [opnsense/plugins#3174]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x ] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ x ] The title contains the plugin to which this issue belongs

**Describe the bug**

When i try to open the Services menu --> VNStat --> Hourly statistics, or daily or monthly or Yearly Statistics, the screen remains empty.

**To Reproduce**
1. Go to 'services'
2. Click on 'VnSat'
3. click on  'any of the statistics'
4. Empty

**Expected behavior**
Seeing statistics of vnstat. It is working on the cli though.

**Screenshots**

![2022-10-25T15:28:53,258008749+02:00](https://user-images.githubusercontent.com/1826203/197786257-7355f29e-b949-4d22-a3bf-e10143b9e567.png)
![2022-10-25T15:28:58,736087541+02:00](https://user-images.githubusercontent.com/1826203/197786931-c8412800-4b86-45b6-9e9a-9289614308c3.png)

**Environment**

OPNsense 22.7.6-amd64
FreeBSD 13.1-RELEASE-p2
OpenSSL 1.1.1q  5 Jul 2022

**Comment by patschi** [comment]
Do you have more than 4 interfaces selected in the vnstat settings? I know there's some known restriction/bug that when you select too much interfaces, it stops working. Apparently some *nix-kernel restriction, if I recall.

> Seeing statistics of vnstat. It is working on the cli though.

What is the exact command you're running on the CLI?

**Comment by MichaelTrip** [comment]
> Do you have more than 4 interfaces selected in the vnstat settings? I know there's some known restriction/bug that when you select too much interfaces, it stops working. Apparently some *nix-kernel restriction, if I recall.
I have selected al of my 10 interface. I have now selected only 4 of them. Still no change.
> > Seeing statistics of vnstat. It is working on the cli though.
> 
> What is the exact command you're running on the CLI?

just running `vnstat`

```
root@OPNsense:~ # vnstat

                      rx      /      tx      /     total    /   estimated
 enc0:
       Oct '22           0 B  /         0 B  /         0 B  /     --     
     yesterday           0 B  /         0 B  /         0 B
         today           0 B  /         0 B  /         0 B  /     --     

 igb0:
       Oct '22      1.17 TiB  /    1.25 TiB  /    2.42 TiB  /    3.03 TiB
     yesterday    118.78 GiB  /   99.10 GiB  /  217.89 GiB
         today    121.04 GiB  /  122.21 GiB  /  243.25 GiB  /  288.29 GiB

 igb0_vlan1100:
       Oct '22           0 B  /         0 B  /         0 B  /     --     
     yesterday           0 B  /         0 B  /         0 B
         today           0 B  /         0 B  /         0 B  /     --     

 etc..

```

**Comment by DjSni** [comment]
here too have the same issue

**Comment by QuarkZ26** [comment]
Please reopen this, it's still hasn't been fixed. Or provide an alternative.

**Comment by mimugmail** [comment]
Its a problem of vnstat itself

**Comment by mpfusion** [comment]
I'm having the same problem and can reproduce it with `OPNsense 24.1.1-amd64` and `vnStat 2.11`. I've selected a single interface and the tabs are empty. The `vnstat` command does produce output, so that's working.

I'm surprised to see this bug closed if it's still an unsolved issue.

**Comment by QuarkZ26** [comment]
It's actually working now for me, though I don't really know why since I hadn't used it since it was broken. I reinstalled Opnsense from scratch at some point and it's likely the reason. 

A few days ago, I decided to try again, installed the plugin, deselected/reselected WAN in the options, and it's working. If it's not working for you, then I'm guessing there's some remnant files that needed cleaned up on the system itself.

**Comment by mpfusion** [comment]
I reset the config and now the stats appear, indeed. This sadly deleted the history, though. But at least the stats show up now.

**Comment by vergoh** [comment]
> Do you have more than 4 interfaces selected in the vnstat settings? I know there's some known restriction/bug that when you select too much interfaces, it stops working. Apparently some *nix-kernel restriction, if I recall.

Mainly for future reference, this limitation was caused by the interface name being limited to 31 characters which often resulted in around 4 interfaces being the limit when the `interface1+interface2+...` syntax was used (which is something this plugin does). This limitation no longer exists start from vnStat 2.10.

> Its a problem of vnstat itself

As already pointed out, `vnstat` will still produce results from CLI which suggests the issue is somewhere in the plugin's implementation.

> I reset the config and now the stats appear, indeed.

I've tried to understand how the plugin has been implemented and "Reset" appears to only be removing the database directory and then proceeding the same flow as pressing "Save" would. There aren't any plugin related files being stored in vnStat's database directory so it's rather strange "Reset" would result in the situation something fixing itself, unless it's somehow some file/directory permission issue. In that case, one of the system logs should contain some error message indicating what the issue is.

**Comment by lexxxel** [comment]
> > Do you have more than 4 interfaces selected in the vnstat settings? I know there's some known restriction/bug that when you select too much interfaces, it stops working. Apparently some *nix-kernel restriction, if I recall.
> 
> Mainly for future reference, this limitation was caused by the interface name being limited to 31 characters which often resulted in around 4 interfaces being the limit when the `interface1+interface2+...` syntax was used (which is something this plugin does). This limitation no longer exists start from vnStat 2.10.
> 
I have this issue with one single interface. I added a second WAN and whenever I switch over to that OR any other interface except the original WAN, I see empty tabs. Only if I select the first WAN, I do get the tabs with the correct tables.

**Comment by atl285** [comment]
I know, this is an old issue, but for me it was still current (I'm on 25.7) . Since Months I tried to get the out put of more interfaces. Based on the informations on the comments of this issue I found the reason, that the statistics are not showing up: It works only for interfaces, which are added to the database. This is done on creating the database. I have some interfaces created on the OPNSense long after creation of the database. To get these listed in the overview, they have to be added to the database. This can be done using the following command:

~~~
vnstat -i NEW_INTERFACE --add
~~~

Maybe this can be done from the plugin on every configuration save, because already existing interfaces will be ignored and vnstat gives the error `Error: Interface "NEW_INTERFACE" already exists in the database.`.

**Comment by abirkill** [comment]
I recently changed the WAN interface that was assigned in OPNsense, and this caused the empty tab issue for me.

I'm not sure if adding the new interface as suggested above would have fixed the issue for new data, but I wanted to keep the existing data from the old interface if possible, which requires updating the vnstat database so the historic interface data is assigned to the new interface.  I was able to do this by using the `--merge` option in vnstat (documented briefly [here](https://github.com/vergoh/vnstat/wiki/Usage-%23-Migrating-data)).

The details of how to use it were a little vague, but what seems to have worked for me is to run:

```vnstat --merge /var/lib/vnstat/vnstat.db:<old_interface> /var/lib/vnstat/vnstat.db:<new_interface>```

So in my case I ran:

```vnstat --merge /var/lib/vnstat/vnstat.db:igb0 /var/lib/vnstat/vnstat.db:ixl1```

This will somewhat explain what it's going to do, without actually doing it -- to perform the merge you'll also need to add the `--force` option.

I'd recommend backing up your existing vnstat data before running this (`/var/lib/vnstat/vnstat.db`), and of course, YMMV -- this worked for me, but may not work for you.
