### ISSUE TITLE
NtopNG interface selection

### ISSUE THREAD

**Issue by nicnatros** [opnsense/plugins#3260]
The issue reported in #906 was not resolved by #907 as reported. I would like to resurrect this problem.

In the ntopng plugin only a singular interface can be selected. No multiple selections are allowed. If "none" is selected then all interfaces are passed to ntopng. This presents a problem for anyone using the community edition of ntopng with more than 8 interfaces. As the license only allows 8 the ntopng software picks the first 8 interfaces it sees. There is no way to decide in ntopng which 8 get monitored. It would be much more preferable to instead be able to select multiple interfaces to pass through from the plugin page in Opnsense. This would allow the selection of the 8 interfaces to pass through to ntopng.

**Comment by rsik** [comment]
Same issue here:


- The current plugin version where the bug first appeared
    - `os-ntopng` `1.2_2`
    - `os-redis` `1.1_2`
- Add the name of the plugin to the front of the subject
    - Not OP but it's there
- The last plugin version where the bug did not exist
    - N/A
- The exact URL of the GUI page involved (if any)
    - `/ui/ntopng/general/index`
- A list of steps to replicate the bug
    - Turn on advanced mode -> Pull dropdown of Interfaces -> Can only select one
- The current OPNsense version used
    - `OPNsense 23.1_6-amd64`

I have a lot of VLANs. Due to how OPNsense deals with vlan bridging, I also have a ton of interfaces. If I sit at none, it drops all but first 8 interfaces. This doesn't cover some of the vital interfaces I need to monitor; I could be less than 8 with my bridges, and would love a fix to this to address that issue.

**Comment by iamtherobin** [comment]
Is this ever going to get fixed? Would seem like a trivial bug not to be able to select the device interfaces from the gui.

I tried editing the ntopng.conf to add only the interfaces I need (My LAN and WAN), however at restart it wipes my configuration and goes back to LAN only.

**Comment by burntoc** [comment]
This should be re-opened. It certainly hasn't been fixed, so what's the purpose of letting a bot auto-close it after 180 days?

**Comment by AdSchellevis** [comment]
@burntoc just open a pull request if you’re planning to work on it. Keeping tickets open without ownership is rather useless as explained in our contribution guidelines.

**Comment by burntoc** [comment]
@AdSchellevis Wish I could, but that's a skill I'm going to have to develop so I can't yet really add anything there.  I do understand the wisdom of closing many tickets that stay open an overly long time, but it sure seems like this is a bug/flaw that should be tracked until someone fixes it.  In the interim, I'm trying to edit the ntopng.conf file if I can find the syntax, but it has also been mentioned that doesn't persist upon a reboot.

**Comment by AdSchellevis** [comment]
botty closes these tickets as unplanned, when there’s an owner (someone willing to do the work), they can be reopened. Same rules apply for all tickets, open tickets without priority do consume people’s time during release engineering for no good reason.

**Comment by burntoc** [comment]
So, I should open a ticket with the template so it can be prioritized

**Comment by AdSchellevis** [comment]
To me that sounds pretty useless as this ticket already exists and nobody showed interest in working on it for 180 days. When someone volunteers, we can reopen as stated earlier. No need to add more noise.

**Comment by burntoc** [comment]
It's clear you feel strongly, so fine. Me and my friends never search
closed tickets to start, though, and many of them do code. There are
statuses that can filter the noise just fine. Seems odd such a bug would be
so neglected, but maybe that's just because it wasn't templated. I mean the
only real choice you have now is 1 interface, or none, which sounds like
it's really 5 chosen by ntopng if the other ticket is correct.
