### ISSUE TITLE
[os-postfix] use TLS certificate both for smtpd and smpt connections in postfix plugin

### ISSUE THREAD

**Issue by fred-bloggs** [opnsense/plugins#3274]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
We want to set up the os-postfix plugin with o365 as smart host. Microsoft offers [multipe ways](https://learn.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-for-secure-mail-flow-with-a-partner) to authenticate the OPNsense as a relay server.

1) via fixed IP address
2) via the TLS certificate used from the os-postfix plugin when connecting to the smart host (in this case o365). --> outbound SMTP TLS connection from postfix to o365

As not all of our remote offices have fixed IPs we want to use option 2), the domain name in the TLS certificate to authenticate against the o365 connector.

**Describe the solution you'd like**
To make this work, the following settings in postfix conf need to be set for **outgoing** SMTP TLS connections to the o365 smarthost server:
postconf -e "**smtp**_tls_cert_file = cert_file"
postconf -e "**smtp**_tls_key_file = cert_key"

So I would like to see an option to also set the **smtp** certs, not only the **smtpd** certs. Maybe with a separate checkbox to enable and disable.

Currently the certificate selected in the GUI only applies to **inbound** SMTP TLS connections, the OPNsense plugin authenticates:
postconf -e "smtp**d**_tls_cert_file = cert_file"
postconf -e "smtp**d**_tls_key_file = cert_key"

**Describe alternatives you've considered**
using a docker container with postfix and adding the settings accordingly works, but I would like to use postfix plugin on the firewall instead

**Additional context**
none, on request I can provide a working docker container with the correct settings, but it is as much as adding the  2 lines regarding **smtp** certificate to the postfix config file pointing to the same cert files and key as for the **smtpd** setting.

**Comment by windgmbh** [comment]
It could be an alternative to add the following setting to `/usr/local/etc/postfix/main.cf`
```
smtp_tls_cert_file = $smtpd_tls_cert_file
smtp_tls_key_file = $smtpd_tls_cert_file
```
To my knowledge, this should not break any existing setups, because client certificates are only sent if requested by the server.
An advantage would be that not having to set two certificates is less confusing to the less adept user. 

If we would want to be more careful, the above could be set by a simple (_hidden?_) checkbox '_Send TLS client certificate_':

```jinja
{% if helpers.exists('OPNsense.postfix.general.send_tls_client_certificate') and OPNsense.postfix.general.send_tls_client_certificate == '1' %}
smtp_tls_cert_file = $smtpd_tls_cert_file
smtp_tls_key_file = $smtpd_tls_cert_file
{%endif %}
```

**Comment by fred-bloggs** [comment]
Thank you for your input. I think both options would be ok. I personally prefer the second solution with the hidden checkbox.

**Comment by jassonmc** [comment]
@fred-bloggs 
Sorry for ressurecting this old thread, but the issue at hand is still very valid and no one seems to have a real solution to it.
I added the follow to main.cf and restartet postfix daemon:
smtp_tls_cert_file = $smtpd_tls_cert_file
smtp_tls_key_file = $smtpd_tls_cert_file

even tried adding it like this:
smtp_tls_cert_file = /usr/local/etc/postfix/cert_opn.pem
smtp_tls_key_file = /usr/local/etc/postfix/cert_opn.pem

also with only smtp_tls_cert_file, since the cert_opn.pem contains cert and key:
smtp_tls_cert_file = /usr/local/etc/postfix/cert_opn.pem


Both all no avail and throws the following error in postfix log when trying to send to an MTA which does client cert verification:
warning: TLS library problem: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1621:SSL alert number 46:

Any idea why that doesn'ts work?
