### ISSUE TITLE
os-theme-vicuna : Low color contrast on Unbound DNS reporting pages

### ISSUE THREAD

**Issue by Codelica** [opnsense/plugins#3290]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x ] The title contains the plugin to which this issue belongs

**Describe the bug**
On the newly introduced Unbound Reporting page (https://opnsense/ui/unbound/overview), the colors provided by Vicuna theme prevent reading the values.  Basically this is the same issue as reported already fro Cicada [#3267](https://github.com/opnsense/plugins/issues/3267)

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

- Install and use Vicuna theme
- Go to https://opnsense/ui/unbound/overview
- Try to read the Overview or Details tab
- Contrast is so low you can't read text

**Expected behavior**
High enough contrast

**Screenshots**

![vicuna-unbound-1](https://user-images.githubusercontent.com/386101/215591050-7603d1af-1fdd-4c9f-ba77-007b4b47c944.png)

![vicuna-unbound-2](https://user-images.githubusercontent.com/386101/215591075-5ee9bead-3324-4f61-880a-c5b7d417fa30.png)

**Environment**

OPNsense 23.1_6 (amd64, OpenSSL)
os-theme-vicuna  1.43

**Comment by cvega** [comment]
This is also the case for the cicada theme.

![Screenshot 2023-02-01 182954](https://user-images.githubusercontent.com/376532/216216589-f7d9cdee-30c9-43ca-970f-1ca16a35616b.jpg)

OPNsense 23.1_6 (amd64, OpenSSL)
os-theme-cicada 1.32

**Comment by jkemp814** [comment]
Same here using 23.1
![Screenshot from 2023-02-06 14-52-42](https://user-images.githubusercontent.com/12059343/217096428-128ab684-0179-4fe6-afb5-fbf68e686635.png)

**Comment by markus-gitdev** [comment]
Maybe someone can guide me which is the correct file to edit.
I guess it would be in the file ``build\css\dns-overview.css`` of the vicuna theme, but I'm not sure ...

My suggestion would be to add the ``color`` attribute with value ``#D77610`` to ``.stats-text`` and change the ``color`` attribute from value ``#888`` (to see the color here: ``#888888``) to value ``#8f96a3`` for ``.counter``.

This would then result in the following for the top information of the overview page ...
![grafik](https://user-images.githubusercontent.com/82206269/222079846-4d601db1-411e-4f0b-857c-766f729f7642.png)

... and the following for the tables at the bottom of the overview page ...
![grafik](https://user-images.githubusercontent.com/82206269/222080515-f5f221d1-4336-4432-9156-2abb48a3a94f.png)

Since I don't know, if that could break anything else, it would be great to get feedback where to correctly implement these changes and also if these settings might break other pages ...

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/plugins/pull/3295 ?
