### ISSUE TITLE
os-udpbroadcastrelay: not starting when a WireGuard-Interface is selected

### ISSUE THREAD

**Issue by oli-h** [opnsense/plugins#3303]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] The title contains the plugin to which this issue belongs

**Describe the bug**
Since OpnSense 23.1, UDP Broadcast Relay does not start any more when a WireGuard-interface is part of the relay.
 error in /var/log/system/latest.log:
`<13>1 2023-02-06T22:01:18+01:00 OPNsense.box root 41059 - [meta sequenceId="5"] /usr/local/etc/rc.d/os-udpbroadcastrelay: WARNING: failed to start osudpbroadcastrelay`

**To Reproduce**
1. Go to 'Services: UDP Broadcast Relay'
2. Add one relay, enable it, set port=1900 and Broadcast-Address=239.255.255.250 and select one WireGuard interface, e.g. "wg0"
3. Click "Save"
4. See in the list of Relay the yellow background-color (and not green background-color)
5. Look into `/var/log/system/latest.log`. Check with `ps` that no process `/usr/local/sbin/udpbroadcastrelay` is running
6. remove the "wg0"-interface (keep two other interfaces selected) - press Save again
7. now you see green-background (i.e. process running) and `ps` find a running `/usr/local/sbin/udpbroadcastrelay`

Can also try to start on console. Then you see a more precise error message:
```
root@OPNsense:~ # /usr/local/sbin/udpbroadcastrelay --id 1 --dev igb0 --dev wg0 --dev ath0_wlan1 --port 1900 --multicast 239.255.255.250 -d
ID set to 1
Port set to 1900
ID: 1 (DSCP: 1, ToS: 0x04), Port 1900
igb0: 1 / 192.168.1.1 / 192.168.1.255
ioctl(SIOCGIFBRDADDR): Invalid argument
```

**Expected behavior**
The relay should run also with WireGuard-Interfaces

**Screenshots**
- Not running when WG0 is part of the party
![image](https://user-images.githubusercontent.com/20283081/217947088-b70d24ba-9f04-41ee-93c5-4e2e9dbd52ac.png)

- Running when it's not
![image](https://user-images.githubusercontent.com/20283081/217947274-812a9876-f5b2-48b0-b03a-1dd9d78db5db.png)

**Relevant log files**
```
<13>1 2023-02-06T22:01:18+01:00 OPNsense.box root 41059 - [meta sequenceId="5"] /usr/local/etc/rc.d/os-udpbroadcastrelay: WARNING: failed to start osudpbroadcastrelay
```

See also https://forum.opnsense.org/index.php?topic=32356.0

**Additional context**
No problem with OpnSense 22.7

**Environment**
OPNsense 23.1_6-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1s 1 Nov 2022

running on AMD GX-412TC SOC (4 cores, 4 threads)

Using `os-wireguard` (and not `os-wireguard-go`)

**Comment by securechicken** [comment]
Confirming this, starting with OPNsense 23 (udpbroadcastrelay version 1.0_2): udpbroadcastrelay service(s) do not start when any Wireguard interface is selected.
Service(s) correctly started with OPNsense < 23.
Removing any Wireguard interface from udpbroadcastrelay config line(s) enable the service(s) to start.

I'm thinking this might be due to wireguard transitioning from userland Go software to kernel implementation between OPNsense 22 and 23: maybe wireguard kernel does not correctly set wireguard interfaces broadcast capability flag, or some of that sort.

From error message when running service with command line:
```
ioctl(SIOCGIFBRDADDR): Invalid argument
```
Looks like issue is either happening at main.c line [2049](https://github.com/marjohn56/udpbroadcastrelay/blob/07d747947047f4c01a3b7dd26bb15beafffeadff/main.c#L2049) or [2059](https://github.com/marjohn56/udpbroadcastrelay/blob/07d747947047f4c01a3b7dd26bb15beafffeadff/main.c#L2059).

**Comment by fichtner** [comment]
Yes, os-wiregard-go required probably. Easy to test?

**Comment by securechicken** [comment]
> Yes, os-wiregard-go required probably. Easy to test?

Setup and upgraded an OPNSense VM (23.1.1_2) with a Wireguard [server](https://docs.opnsense.org/manual/how-tos/wireguard-client.html#step-2-configure-the-local-peer-server) + WAN/LAN ifs, using `os-wireguard-go` (1.13_5). Added `os-udpbroadcastrelay` (1.0_2), and a "MDNS" repeater [config/service for it](https://github.com/marjohn56/udpbroadcastrelay#mdns--multicast-dns-chromecast-discovery--bonjour--more) in between the LAN and Wireguard server interfaces.

NO issue with this setup, udpbroadcastrelay service starts correctly, is displayed green in Web UI and is running as can be controlled with processes list on CLI shell.

As can further be confirmed, Wireguard intefaces as created from `os-wireguard-go` differ from those created using kernel driver (`os-wireguard`) by +`BROADCAST` and -`NOARP` flags, as well as a group (`tun` instead of `wg`):
With Go Wireguard module:
```
ifconfig wg2
wg2: flags=8043<UP,BRODCAST,RUNNING,MULTICAST> metric 0 mtu 1420
...
	groups: tun wireguard
...
	Opened by PID [REDACTED]
```
With kernel Wireguard module:
```
ifconfig wg2
wg2: flags=80c1<UP,RUNNING,NOARP,MULTICAST> metric 0 mtu 1420
...
	groups: wg wireguard
...
```

So either raw sockets on interfaces created with kernel Wireguard module wrongly report `BROADCAST` capabilities (then udpbroadcastrelay calls `ioctl(,SIOCGIFBRDADDR,)` on and fails), or there is a bug at udpbroadcastrelay fallback code for interfaces that do not support broadcast (`ioctl(,SIOCGIFDSTADDR,)`, which wrongly reports a perror from ` SIOCGIFBRDADDR` in case of failure).

**Comment by pdarcos** [comment]
I also have this problem with one major difference.
In my case I don't have any wg interfaces added to the relay although I do have a wg0 interface active on the box.

Still I get the same error message: "root 51746 - [meta sequenceId="1"] /usr/local/etc/rc.d/os-udpbroadcastrelay: WARNING: failed to start osudpbroadcastrelay"

How can I dig deeper to find out the root of the problem?

Thx

**Comment by strichte** [comment]
I have the same issue as reported by @oli-h

**Comment by oli-h** [comment]
My workaround now is to switch back from `os-wireguard` to `os-wireguard-go`

**Comment by fichtner** [comment]
I don’t think this will change anytime soon. Upstream is responsive for the interface behaviour. I’m unsure if the built in kernel module in FreeBSD 13.2 changes this but I doubt it.

**Comment by oli-h** [comment]
Updated to OpnSense 23.7.
Now situation is even worse: udpbroadcastrelay doesn't start with `os-wireguard-go` any more.
Remind: Using `os-wireguard-go` instead of `os-wireguard` was my workaround to keep udpbroadcastrelay running

**Comment by kuya1284** [comment]
Confirming what @oli-h said. I also just upgraded to 23.7 and also receive the **Invalid argument** error:

> ioctl(SIOCGIFBRDADDR): Invalid argument

I've been running `os-wireguard-go` for quite some time  and now I'm unable to include my WireGuard interface.

**Comment by pine-serpent** [comment]
I know this is a bit old but I am experiencing the same issue but not including the wireguard interface in the udpbr plugin. I just have a WG interface running but udpbr doesn't start. was any solution discovered for this issue?

**Comment by radiantwave** [comment]
There is no fix yet. Shouldn't this issue be open?

**Comment by damige** [comment]
Running into this issue today, please reopen.

**Comment by dMopp** [comment]
Same problem.

**Comment by DevFreezing** [comment]
Same here, the issue still exist

**Comment by Ghosty01** [comment]
Same here, the issue still exist

**Comment by Korvenwin** [comment]
I'm having the same issue.

**Comment by timlok** [comment]
Opnsense 25.7.11_9 same problem
