### ISSUE TITLE
mdsn-repeater not stopping when CARP is disabled by the "Temporary Disable CARP" button

### ISSUE THREAD

**Issue by avandeweghe** [opnsense/plugins#3369]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
When "Enable CARP Failover" is set to enabled on the mDNS Repeater plugin the MDNS Repeater service does stop when CARP is disabled. This ends up causing a flood on the network because  two mDNS repeaters are now running on the network. One on the disabled node and one one the node that was promoted master. 

**To Reproduce**
1. On the master node go to Interfaces > Virtual IP's > Status.
2. Click Temporary Disable CARP. 
3. Check status of mdsn-repeater service on the disabled CARP node.

**Expected behavior**
When clicking Disable CARP on the Master Node, It's expected that the mdns-repeater also stops.

OPNsense 23.1.5-amd64

**Comment by TechGeek01** [comment]
I'm having this problem as well. Seems that CARP failover properly starts and stops the mdns-repeater service on the backups when demoting the master, but it doesn't stop it on the master when demoting.

That is, the mdns-repeater service starts on the backup when the master is demoted (and thus, the backup becomes the master), but the original master also keeps it running, and two of them on one network causes a flood of mDNS packets.

Expected behavior should be to properly stop the service when demoting a master, just like how the service is started when promoting a backup.

**Comment by fouram** [comment]
Necro on this as well to state that I'm seeing this same behavior. Main node is 24.1 and backup is 24.7 (brought the network down post-upgrade). Master node won't shut down. Both nodes "CARP Failover" checkboxes are checked.
