### ISSUE TITLE
dns/dyndns: Unsuccessful DNS Made Easy

### ISSUE THREAD

**Issue by roens** [opnsense/plugins#3494]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
I've poked at attempting to configure our new Dynamic DNS replacement (`ddclient`) for some time now, but with impending depreciation of the soon-to-be former `dyndns` plugin, I'm back at it. However, any combination of configuration I've tried always seems to result in a `notice` level log entry like (hostname redacted):

     [meta sequenceId="1"] FAILED: Updating HOSTNAME: Server said: '0':

Perhaps this is even the result of too-sparse documentation and I'm missing something. What surmised, both from [OPNsense docs](https://docs.opnsense.org/manual/dynamic_dns.html) and [DNSME docs](https://support.dnsmadeeasy.com/support/solutions/articles/47001122450-dynamic-dns) is:

- Advanced config mode: enabled
- Description: _whatever meaningful to me_
- Service: DNS Made Easy (digicert)
- resourceID: Dynamic DNS ID (of the target name record)
- Username: My DNSME username
- Password: Dynamic DNS Password (defined on the target name record)
- Hostname(s): The target dynamic DNS hostname
- Check ip method: Interface
- Interface to monitor: WAN (my router has one "WAN" interface, which is called "WAN")
- Check ip timeout: 10
- Force SSL: checked/enabled

I still have the old `dyndns` plugin installed & configured. It is still able to update DNSME with the current WAN IP of my router. I did have to configure it with the **Update URL** option, which has the arguments DNSME requires for Dynamic DNS updates embedded in the URL: credentials, ID, IP.

I've never found success with DNSME and any version of the `ddclient` plugin in OPNsense.

Also, I see that as of today, `ddclient` has been archived, [from a lack of interested parties in maintaining the repo](https://github.com/ddclient/ddclient/issues/528). Are there plans here to continue `ddclient` work in a fork (or similar)?

**To Reproduce**
1. Set up account with DNS Made Easy with Rest API Access
2. Create DNS A record in a zone
  - Dynamic DNS: enable
  - Dynamic DNS Password: define a good password
  - Dynamic DNS ID: take note of it
3. Configure a `ddclient` Account as described in the section above
4. Check `ddclient` logs
  - Note log entries stating `[meta sequenceId="1"] FAILED: Updating YOUR_HOSTNAME: Server said: '0':`

**Expected behavior**
That the A Record at DNS Made Easy gets updated with the current WAN IP.

**Screenshots**
n/a

**Relevant log files**

    2023-06-17T15:44:44-07:00	Notice	ddclient[60253]	66363 - [meta sequenceId="4"] WARNING: Wait at least 5 minutes between update attempts.	
    2023-06-17T15:44:44-07:00	Notice	ddclient[60253]	66363 - [meta sequenceId="3"] WARNING: last updated <never> but last attempt on Sat Jun 17 15:44:01 2023 failed.	
    2023-06-17T15:44:44-07:00	Notice	ddclient[60253]	66363 - [meta sequenceId="2"] WARNING: skipping update of REDACTED from <nothing> to IP_REDACTED.	
    2023-06-17T15:44:01-07:00	Notice	ddclient[37450]	47247 - [meta sequenceId="1"] FAILED: Updating HOSTNAME_REDACTED: Server said: '0':	
    2023-06-17T15:36:48-07:00	Notice	ddclient[29274]	41902 - [meta sequenceId="1"] FAILED: Updating HOSTNAME_REDACTED: Server said: '0':	
    2023-06-17T14:13:46-07:00	Notice	ddclient[27403]	35919 - [meta sequenceId="1"] FAILED: Updating HOSTNAME_REDACTED: Server said: '0':	

**Additional context**
n/a

**Environment**
OPNsense 23.1.11-amd64
FreeBSD 13.1-RELEASE-p8
OpenSSL 1.1.1u 30 May 2023

Supermicro E302-9D
Intel(R) Xeon(R) D-2123IT CPU @ 2.20GHz (4 cores, 8 threads)

**Comment by Ramalama2** [comment]
The old dyndns client here on all 4 of my opnsense instances, worked flawless with ovh.

Now with that new ddclient im having troubles either.

On 3 instances it's working flawless with OVH.
On 1 instance, it sometimes updates the IP on OVH, and sometimes not.

Most of the time it runs into an "max update limit" per day error, as if the ddclient updates OVH, no matter if the IP is already correct or the old one.

As if ddclient doesn't recognizes the interface IP, tho it even shows the old or new ip in the Status Page of ddclient.

It's same configured as all other opnsense instances, so there is no difference.

However, on the one opnsense instance im talking about, i stopped using the ddclient and switched to a docker solution:
https://github.com/qdm12/ddns-updater

It works flawless, i could have made a simple cron script, lol
Which does basically the same, but since i have a whole docker server, who cares.

But it would make me very happy to get ddclient on opnsense working, because that's in my opinion something that really fits well opnsense and belongs there.

Cheers

**Comment by Marvo2011** [comment]
Hello,

I want to note that the **ddclient** is now **unmaintained**. I also use the old legacy dyndns plugin for 2 years ago, because ddclient can't add multi gateway support. For me the old dyndns works great, only the little RegEx Support with i haved added: https://github.com/opnsense/plugins/pull/2766

**Comment by roens** [comment]
I'm curious, @AdSchellevis, why the "community support" label on this issue? This seems more in the buckets of "upstream" or "help wanted". Decision was made to move from `dyndns` to `ddclient`, yet [`ddclient`](https://github.com/ddclient/ddclient) now has no maintainer(s), and seems broken for DNS Made Easy… while the current `dyndns` plugin does work.

**Comment by fichtner** [comment]
Community meaning just add your work on the code here. This is not „my problem but your issue“ territory.

**Comment by roens** [comment]
I see, thanks for the clarification @fichtner  🙂

**Comment by Ramalama2** [comment]
> Community meaning just add your work on the code here. This is not „my problem but your issue“ territory.

Fichtner, would it be possible to simply change the description of the old dyndns client?
What i mean is, for most users the old one worked pretty well and tbh still works pretty well.

The only problem i see is, that people don't want to use it, because of the, soon not supported message.

I don't know, why it's not supported soon, maybe the way of the GUI changing the configuration files will change soon.

However in my opinion, as there is no maintainer and no solution to this in the meantime, wouldn't be a better way, either:
To add to the os-ddns package a message either, that's not gonna be supported.
Or to remove the not gonna be supported message from the old dyndns package?

That would at least either inform people, to watch out soon for an alternative way,
Or install the package that works as best for them?

Im sorry beeing an stupid user not able to code something other as stupid bash scripts 🙈

----------------------

However for everyone else here, we have at the moment 3 options:
1. We have an option to make a simple cronjob, since most dyndns providers allows to update the ip via an url. (Unifi users, have only this option for example)
2. We can use either the os-ddns or os-dyndns package, as the one or another are still usable, just pick the one you like better.
3. Use something external, like: https://github.com/qdm12/ddns-updater , that works for me amazingly well and i even get discord messages with the updated IP. It checks here every 5 minutes for a changed ip and updates only if the IP has changed. But there are a ton of other external solutions either.

I mean this isn't something we can't solve either one way or another.
And as someone of us don't start to Code to support the Opnsense development, there won't be any other way.
We should be instead already very happy that opnsense is already that great and thankful to everyone that provides his free time to keep opnsense working and updating.

Cheers :-)

**Comment by AdSchellevis** [comment]
>  Fichtner, would it be possible to simply change the description of the old dyndns client?
What i mean is, for most users the old one worked pretty well and tbh still works pretty well.

23.7 sounds like a good target to finally remove the plugin from our build (https://github.com/opnsense/plugins/commit/b8f705e7d0eecf763d8473cffff5bd5b7a9b529a), in which case we do not have to update anything anymore (ever) for it. `os-dyndns` has outlived its useful life.

> I don't know, why it's not supported soon, maybe the way of the GUI changing the configuration files will change soon.

Because it's old unmaintainable code.

> However in my opinion, as there is no maintainer and no solution to this in the meantime, wouldn't be a better way, either:
> To add to the os-ddns package a message either, that's not gonna be supported.
> Or to remove the not gonna be supported message from the old dyndns package?

The new plugin `os-ddclient` also supports a different backend, which is supported (within reasonable limits), people just have to open pull-requests in order to add more providers. ( see also https://docs.opnsense.org/manual/dynamic_dns.html#general-settings ). It implements a pluggable framework written in python and should be much easier to support in the long run (https://github.com/opnsense/plugins/tree/master/dns/ddclient/src/opnsense/scripts/ddclient/lib/account).

**Comment by monkeyclass** [comment]
> > Fichtner, would it be possible to simply change the description of the old dyndns client?
> > What i mean is, for most users the old one worked pretty well and tbh still works pretty well.
> 
> 23.7 sounds like a good target to finally remove the plugin from our build ([b8f705e](https://github.com/opnsense/plugins/commit/b8f705e7d0eecf763d8473cffff5bd5b7a9b529a)), in which case we do not have to update anything anymore (ever) for it. `os-dyndns` has outlived its useful life.
> 
> > I don't know, why it's not supported soon, maybe the way of the GUI changing the configuration files will change soon.
> 
> Because it's old unmaintainable code.
> 
> > However in my opinion, as there is no maintainer and no solution to this in the meantime, wouldn't be a better way, either:
> > To add to the os-ddns package a message either, that's not gonna be supported.
> > Or to remove the not gonna be supported message from the old dyndns package?
> 
> The new plugin `os-ddclient` also supports a different backend, which is supported (within reasonable limits), people just have to open pull-requests in order to add more providers. ( see also https://docs.opnsense.org/manual/dynamic_dns.html#general-settings ). It implements a pluggable framework written in python and should be much easier to support in the long run (https://github.com/opnsense/plugins/tree/master/dns/ddclient/src/opnsense/scripts/ddclient/lib/account).

@AdSchellevis I have now tried to add a regular "API call"/"Curl" provider for the new python backend. I'm not entirely sure if this is the correct approach to support new fields and methods. #3507.

**Comment by AdSchellevis** [comment]
@roens it might be better to combine this with the existing "custom" handler, although it would need some additional documentation to explain the placeholders and a custom validation to support "hostnames" being uri's as well for selected cases. I rather prevent adding more fields which act like mutually exclusive pairs.

**Comment by monkeyclass** [comment]
> @roens it might be better to combine this with the existing "custom" handler, although it would need some additional documentation to explain the placeholders and a custom validation to support "hostnames" being uri's as well for selected cases. I rather prevent adding more fields which act like mutually exclusive pairs.

@AdSchellevis, I've opened a new PR #3511. Tries to implement it in `dyndns2.py` for the custom service. Just not sure how to modify the validation logic to allow the added complexity in the server field. Thought it was better than doing it for each hostname that one wanted to update. Added a `POST Request` protocol to differentiate for the user whether it's custom dyndns or in this case custom POST request.

**Comment by AdSchellevis** [comment]
@monkeyclass I've added the "post" option in https://github.com/opnsense/plugins/commit/c3f9859fb287d2da8e2676e02d96a83e70a45a6f, can you check if this works for your usecase? 


Please note that multiple hostnames in the same services are pushed for the other end to process, calling the same endpoint multiple times isn't an option (as accounting is done on the single instance).

**Comment by monkeyclass** [comment]
> @monkeyclass I've added the "post" option in [c3f9859](https://github.com/opnsense/plugins/commit/c3f9859fb287d2da8e2676e02d96a83e70a45a6f), can you check if this works for your usecase?
> 
> Please note that multiple hostnames in the same services are pushed for the other end to process, calling the same endpoint multiple times isn't an option (as accounting is done on the single instance).

@AdSchellevis awesome! if I understand correctly then, it won't be an issue that there are multiple hostnames specified, just that the logic is handled before even hitting the python backend, so it's called once per hostname without the for loop? In that case it seems your implementation indeed solves my use-case.

A bit concerned about `params` in `req_opts` for post though. Probably won't be an issue, but `myip` and `hostname` are redundant/double if a fully custom uri like `https://api.example.com/2/ddns/?domain=example.com&hostname=__HOSTNAME__&myip=__MYIP__` is provided that would end up with 2 x query parameters for `hostname` and `myip`. Of course the complete custom uri enables scenarios where the parameter is *not* `hostname` or `myip`, but might be good to mention in documentation to only add query params if not named `myip` and `hostname` or to not have the params there for the post option.

**Comment by monkeyclass** [comment]
@AdSchellevis nevermind my previous comment, I just reread the commit, apparently I was too tired to see the indent correctly. Your implementation should work wonderfully!

**Comment by monkeyclass** [comment]
@AdSchellevis just had a chance to test it out as part of 23.7.1.

Only works with a single hostname specified in the `hostname(s)` field. Multiple entries lead to a `500: Invalid input` from my DNS provider (Not really a server-side error).

So I'm not sure that each entry in `hostname(s)` is sent seperately as calls, and it insteads try to send the list of hostnames as a string. Can you confirm that behaviour? If that's the case I think a loop needs to be implemented or it needs to be specified that an entry per hostname is needed.

**Comment by AdSchellevis** [comment]
@monkeyclass their not being send as separate items, if your provider does not support comma separated lists of hostnames, you do have to input them manually (per line).  If you would post them as separate items, the result would be inconsistent. 

https://github.com/opnsense/plugins/blob/c9c2a7546042f345b37cb006faddfb4c756c82b1/dns/ddclient/src/opnsense/scripts/ddclient/lib/account/dyndns2.py#L69-L76

https://github.com/opnsense/plugins/blob/c9c2a7546042f345b37cb006faddfb4c756c82b1/dns/ddclient/src/opnsense/scripts/ddclient/lib/account/dyndns2.py#L105

**Comment by monkeyclass** [comment]
Great, happy that’s expected behaviour and just me that misunderstood. Got it working perfectly with individual entries per hostname. Legacy dyndns plug-in deleted 👍

**Comment by fichtner** [comment]
This was resolved. :)
