### ISSUE TITLE
net/upnp: Feature Request: Deny use of upnp to specific devices on the LAN

### ISSUE THREAD

**Issue by OPNComet** [opnsense/plugins#358]
This is just a suggestion that would make life easier for users, especially new users, that might want to enable upnp but ONLY for specific devices on their LAN.  I have been told that there are already difficult ways to do this, but they require a degree of knowledge that some people might not have.  The idea is to be able to create a list of devices (either identified by IP address or MAC address, whichever is easiest) that are allowed to use upnp.  Any other device on the LAN would not even know that upnp exists on the network.

The reason for this is that upnp has been known for many years to be a security vulnerability, and many people don't use it that reason, but certain game consoles may not be able to fully function without upnp, particularly if there is more than one on the network.  So, if upnp could be allowed only for those devices that actually need it, and disallowed for everything else, then there would be no worry that (for example) malware running on a desktop computer could use upnp to open a port for nefarious reasons.

If it's not feasible to make this part of the software, could something at least be added to the documentation showing the correct way to block most devices on the network from using upnp, while allowing the handful of devices that need it to access it?

**Comment by fabianfrz** [comment]
@fichtner assigned to you as it it your plugin.

**Comment by djzort** [comment]
This is already a thing in pfsense CE
![untitled](https://user-images.githubusercontent.com/937277/33985359-74e497cc-e10e-11e7-933e-747d05d61e80.png)

**Comment by bsd-source** [comment]
> If it's not feasible to make this part of the software, could something at least be added to the documentation showing the correct way to block most devices on the network from using upnp, while allowing the handful of devices that need it to access it?

I'm not use why this feature request is still open. Maybe this wasn't available in the OPNsense Universal Plug and Play Settings before the feature request was opened. Selecting the Default Deny checkbox under Universal Plug and Play --> Settings will prevent upnp access to all devices. This line will be added to the miniupnpd.conf file when Default Deny is checked:

deny 0-65535 0.0.0.0/0 0-65535

This is what you want by default. One would then use specified permissions to allow specific subnets or specific indivisual devices access to upnp such as the following entries:

Entry 1:   allow 1024-65535 192.168.0.0/24 1024-65535
Entry 2:   allow 1024-65535 192.168.1.0/24 1024-65535
Entry 3:   allow 1024-65535 192.168.0.0/23 22
Entry 4:   allow 12345 192.168.7.113/32 54321

OPNsense miniupnpd.conf file will look like this:

allow 1024-65535 192.168.0.0/24 1024-65535
allow 1024-65535 192.168.1.0/24 1024-65535
allow 1024-65535 192.168.0.0/23 22
allow 12345 192.168.7.113/32 54321
**deny 0-65535 0.0.0.0/0 0-65535**

This feature request should be closed since the OPNsense Universal Plug and Play settings already has this feature.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
