### ISSUE TITLE
security/acme-client: ACME broken for INWX with Let’s Encrypt

### ISSUE THREAD

**Issue by 53c70r** [opnsense/plugins#3590]
Let’s Encrypt certificates will not update since this patch is missing.

https://github.com/acmesh-official/acme.sh/commit/9143cd1485a4a0220897124fec78eb2ec45f81ec

**Comment by fraenki** [comment]
When this patch is available in an [official release of acme.sh](https://github.com/acmesh-official/acme.sh/releases), it will automatically be included in one of the upcoming OPNsense releases.

**Comment by TheHellSite** [comment]
The new release including the pull-request is available now.
https://github.com/acmesh-official/acme.sh/releases/tag/3.0.7

Any ETA for the OPNsense release containing this?

**Comment by fichtner** [comment]
https://pkg.opnsense.org/FreeBSD:13:amd64/23.7/MINT/23.7.6/latest/All/acme.sh-3.0.7_1.pkg is the one you are looking for

**Comment by fichtner** [comment]
Looks like people are still having issues with the upstream patch in place: https://forum.opnsense.org/index.php?topic=36467.0

**Comment by Contik** [comment]
Thanks for the ping, this forum post was me. I think this boils down to: what is the current canonical way with DNS provider `INWX XMLRPC` to use a shared secret aka RFC6238 one-time password seed in addition to username and password? Is this a missing third optional field in `os-acme-client` settings menu? Is there some variable I can set in OPNsense? Do I manually edit `/var/etc/acme-client/accounts/<id>/account.conf` and set my OTP seed value at `SAVED_INWX_Shared_Secret=''`?

The thought process came up when presumably without any outside interaction DNS-01 renewals against `INWX XMLRPC` stopped working on my OPNsense 21.1 between August 1 (still worked) and 60 days later on September 30 (didn't work anymore due to `INWX API: Mobile TAN not correct.`). I've since upgraded to newest OPNsense 23.7.6, newest `os-acme-client` 3.19 and newest `acme.sh` 3.0.7_1 and have `"Reset ACME Client"` in `"Services: ACME Client: Settings"`.

It is possible that when this last worked I had a manually edited shared secret in my `account.conf` file, I don't remember. But I don't think I was affected by the upstream [patch commit 9143cd1](https://github.com/acmesh-official/acme.sh/commit/9143cd1485a4a0220897124fec78eb2ec45f81ec) mentioned at the top so I'm at a bit of a loss as to why this may have stopped working out of the blue.

What ***is*** the best way to use the shared secret with DNS provider `INWX XMLRPC`?

**Comment by fraenki** [comment]
It seems that multiple different issues are mentioned here.

> didn't work anymore due to INWX API: Mobile TAN not correct

According to the [acme.sh wiki](https://github.com/acmesh-official/acme.sh/wiki/dnsapi#dns_inwx):

> If your account is secured by mobile tan you have also defined the shared secret.
> export INWX_Shared_Secret="<shared secret>"
> You may need to re-enable the mobile tan to gain the shared secret.

Currently the INWX_Shared_Secret option is not supported in os-acme-client. However, it [requires oathtool](https://github.com/acmesh-official/acme.sh/blob/377a37e4c9c23bb6988fe5f8863f21b19d3e3a40/dnsapi/dns_inwx.sh#L8-L10), which is currently not available on OPNsense. I'll try to [add it](https://www.freshports.org/security/oath-toolkit/), but it may take some time.

So in order to use INWX _right now_ with OPNsense my suggestion is to disable 2FA in your INWX account.

**Comment by Contik** [comment]
Understood, thanks!
