### ISSUE TITLE
security/acme-client: Add support for Synology SRM deploy hook

### ISSUE THREAD

**Issue by nothing-fr** [opnsense/plugins#3639]
Hi, 

**Is your feature request related to a problem? Please describe.**
Is it possible to add support for Synology Router (SRM) certificate upload ? (like acme.sh did : https://github.com/divx118/acme.sh/blob/synology_srm/deploy/synology_srm.sh )

**Describe the solution you'd like**
Same as "Upload certificate to Synology DSM" (NAS) but for Synology SRM (Router)

**Describe alternatives you've considered**
None for now, i'm still using the synology auto-generated cert but it's not convenient.

I've also tried the "Upload certificate to Synology DSM" script on OPNSense, but it's not working...

Thanks.

**Comment by fraenki** [comment]
>  Is it possible to add support for Synology Router (SRM) certificate upload ? (like acme.sh did : https://github.com/divx118/acme.sh/blob/synology_srm/deploy/synology_srm.sh )

You are not referring to the official acme.sh repository, but a fork instead. The author of this deploy script has never submitted it to the acme.sh project, hence it cannot be used in OPNsense.

The author of this unofficial deploy script opened an issue, but never submitted a pull-request so that his script can be added to acme.sh:
https://github.com/acmesh-official/acme.sh/issues/3332

Someone needs to step-in and submit a pull-request to the acme.sh project. Once the pull-request is accepted by the acme.sh maintainers and included in an official acme.sh release, we may add support for it to OPNsense. Until then there is nothing we can do.
