### ISSUE TITLE
[os-wireguard] - Cannot save WG instance - keys are not autogenerated and validation requires those to be set

### ISSUE THREAD

**Issue by doktornotor** [opnsense/plugins#3656]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] The title contains the plugin to which this issue belongs

**Describe the bug**
Trying to add a local instance of WG.

- The [docs](https://docs.opnsense.org/manual/how-tos/wireguard-s2s.html) say to generate the key with “Generate new keypair” button which does not exist.
- The help says: "Public key of this instance. You can specify your own one, or a key will be generated after saving."
- I cannot save anything since there is some validation requiring the keys to be set.

**To Reproduce**
1. Install the wireguard-os plugin
2. Enable wireguard.
3. Try to add a local instance.
4. See error on trying to save unless you fill in the keys manually

**Expected behavior**
The keys should be autogenerated on save as documented in the help.

**Screenshots**
![image](https://github.com/opnsense/plugins/assets/1075960/8729b095-f060-43bc-b787-b20b800481fc)

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 23.7.7_3 (amd64).
os-wireguard 2.4_1

**Comment by doktornotor** [comment]
Really, what's up with this package lately? Why does the GUI keep changing back and forth? Cf. the screenshot in https://github.com/opnsense/plugins/issues/3632 and discussion there. 

I have started a [thread in the forums](https://forum.opnsense.org/index.php?topic=36829.0) - and also someone there claims that the GUI I posted here is not what's shipping with 23.7.... 😖

```
# pkg info os-wireguard
os-wireguard-2.4_1
Name           : os-wireguard
Version        : 2.4_1
Installed on   : Sun Nov  5 22:21:10 2023 CET
Origin         : opnsense/os-wireguard
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : net
Licenses       : BSD2CLAUSE
Maintainer     : ad@opnsense.org
WWW            : https://opnsense.org/
Comment        : WireGuard VPN service kernel implementation
Annotations    :
        FreeBSD_version: 1302001
        product_abi    : 23.7
        product_arch   : amd64
        product_email  : ad@opnsense.org
        product_hash   : 13a20dcd3
        product_id     : os-wireguard
        product_name   : wireguard
        product_tier   : 3
        product_version: 2.4_1
        product_website: https://opnsense.org/
        repo_type      : binary
        repository     : OPNsense
Flat size      : 79.6KiB
```

```
# pkg list os-wireguard
/usr/local/etc/inc/plugins.inc.d/wireguard.inc
/usr/local/etc/rc.syshook.d/carp/20-wireguard
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ClientController.php
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/GeneralController.php
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ServerController.php
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ServiceController.php
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/DiagnosticsController.php
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/GeneralController.php
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardClient.xml
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardServer.xml
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/general.xml
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/ACL/ACL.xml
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/Client.php
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/Client.xml
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/FieldTypes/ServerField.php
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/General.php
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/General.xml
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/Menu/Menu.xml
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/Server.php
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/Server.xml
/usr/local/opnsense/mvc/app/views/OPNsense/Wireguard/diagnostics.volt
/usr/local/opnsense/mvc/app/views/OPNsense/Wireguard/general.volt
/usr/local/opnsense/scripts/Wireguard/gen_keypair.py
/usr/local/opnsense/scripts/Wireguard/reresolve-dns.py
/usr/local/opnsense/scripts/Wireguard/wg-service-control.php
/usr/local/opnsense/scripts/Wireguard/wg_show.py
/usr/local/opnsense/service/conf/actions.d/actions_wireguard.conf
/usr/local/opnsense/service/templates/OPNsense/Syslog/local/wireguard.conf
/usr/local/opnsense/service/templates/OPNsense/Wireguard/+TARGETS
/usr/local/opnsense/service/templates/OPNsense/Wireguard/wireguard
/usr/local/opnsense/service/templates/OPNsense/Wireguard/wireguard-server.conf
/usr/local/opnsense/version/wireguard
/usr/local/www/widgets/include/wireguard.inc
/usr/local/www/widgets/widgets/wireguard.widget.php

```

**Comment by fichtner** [comment]
Let’s not make a conspiracy theory out of traceable source code changes. Wireguard was community maintained since 2019 but now it moves to core (24.1) with a number of fundamental improvements and restructuring.FWIW, I’ve heard the report before and it seems valid, but there hasn’t been a GitHub ticket yet? Posting on the forum or Reddit is more unreliable WRT bug report handling and fixing, but that’s just as a general point. All I want to say is this appears to be a change in behaviour indeed and may have been in error.Cheers,FrancoOn 6. Nov 2023, at 00:12, doktornotor ***@***.***> wrote:﻿
Really, what's up with this package lately? Why does the GUI keep changing back and forth? Cf. the screenshot in #3632 and discussion there.
I have started a thread in the forums - and also someone there claims that the GUI I posted here is not what's shipping with 23.7.... 😖
# pkg info os-wireguard
os-wireguard-2.4_1
Name           : os-wireguard
Version        : 2.4_1
Installed on   : Sun Nov  5 22:21:10 2023 CET
Origin         : opnsense/os-wireguard
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : net
Licenses       : BSD2CLAUSE
Maintainer     : ***@***.***
WWW            : https://opnsense.org/
Comment        : WireGuard VPN service kernel implementation
Annotations    :
        FreeBSD_version: 1302001
        product_abi    : 23.7
        product_arch   : amd64
        product_email  : ***@***.***
        product_hash   : 13a20dcd3
        product_id     : os-wireguard
        product_name   : wireguard
        product_tier   : 3
        product_version: 2.4_1
        product_website: https://opnsense.org/
        repo_type      : binary
        repository     : OPNsense
Flat size      : 79.6KiB

# pkg list os-wireguard
/usr/local/etc/inc/plugins.inc.d/wireguard.inc
/usr/local/etc/rc.syshook.d/carp/20-wireguard
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ClientController.php
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/GeneralController.php
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ServerController.php
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ServiceController.php
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/DiagnosticsController.php
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/GeneralController.php
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardClient.xml
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardServer.xml
/usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/general.xml
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/ACL/ACL.xml
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/Client.php
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/Client.xml
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/FieldTypes/ServerField.php
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/General.php
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/General.xml
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/Menu/Menu.xml
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/Server.php
/usr/local/opnsense/mvc/app/models/OPNsense/Wireguard/Server.xml
/usr/local/opnsense/mvc/app/views/OPNsense/Wireguard/diagnostics.volt
/usr/local/opnsense/mvc/app/views/OPNsense/Wireguard/general.volt
/usr/local/opnsense/scripts/Wireguard/gen_keypair.py
/usr/local/opnsense/scripts/Wireguard/reresolve-dns.py
/usr/local/opnsense/scripts/Wireguard/wg-service-control.php
/usr/local/opnsense/scripts/Wireguard/wg_show.py
/usr/local/opnsense/service/conf/actions.d/actions_wireguard.conf
/usr/local/opnsense/service/templates/OPNsense/Syslog/local/wireguard.conf
/usr/local/opnsense/service/templates/OPNsense/Wireguard/+TARGETS
/usr/local/opnsense/service/templates/OPNsense/Wireguard/wireguard
/usr/local/opnsense/service/templates/OPNsense/Wireguard/wireguard-server.conf
/usr/local/opnsense/version/wireguard
/usr/local/www/widgets/include/wireguard.inc
/usr/local/www/widgets/widgets/wireguard.widget.php

**Comment by doktornotor** [comment]
Thanks, at least I'm not the only one who is seriously confused. Anyway, I need to get something up and running quickly for a use case where ISP broke IPsec altogether ages ago (some NAT madness) and now even OpenVPN keeps dying every other day with some replay errors. 

Is the (to be deprecated) Go plugin something I will eventually have to reconfigure from scratch, or will the config get imported when you switch to the OS package? The missing button to generate the keys suggests there's more to this than just nuking the validation for a quick local hack, but then again not sure whether the (updated) docs or the inline help is correct, regarding how it's supposed to work.

This was not meant to create any conspiracy theories; it's simply really confusing. Thanks again.

**Comment by fichtner** [comment]
Ok, so wireguard-go package will be removed by FreeBSD ports at the end of this year and we will drag it over the finish line in January until 24.1 is out. Our plugins (os-wireguard and os-wireguard-go) use the same code and structure so migration isn't an issue. The core version will be the os-wireguard one and in that sense the change from os-wireguard-go is automatic minus the idiosyncrasies built into the Go version that are not present in the Kernel implementation.

Just to be clear os-wireguard-go works for you now and os-wireguard shows this oddity? It could very well be that validation is the only change here (Required=Y in the model xml file).

**Comment by fichtner** [comment]
PS: Your screenshot suggests os-wireguard-go 1.13_7, not os-wireguard 2.4_1?

% git grep "Edit.Local.Configuration"
net/**wireguard-go**/src/opnsense/mvc/app/views/OPNsense/Wireguard/general.volt:{{ partial("layout_partials/base_dialog",['fields':formDialogEditWireguardServer,'id':'dialogEditWireguardServer','label':lang._('**Edit Local Configuration**')])}}

**Comment by fichtner** [comment]
Possible historic change 15a3559d58a

**Comment by doktornotor** [comment]
Well, I installed `os-wireguard`, got confused (as others) by the port deprecation message. Removed, installed the Go plugin. Did not have time to configure it, never touched it in fact. After a couple of days found out that the Go plugin is going to be deprecated in OPNsense, not the kernel variant. Since nothing was done, I removed the Go plugin again, reinstalled the OS plugin to finally get the work done. All via the plugins GUI.

Now I have reinstalled the OS plugin multiple times even after hitting the issue described here. 

Anyway, `os-wireguard-go` is NOT installed at the moment. 

```
# pkg info |  grep wireguard
os-wireguard-2.4_1             WireGuard VPN service kernel implementation
wireguard-kmod-0.0.20220615_1  WireGuard implementation for the FreeBSD kernel

```
```
# pkg info os-wireguard-go
pkg: No package(s) matching os-wireguard-go
```

Getting super confused really.

**Comment by fichtner** [comment]
> Getting super confused really.

The info you posted, looks normal but I just tested development core with built-in plugin and a VM with community and os-wireguard plugin:

<img width="940" alt="Screenshot 2023-11-06 at 08 22 49" src="https://github.com/opnsense/plugins/assets/1915288/37f29c19-6412-4cf6-95be-efe19910486a">

Notice the button for generating the key and the other modal title...

**Comment by fichtner** [comment]
Let's try a bigger hammer:

    # opnsense-revert os-wireguard

Does the GUI look better now?

**Comment by fichtner** [comment]
And what browser are you using? Any blockers in that one? https://github.com/opnsense/core/issues/6991 may be unwillingly related to the results you are seeing in terms of rendering / missing JS.

**Comment by doktornotor** [comment]
Negative.

```
 # opnsense-revert os-wireguard
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.

No packages are required to be fetched.
Integrity check was successful.
os-wireguard-2.4_1: already unlocked
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be REINSTALLED:
        os-wireguard-2.4_1

Number of packages to be reinstalled: 1
[1/1] Reinstalling os-wireguard-2.4_1...
[1/1] Extracting os-wireguard-2.4_1: 100%
Stopping configd...done
Starting configd.
Reloading plugin configuration
Configuring system logging...done.
Reloading template OPNsense/Syslog: OK
Reloading template OPNsense/Wireguard: OK

```

Still no button, still the validation issue, and still no "Instance". 

![image](https://github.com/opnsense/plugins/assets/1075960/481d0004-5694-454e-b846-a6e06515c60f)

**Comment by fichtner** [comment]
That's definitely the GUI part for wireguard-go... maybe the rendering for the volt templates is not cleared?

    # configctl webgui restart


Cheers,
Franco

**Comment by doktornotor** [comment]
Bingo! Works now, button there and the GUI is completely different. 

![image](https://github.com/opnsense/plugins/assets/1075960/d1a7b2f5-ca92-453b-8651-7cdcca598e84)

**Comment by fichtner** [comment]
Ok, that wireguard thing should be good now. A little worried about the cache mechanics... never seen fail this before. Maybe a timestamp issue / NTP going backwards for bit preventing the clearing of stale files (look newer than they are)?

**Comment by doktornotor** [comment]
Hmmm, did not notice anything odd with time (except that the pools are not implemented properly, known issue, but the whole network syncs from the domain controllers anyway.

```
# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 0.cz.pool.ntp.o .POOL.          16 p    -   64    0    0.000   +0.000   0.000
 1.cz.pool.ntp.o .POOL.          16 p    -   64    0    0.000   +0.000   0.000
 2.cz.pool.ntp.o .POOL.          16 p    -   64    0    0.000   +0.000   0.000
 3.cz.pool.ntp.o .POOL.          16 p    -   64    0    0.000   +0.000   0.000
*dc1.intranet.ex 218.193.203.158  3 u  325  512  377    0.869   -1.449   0.324
+82.113.53.41    5.1.56.123       2 u  463  512  377    7.504   -4.088   0.201
+ntp.nic.cz      .GPS.            1 u  514  512  377    7.530   -3.672   0.233
+inter.tyjo.eu   217.31.202.100   2 u  503  512  177    7.691   -3.887   0.159
+ntp1.karneval.c 116.49.102.213   2 u  358  512  377    8.986   -4.180   0.239
+ntp1.karneval.c 116.49.102.213   2 u  340  512  377    9.285   -3.685   0.372
+ntp.suas.cz     .PTP1.           1 u  348  512  377   11.257   -3.599   0.205

```

**Comment by fichtner** [comment]
Hmm, ok, close this and raise a core issue about volt cache when this happens again? Attach the following to be able to inspect the timestamp theory:

    # date && ls -lah /usr/local/opnsense/mvc/app/cache/*.php 


Cheers,
Franco

**Comment by doktornotor** [comment]
Agreed. Thanks for help @fichtner 

```
# date && ls -lah /usr/local/opnsense/mvc/app/cache/*.php
Mon Nov  6 08:51:57 CET 2023
-rw-r-----  1 root  wheel   5.8K Nov  6 08:36 /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_layout_partials_base_dialog.volt.php
-rw-r-----  1 root  wheel   3.5K Nov  6 08:36 /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_layout_partials_base_form.volt.php
-rw-r-----  1 root  wheel   6.7K Nov  6 08:36 /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_layout_partials_base_menu_system.volt.php
-rw-r-----  1 root  wheel   4.1K Nov  6 08:36 /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_layout_partials_form_input_tr.volt.php
-rw-r-----  1 root  wheel    15K Nov  6 08:36 /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_layouts_default.volt.php
-rw-r-----  1 root  wheel   6.9K Nov  6 08:36 /usr/local/opnsense/mvc/app/cache/_usr_local_opnsense_mvc_app_views_opnsense_wireguard_general.volt.php

```

**Comment by fichtner** [comment]
Looks as expected for now. Thanks for helping debug this so far.
