### ISSUE TITLE
security/acme-client: support 2fa for inwx API

### ISSUE THREAD

**Issue by pkoevesdi** [opnsense/plugins#3942]
**Important notices**
- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
When using inwx as domain host, I cannot set 2fa inside this plugin.

**Describe the solution you'd like**
An additional field for the shared secret and a functionality of the plugin to gereate the TOTP from it, when requested.

**Additional context**
![grafik](https://github.com/opnsense/plugins/assets/33196971/1d95324d-65c1-45ff-909b-c72a90474f92)

**Comment by fraenki** [comment]
Note to myself: upstream documentation...
https://github.com/acmesh-official/acme.sh/wiki/dnsapi#dns_inwx

**Comment by TheHellSite** [comment]
@fraenki Hey, any updates on this? (no rush)

I just bumped into this issue after enabling 2FA for my INWX account only 5 days after the last cert was renewed fine. Now 3 months later it failed and the same issue occurred for me. If INWX would simply provide API keys instead of relying on the same user+pw+2fa auth... this wouldn't even be an issue.

**Comment by fraenki** [comment]
@TheHellSite Apparently no news. If anyone wants to contribute the missing functionality, I'll gladly review any PR.
