### ISSUE TITLE
www/caddy add copy_headers

### ISSUE THREAD

**Issue by mimi0000oo** [opnsense/plugins#4056]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

I want to add authelia in front of my reverse proxy setup. 
The guide, on authelia's website: https://www.authelia.com/integration/proxies/caddy/
and Caddy website: https://caddyserver.com/docs/caddyfile/directives/forward_auth

They both suggest that `copy_headers` should be an option, but there is no way to be found in the gui

**Describe the solution you'd like**

Simple, add the option to the plugin! I guess that should be on the headers page, but I've searched through all the other and couldn't find anything.

**Describe alternatives you've considered**

For now I am trying to modify the Caddyfile manually.

**Comment by Monviech** [comment]
I have a branch here I did a while ago where I tried to fit forward auth into the GUI:

https://github.com/Monviech/opnsense-plugins/tree/forward-auth-stached

I have documented it too:

https://github.com/Monviech/opnsense-docs/blob/forward-auth-stached/source/manual/how-tos/caddy.rst#authelia-as-forward_auth-provider

Warning, this is unusable in the current plugin. I just wanted to show I have spend considerable time on it in the past.

I came to the conclusion that its unfeasable right now, look at the documentation and how careful you would need to set it up, and it still would break because the current template generation has no way to create specific orders.

Authelia sadly needs a very specific order of handles to work. In the GUI there is no way to say "First this handle, then this, and then this last". It's all generated implicitly based on which handlers have been created first.

Right now, you have to continue to use the import statements. (You don't really have to edit the Caddyfile manually.

https://docs.opnsense.org/manual/how-tos/caddy.html#using-custom-configuration-files


So, I sadly have to say this is out of scope for me right now. If somebody wants to pick up on my work in that branch I left behind, feel free to.

**Comment by Monviech** [comment]
@mimi0000oo

I think I have a new idea here how I could theoretically make this work, without making it too convoluted or prone to breakage.

But before working on it, I want to know if I can count on you to test this.

**Comment by Monviech** [comment]
@mimi0000oo I have created a PR for you to test. If you have any questions, just ask.

**Comment by Monviech** [comment]
@mimi0000oo Authelia is part of the plugin now since 24.1.10. Could you test if it works as expected?

**Comment by adrianzech** [comment]
Hi @Monviech, 
awesome work with the plugin, I'm really loving it so far!

Would it be possible to add Authentik to the Auth Provider list or make it more customizable? At the moment we can't set the copy_headers as they are as far as I can see hardcoded for Authelia.

This is an example from the Authentik documentation: 
`app.company {
    # always forward outpost path to actual outpost
    reverse_proxy /outpost.goauthentik.io/* http://outpost.company:9000

    # forward authentication to outpost
    forward_auth http://outpost.company:9000 {
        uri /outpost.goauthentik.io/auth/caddy

        # capitalization of the headers is important, otherwise they will be empty
        copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version

        # optional, in this config trust all private ranges, should probably be set to the outposts IP
        trusted_proxies private_ranges
    }

    # actual site configuration below, for example
    reverse_proxy localhost:1234
}`
https://docs.goauthentik.io/docs/providers/proxy/server_caddy

Please let me know if I can help with anything or if I should create a new feature request.
Thank you very much!

**Comment by Monviech** [comment]
@adrianzech https://github.com/opnsense/plugins/pull/4104

Already added xD, will be in os-caddy-1.6.2

**Comment by adrianzech** [comment]
Oh sorry I missed that while searching.

Thank you very much for your work @Monviech ! :)

**Comment by Monviech** [comment]
@adrianzech If you want you can already test it:

```opnsense-patch -c plugins 7d837d7f6dbd7aab495150601a3223214689967c```

**Comment by adrianzech** [comment]
@Monviech Awesome! I'll give it a try the next few days. Thank you :)
