### ISSUE TITLE
net/relayd: File /var/log/relayd.log doesn't exist

### ISSUE THREAD

**Issue by shezzski** [opnsense/plugins#409]
## Background
I have a 3 day old installation of OPNsense 17.7.8-amd64.  This installation was build ontop of a FreeBSD 11.0 VM via opnsense-bootstrap on Microsoft Azure.

## Problem
I have installed the relayd plugin "os-relayd  version 1.1_1" and have noticed that that there is no log file located at /var/log/relayd.log, which is also shown to be missing using the GUI under SERVICES -> LOAD BALANCER -> LOG FILE with the error "File /var/log/relayd.log doesn't exist"

**Comment by fichtner** [comment]
Hi @shezzski,

This is due to https://github.com/opnsense/core/issues/1930 -- you need a syslog restart or reboot for this file to materialise. Once upon a time relayd was part of the core, so that problem did not exist, but now more plugins are having this issue so we need to solve it, but from the core side. I am not fully sure how yet.

You can manually restart logging by saving the System: Settings: Logging page.

I will close this issue since we have an open ticket and they are now linked.


Cheers,
Franco
