### ISSUE TITLE
Caddy - Allow Access list selection for Handlers to be able to block certain paths from the internet.

### ISSUE THREAD

**Issue by The-Istar** [opnsense/plugins#4223]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

I want to migrate my current Caddy Installation over to Opnsense. However my current Caddy files blocks access to my vaultwarden admin page from the internet and only allows local access. However I do not see how I could replicate this in Opnsense.

This has actually discussed on the Vaultwarden github here: [](https://github.com/dani-garcia/vaultwarden/discussions/2626)
And working Caddy examples can actually be found here: [](https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples)

**Describe the solution you'd like**
(e.g. I would like an input field in the `/ui/firewall/alias` which would add .... to ....)

Ideally I would be able to just select my access list from within the HTTP Handler form under the Header Access. Currently it only lists forward auth.

**Describe alternatives you've considered**

I would stay with my current setup

**Additional context**

For reference a copy paste from the Caddy example on the Vaultwarden Github:

```
# Uncomment this in addition with the import admin_redir statement allow access to the admin interface only from local networks
# (admin_redir) {
#        @admin {
#                path /admin*
#                not remote_ip private_ranges
#        }
#        redir @admin /
# }

{$DOMAIN} {
  log {
    level INFO
    output file {$LOG_FILE} {
      roll_size 10MB
      roll_keep 10
    }
  }

  # Uncomment this if you want to get a cert via ACME (Let's Encrypt or ZeroSSL).
  # tls {$EMAIL}

  # Or uncomment this if you're providing your own cert. You would also use this option
  # if you're running behind Cloudflare.
  # tls {$SSL_CERT_PATH} {$SSL_KEY_PATH}

  # This setting may have compatibility issues with some browsers
  # (e.g., attachment downloading on Firefox). Try disabling this
  # if you encounter issues.
  encode zstd gzip

  # Uncomment to improve security (WARNING: only use if you understand the implications!)
  # If you want to use FIDO2 WebAuthn, set X-Frame-Options to "SAMEORIGIN" or the Browser will block those requests
  # header / {
  #	# Enable HTTP Strict Transport Security (HSTS)
  #	Strict-Transport-Security "max-age=31536000;"
  #	# Disable cross-site filter (XSS)
  #	X-XSS-Protection "0"
  #	# Disallow the site to be rendered within a frame (clickjacking protection)
  #	X-Frame-Options "DENY"
  #	# Prevent search engines from indexing (optional)
  #	X-Robots-Tag "noindex, nofollow"
  #	# Disallow sniffing of X-Content-Type-Options
  #	X-Content-Type-Options "nosniff"
  #	# Server name removing
  #	-Server
  #	# Remove X-Powered-By though this shouldn't be an issue, better opsec to remove
  #	-X-Powered-By
  #	# Remove Last-Modified because etag is the same and is as effective
  #	-Last-Modified
  # }

  # Uncomment to allow access to the admin interface only from local networks
  # import admin_redir

  # Proxy everything to Rocket
  # if located at a sub-path the reverse_proxy line will look like:
  #   reverse_proxy /subpath/* <SERVER>:80
  reverse_proxy <SERVER>:80 {
       # Send the true remote IP to Rocket, so that Vaultwarden can put this in the
       # log, so that fail2ban can ban the correct IP.
       header_up X-Real-IP {remote_host}
       # If you use Cloudflare proxying, replace remote_host with http.request.header.Cf-Connecting-Ip
       # See https://developers.cloudflare.com/support/troubleshooting/restoring-visitor-ips/restoring-original-visitor-ips/
       # and https://caddy.community/t/forward-auth-copy-headers-value-not-replaced/16998/4
  }
}

```

**Comment by Monviech** [comment]
For very specific configurations, you can put the site block into a custom configuration file, and it gets imported into the Caddyfile.

The flexibility of the GUI has its limits here.

Though there also is another way, reverse proxy the path to an upstream that does not exist.

https://docs.opnsense.org/manual/how-tos/caddy.html#advanced-configuration

Check out Multiple Handlers for a Domain, and Custom Configuration Files

**Comment by The-Istar** [comment]
Thanks, I was aware of both options. But blackholing the path means I can not access it at all, while the goal is to only access it inside my own network and block it externally.

As for using an advances config file. I am also aware this option exists but I assumed / was hoping that  extending the access list functionality to include the handlers was not too complicated.

Also I assumed that the goal would be to implement as much as possible in the GUI to discourage users from fiddling around.

On that note, any chance of getting the editing from the advanced config files added tot he GUI (In some sort of web editor) ?

**Comment by Monviech** [comment]
The issue is the complex template generation. The hierarchy of the Caddyfile is a nested structure with named handlers inside named handlers.

Certain design choices were made, for example automatic implicit ordering of Path handles by empty/populated. Access lists would have to match before the handle matches in the structure of the current template, that would mean any handler ordering could not be done the current way anymore.

The access lists also use uuids as named matchers. On the same hierarchy there cant be more named matcher with the same name, it would break the Caddyfile. That would mean the Access List implementation per domain and in a separate unique menu conflicts at its very core with the need to implement it per reverye proxy handle.

This would need considerable amount of work to change while keeping the current functionality the way it is. If anybody wants to try, feel free to. But its going to be quite hard.

In contrast, forward auth per handle is easy, since it just needs to render without being nested around it inside a path handle.

Its hard to explain, but look at how the template generates the Caddyfile and you can see how intricate and hard it is. Its at the very limit and the implementation should be considered stable and done.

**Comment by The-Istar** [comment]
Understood. Thanks for the explanation. Guess I need to figure out how to best implement this with the advanced options.

**Comment by Monviech** [comment]
Maybe theres a way to render it somehow in a clever way. If somebody has a nice idea that does not break current setups, feel free to write it here or offer a PR. Not against it. I just lack the time personally right now.

**Comment by The-Istar** [comment]
So, I thought I try to just create another domain (something like admin.domain.com) and forward this to the /admin path. However, it seems there is no way to rewrite the path either? So that requests to admin.domain.com actually go to vaultwarden.domain.com/admin or 10.11.12.13:80/admin ?
Or am I missing something?

**Comment by Monviech** [comment]
Theres this option that prepends a path to the request with a rewrite:

https://github.com/opnsense/plugins/blob/5a02d3867d5e074837a1de8af7ffbaa46552a89f/www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml#L88

Its in the advanced options of handlers, enable the toggle.

**Comment by The-Istar** [comment]
Ok, seems I was blind. Thanks for the quick reply! Seems I totally overlooked this.

**Comment by Monviech** [comment]
np, some options are more well hidden for reasons. This one is mostly for apache tomcat stuff, but if it works for you too, good job. :)

**Comment by The-Istar** [comment]
After finally being able to fully test this I can confirm this did not work for my use case. Although I was able to work around it by changing my setup. So my immediate need was resolved. Though it would still be a nice feature to have.

**Comment by Monviech** [comment]
Thinking about it again it wouldnt be too hard if it is inserted the same way as the forward auth directive into the handle.

But I want somebody else to do this and offer a PR. Im sure somebody will step up if its a much needed feature.

**Comment by mtchetch** [comment]
I would like to +1 this for the following usecase:

Nextcloud installation running unred nextcloud.domain.com that needs to be accessible fully from LAN network and only partially from WAN networks

I got the http handlers to do what i want and allow only the paths:

- /s/ - shared files
- /apps/* - app related files that provide the UI
- /core/* - main theme files
- /css/* - CSS files

but at the moment there is no aparent way to target these handlers to be only for connections from WAN and allow everything from LAN. 

Any ideas or solutions?

**Comment by Monviech** [comment]
Why are you doing this? A nextcloud has user authentication. It even has plugins to ban IPs. A fully patched Nextcloud is designed to be exposed to the internet.

Just conflicted to add something that is so specific for usecases I do not understand.

Better use a custom Caddyfile configuration in the caddy.d folder.

**Comment by mtchetch** [comment]
> Why are you doing this? A nextcloud has user authentication. It even has plugins to ban IPs. A fully patched Nextcloud is designed to be exposed to the internet.
> 
> Just conflicted to add something that is so specific for usecases I do not understand.
> 
> Better use a custom Caddyfile configuration in the caddy.d folder.
> 
> I will wait for a PR here.

Thanks for getting back to me and considering my request.

I understand that Nextcloud is meant to be exposed to the internet and has user authentication along with plugins for IP banning. However, since it's a complex piece of software with a large codebase, there's always a possibility of security vulnerabilities. In fact, Nextcloud has had issues in the past, as shown by their CVE list: [CVE Details for Nextcloud](https://www.cvedetails.com/vulnerability-list/vendor_id-15913/Nextcloud.html?page=1&order=3). Even though the developers are quick to patch, zero-day vulnerabilities can still pose a risk before they're addressed.

I believe it's good practice to limit exposure of systems when possible. By using a reverse proxy, we can expose only the shared resources that need to be accessible externally while keeping the rest of the application behind the proxy and accessible only within our local network. This adds an extra layer of security without hindering the functionality we need from Nextcloud's sharing features. Safeguarding our internal information is very important to us and that is why we need to implement additional security measures.

I get that this might be a specific use case you're not familiar with, and I'm willing to implement these changes using a custom Caddyfile configuration in the caddy.d folder, as you suggested. I am not entirely sure how one would implement the external custom caddyfile correctly with out breaking the domain cert generation and other features that are working as expected.

I feel that this might not be such an unique use case and it would benefit the community using OPNSense to be able to add access control on a per handle basis from the gui.

**Comment by Monviech** [comment]
If you want to have an additional layer of security, why not use Crowdsec and let it analyze the Caddy HTTP Access Logs?

That would fit your usecase for security a lot more dynamically.

https://docs.opnsense.org/manual/how-tos/caddy.html#crowdsec-integration

**Comment by mtchetch** [comment]
This is a great idea to have this as an additional layer of security. We will look into this. I think that we still would like to block all actors from accessing non shared content on our Nextcloud instance, not only bad actors as defined by crowdsec.

I would like to share the custom Caddyfile that I created for split filtering an owncloud instance for our use case. Hopefully it is helpfull for someone.

``` 
domain.for.nextcloud {

    # Define a matcher for public paths accessible by any client
    @publicPaths {
        path /s/* /apps/* /css/* /core/* /dist/* /public.php/*
    }

    # Allow public paths from any client
    handle @publicPaths {
        reverse_proxy 192.168.33.189:11000
    }

    # Define a matcher for LAN clients
    @lanClients {
        remote_ip 192.168.33.0/24 192.168.34.0/24 10.10.10.0/24 192.168.11.0/24
    }

    # Handle requests from LAN clients (allow access to all paths)
    handle @lanClients {
        reverse_proxy 192.168.33.189:11000
    }

    # Deny access to all other requests (non-LAN clients accessing non-public paths)
    handle {
        respond "Access denied" 403
    }
}

**Comment by Monviech** [comment]
I added a PR with an idea how to include it. Please test this and give me feedback. I will only add this if it has been tested by the requesting users.

**Comment by mtchetch** [comment]
Wow, that was fast. I would love to test your PR. I am not familiar with the procedure for actually getting the PR code onto a running OPNSense instance. I am confortable with Terminal, SSH and Linux/Unix systems in general so a brief outline of steps should be enough to get me by.

**Comment by Monviech** [comment]
Dont test it yet it has several drawbacks, it will need more time to cook. Open for ideas here.

**Comment by mtchetch** [comment]
> Dont test it yet it has several drawbacks, it will need more time to cook. Open for ideas here.

Since the order of processing is important for Caddy, There _could_ be an ordering number field in the  HTTP handlers that are used for a particular domain. That way it would be possible to put the handler blocks in a particular order and  that could in theory help with the catch all clauses working, since Caddy aparently works like nginx and stops processing further rules on first match for the traffic.

**Comment by Monviech** [comment]
I have pushed a new commit to the draft PR. Now access lists can be added onto domain and handlers and a configuration like this will be generated:

- Allow all IPs other than 3.3.3.3 to continue to the path handlers.
- Deny all IPs other than 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8 to access 192.168.1.1:8080 /after/ having been matched with handle /css/*

This will stop the processing right there for IPs that got caught inside `handle /css/*` and are then denied in there.

```
# Reverse Proxy Domain: "55e9c96f-9694-4ff7-a197-7fb97ffa3c21"
example.com {
	@47ff71af-f35b-4f1c-a5b8-128c29a0d770 {
		not client_ip 3.3.3.3
	}
	handle @47ff71af-f35b-4f1c-a5b8-128c29a0d770 {
		handle /css/* {
			@d72c1182-6f05-4c25-8d9f-6a226a9039ea {
				not client_ip 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
			}
			handle @d72c1182-6f05-4c25-8d9f-6a226a9039ea {
				abort
			}
			reverse_proxy 192.168.1.1:8080 {
			}
		}

		handle /private {
			@d72c1182-6f05-4c25-8d9f-6a226a9039ea {
				not client_ip 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
			}
			handle @d72c1182-6f05-4c25-8d9f-6a226a9039ea {
				abort
			}
			reverse_proxy 192.168.1.1:8080 {
			}
		}

		handle /something/special/* {
			@7bf956ab-acea-4b1e-bfd0-8719788f3532 {
				client_ip 1.1.1.1 8.8.8.8
			}
			handle @7bf956ab-acea-4b1e-bfd0-8719788f3532 {
				respond "Forbidden" 403
			}
			reverse_proxy 192.168.1.1:8080 {
			}
		}

		handle {
			reverse_proxy 192.168.1.1:8080 {
			}
		}
	}

	abort
}
```

Since empty handles always get generated last, regardless of their spot in the configuration, all handles that specify paths will match before it. Inside these, the client ips can be matched, and an `abort` or `respond` will block further processing. The abort will always be generated if there is no response code in the handler.

I think this will work but I need testing here.

**Comment by Monviech** [comment]
This will come automatically in the next version, from my tests it should be fine.

**Comment by The-Istar** [comment]
Thanks Monviech!

**Comment by mtchetch** [comment]
Great job @Monviech, looking forward to the new version!

**Comment by Monviech** [comment]
@mtchetch Its already out in os-caddy-1.7.1 :)

https://forum.opnsense.org/index.php?topic=43063

If you test it tell me if it works for you. Thanks.

**Comment by mtchetch** [comment]
> @mtchetch Its already out in os-caddy-1.7.1 :)
> 
> https://forum.opnsense.org/index.php?topic=43063
> 
> If you test it tell me if it works for you. Thanks.

I tested this successfully and it seems to work perfectly. Thank you for your work on the changes!

The implementation could be made slightly better if it would allow paths to be chained together.

My hand crafted custom config does this but when using the plugin it is not allowed.

This is not a very big issue, but would probably improve performance and readability when all paths could be defined under one rule.

My config has the paths:

"/s/*",
 "/apps/*",
 "/css/*",
 "/core/*",
 "/dist/*",
 "/public.php/*",
 "/csrftoken",
 "/ocs/*",
 "/js/*"

JSON (for another nextcloud instance)
```

{
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "group": "group17",
                      "handle": [
                        {
                          "handler": "subroute",
                          "routes": [
                            {
                              "handle": [
                                {
                                  "handler": "reverse_proxy",
                                  "upstreams": [
                                    {
                                      "dial": "192.168.33.189:11000"
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ],
                      "match": [
                        {
                          "path": [
                            "/s/*",
                            "/apps/*",
                            "/css/*",
                            "/core/*",
                            "/dist/*",
                            "/public.php/*",
                            "/csrftoken",
                            "/ocs/*",
                            "/js/*"
                          ]
                        }
                      ]
                    }
```

VS individual rules generated by the plugin
```
...

              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "group": "group19",
                      "handle": [
                        {
                          "handler": "subroute",
                          "routes": [
                            {
                              "handle": [
                                {
                                  "handler": "reverse_proxy",
                                  "upstreams": [
                                    {
                                      "dial": "192.168.33.195:11000"
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ],
                      "match": [
                        {
                          "path": [
                            "/public.php/*"
                          ]
                        }
                      ]
                    },
                    {
                      "group": "group19",
                      "handle": [
                        {
                          "handler": "subroute",
                          "routes": [
                            {
                              "handle": [
                                {
                                  "handler": "reverse_proxy",
                                  "upstreams": [
                                    {
                                      "dial": "192.168.33.195:11000"
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ],
                      "match": [
                        {
                          "path": [
                            "/csrftoken"
                          ]
                        }
                      ]
                    },

...
```
![image](https://github.com/user-attachments/assets/ed74e337-b210-4eda-b4d3-d2bb920d1630)

![image](https://github.com/user-attachments/assets/46395d89-8951-4e4f-ac06-3a3bf8b15429)

**Comment by Monviech** [comment]
Thank you for testing, I'm happy it works.

About your request, I can not change this right now without considerable effort.

https://caddyserver.com/docs/caddyfile/directives/handle

The handle can only take one "argument count". The current mask follows what handle can do very closely.

I would need to abstract it with introducing named matchers, so you could create group of them and then handle the named matcher. That would then make other configurations more complicated.

I will think about introducing a sequence number though to order these configurations more easily. You can see how the Sequence number works and looks like in the Layer 4 module.

**Comment by mtchetch** [comment]
Thanks for your reply. I think that this will not be a problem at the scale that we operate at since these split configs with multiple pattern matches are edge cases. We use a similar config for nextcloud as well as password pusher to keep the management portals in our internal network and still allow external clients to access shared links and resources.

I am happy that this works now with out the need for custom configs and is easy to setup even though there is aneed to create a separate config for each url pattern. When adding multiple matchers one needs to remember to add the pattern to the description in order for it to be visible and clear in the ui and be easy to manage and administer.

Over all, good job and thanks for taking the time to implement this, even though it is not a feature that most users need.

**Comment by Monviech** [comment]
@mtchetch I think it was a valuable addition.

You can also do other things now in the latest version, like the weird nextcloud redirects if needed:

https://github.com/opnsense/plugins/pull/4263
