### ISSUE TITLE
security/acme-client: Automation fails to authenticate on Synology NAS

### ISSUE THREAD

**Issue by GitTimeraider** [opnsense/plugins#4286]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [ X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ X] The title contains the plugin to which this issue belongs

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

When using the automation rule "Upload certificate to Synology DSM", it fails to authenticate on the Synology NAS.
The user login used is an admin account, IP and port as correctly set from DSM settings.
Synology 720+ with DSM 7.2.2-72806
So far tried: 
- https and https
- the actual base admin account instead of a new one
- turning off any security I had on the NAS

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
Set up an ACME certificate renewal (which does work)
Create an user on the Synolgy NAS and add him to the Administrator group
Create an "Upload certificate to Synology DSM" automation rule in the ACME-client plugin UI.
Try running the automation, it fails.

**Expected behavior**
An certificate being created and/or renewed on the Synology NAS

**Screenshots**
![Screenshot 2024-10-09 201423](https://github.com/user-attachments/assets/a04baaca-b5ea-4469-9484-1dae131fcc66)

**Relevant log files**
If applicable, information from log files supporting your claim.

[new 1.txt](https://github.com/user-attachments/files/17317076/new.1.txt)

**Additional context**

**Environment**
Router
OPNsense 24.7.6-amd64
ACME plugin 4.6

NAS
Synology NAS 7.2.2-72806

**Comment by GitTimeraider** [comment]
Ok.. even when I change the IP address in the automation, it still tries to authenticate against the old IP even though that automation doesnt exist anymore.
I think something is going wrong there... any locations I can check out where it saves automations or something?

**Comment by GitTimeraider** [comment]
Ok.. found the issue. The ACME-client plugin seems to save automation settings together with the certificate settings somewhere (dont ask me where.. if I knew I would have wiped that stuff out into space already)
So the only way was to make a new certificate in the ACME client and then it did pick up the changes in automation.
So... why or where? 
Because I do NOT want to have to recreate certificates just to adjust automation rules simply because the plugin doesnt seem to be able to clean those settings up correctly.

**Comment by JoTec2002** [comment]
Same issue here - especially problematic since I want to deploy the same cert to two different NAS Systems. For the second NAS allways the saved values are used.

Is it maybe possible to deactivate the saving of the Environment variables?

**Comment by JerryFrum** [comment]
Same exact error/issue here.  Even if you remove the automation and create a brand new one, it seems to still ignore the port.  So when I looked at the .conf file for my installation, it showed that I did create a new automation to use HTTPS (from default HTTP) but despite putting in port 5001, it wouldn’t change what’s in the conf file as 5000.  Manually editing the .conf for that cert fixed things.

I’m going to try creating a new cert to see if its because I originally created the certs when the automation was using HTTP and port 5000, but then changed it later but it was already stuck using 5000 and ignored any future changes to different ports.  24.7.7 with 4.6 Acme client.

**Comment by mhalife** [comment]
Same issue here too !! I want to deploy the same certificate to two Synology systems. I've tried all; remove and delete all directories and the reinstall the plugin. Recreate a new account, challenge, automation and certificate !
Tried to modify the config file in " /var/etc/acme-client/cert-home/" but no chance.

**Comment by JoTec2002** [comment]
I found a possible root cause of error but would need some help setting up a viable dev environment to test it out.


In the File `https://github.com/opnsense/plugins/blob/master/security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php#L141` is a function to clean up the conf files based on the deploy hook name.

```
// acme.sh records the last used deploy hook and would automatically
// use it on the next run. This information must be removed from the
// configuration file. Otherwise it would be impossible to disable
// or remove a deploy hook from the GUI.
foreach (glob(self::ACME_HOME_DIR . '/*/*.conf') as $filename) {
    // Skip openssl config files.
    if (preg_match('/.*.csr.conf/i', $filename)) {
        continue;
    }

    // Read contents from file.
    $contents = file_get_contents($filename);

    // Check if deploy hook string can be found.
    if (strpos($contents, self::ACME_DEPLOY_HOOK_STRING) !== false) {
        // Replace the whole line with an empty string.
        $contents = preg_replace('(' . self::ACME_DEPLOY_HOOK_STRING . '.*)', '', $contents);

        // Write changes to the file.
        if (!file_put_contents($filename, $contents)) {
            LeUtils::log_error('clearing recorded deploy hook from acme.sh failed (' . $filename . ')');
        } else {
            LeUtils::log_debug('cleared recorded deploy deploy hook from acme.sh (' . $filename . ')', $this->debug);
        }
    }
}
```
The Synology Deploy Hook name is `synology_dsm` but the variables are `SYNO_xxxxx` so their not getting cleaned up properly. In the Logs this would possibly explain the line 
`Domain config new key exists, old key SYNO_Certificate='OPNsense ACME' has been removed.`

**Comment by fraenki** [comment]
Maybe a upstream changes broke support for DSM:
https://github.com/acmesh-official/acme.sh/wiki/deployhooks#20-deploy-the-certificate-to-synology-dsm
https://github.com/acmesh-official/acme.sh/commits/master/deploy/synology_dsm.sh
If someone can spot the changes that need to be made, please let me know.

**Comment by gitwildnow** [comment]
The /var/etc/acme-client/cert-home/ gets regenerated only when you issue the cert - not if you just tell the webui to run the automations.

**Comment by fraenki** [comment]
@GitTimeraider How is this related to this bug report?

**Comment by JoTec2002** [comment]
In the log of the Original issue you will find the lines: 

```20:14:34 CEST 2024] Domain config new key exists, old key SYNO_Port='DSM PORT' has been removed.```

So his Automation also runs with old, probably wrong, credentials.

**Comment by GitTimeraider** [comment]
> In the log of the Original issue you will find the lines:
> 
> `20:14:34 CEST 2024] Domain config new key exists, old key SYNO_Port='DSM PORT' has been removed.`
> 
> So his Automation also runs with old, probably wrong, credentials.

This is correct.
Like said in the original, my specific issue was that when youve set up the automation and added it to an certificate issue under the Certificates tab of the ACME client plugin .. it keeps the old credentials even if you change the credentials in the automation afterwards.
This persists even with an reissue of the certificate for me. All that can make the automation use the "new" set credentials was to fully delete the certificate from the Certificates tab in the ACME client plugin and then create that one again.

**Comment by fraenki** [comment]
> it keeps the old credentials even if you change the credentials in the automation afterwards

@GitTimeraider So you've changed the (Synology) credentials and now it does not work anymore?

**Comment by GitTimeraider** [comment]
> > it keeps the old credentials even if you change the credentials in the automation afterwards
> 
> @GitTimeraider So you've changed the (Synology) credentials and now it does not work anymore?

If you change the Synology credentials (or IP address or Port) in the automation ... the certificate in acme client will keep using the old setting for the Synology automation whenever it tries to run it in any way, thus not working if those are now incorrect

**Comment by gitwildnow** [comment]
After the automation fails, go to your System->Log Files->General and you'll find the failing command logged there. It will look something like:

`AcmeClient: AcmeClient: The shell command returned exit code '1': '/usr/local/sbin/acme.sh --deploy --syslog 6 --log-level 1 --server 'letsencrypt'...`

To see in detail what's going wrong, start a ssh session. Grab all the text between the quotes starting at /usr/local/sbin... If you execute it in ssh then it still fails but without much more in the way of clues. Now change the _--log-level 1_ argument to _--debug --output-insecure_. Now the command looks something like this...

`/usr/local/sbin/acme.sh --deploy --syslog 6 --debug --output-insecure --server 'letsencrypt'...`

Run it again and you'll see debug output including the literal password that's being passed to your Synology NAS. You'll see here that if you've changed the password in your OPNsense config, that it is still using the old password instead.

Now if you go to /var/etc/acme-client/cert-home you'll find one directory for each certificate and in that directory you'll find a .conf file that has the bad credentials stored with a _SAVED_SYNO_PASSWORD=_ line etc.

Look at the date/time stamp on that file and you'll find that it matches roughly when you last issued the certificate. If you delete the whole directory under cert-home, it will NOT get regenerated when you run the automations again, it will just fail more catastrophically because of the missing config files.

However, if you go to the webui for the acme plugin and tell it reissue the certificate, now it WILL regnerate the config in acme-client and successfully update your nas. If it does not, you have another problem. Repeat the steps for running it in debug mode at the ssh prompt and you'll see what's going wrong and you can confirm it using the correct password now.

**Comment by murphysprings** [comment]
Thank you @fraenki ! The patch works correctly. I can now push to multiple DSMs.

**Comment by fraenki** [comment]
Thanks for testing and providing feedback, much appreciated.
