### ISSUE TITLE
Caddy fails to start when HTTPS is disabled for the web gui

### ISSUE THREAD

**Issue by sdellysse** [opnsense/plugins#4288]
Problem: When `System: Settings: Administration: Web GUI: Protocol` is set to `HTTP`, and `System: Settings: Administration: Web GUI: TCP Port` is set to `81`, the caddy server will fail to start. I fixed this by changing `System: Settings: Administration: Web GUI: Protocol` to `HTTPS`, changing `System: Settings: Administration: Web GUI: TCP Port` to `8443`, set `System: Settings: Administration: Web GUI: Http Redirect` to `unchecked`.

Expected outcome: when the protocol is `http` and the port is `!= 80`, caddy should start.

The code that needs to be fixed is somewhere in this block but I haven't had a chance to try to fix it myself: https://github.com/opnsense/plugins/blob/f25a1fa6d54ef53339ab02685ecaf53a8fa5fcbb/www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php#L77C1-L94C6

**Comment by Monviech** [comment]
That code you referenced is only a validation to give users feedback that something they configured might collide with what caddy expects.

But caddy is not controlled by that code. I am sure there are a few more configurations that will slip through the cracks.

E.g. if you have another plugin binding ports that Caddy might like to use.

In the Layer 4 module thats included you are able to bind any port that you want, there's no way to validate against all plugins in the system. Caddy will just try to start, and if it can not bind the ports it needs it will fail.

**Comment by clsferguson** [comment]
This is a problem for me too, I have been using mimugmail's caddy plugin. I have https disabled, and the TCP port is 81. Using that plugin my setup works, I was hoping to move the official plugin and have a gui. But when I try to set Auto https to on, it says port 80 is conflicting, and I need to ->

"To use "Auto HTTPS", resolve these conflicting ports 80 that are currently configured for the OPNsense WebGUI. Go to "System - Settings - Administration". To release port 80, enable "Disable web GUI redirect rule". To release port 443, change "TCP port" to a non-standard port, e.g., 8443." 

this is with mimugmail's caddy plugin service stopped.

but since https is disabled, "Disable web GUI redirect rule" is not available.

**Comment by Monviech** [comment]
Oh I see its a bug in the validation. Okay thats going to be solved.

**Comment by Monviech** [comment]
I understand how this happens now.

If you go from HTTPS to HTTP, and never disabled the "GUI redirect rule", it is saved inside the configuration. It will still be validated even though the configuration checkbox is not visible.

I have reverted to HTTP, and since I had the GUI redirect rule disabled already and had saved that, I didnt get the validation bug.

So until this is fixed:
- Change to HTTPS
- Disable the redirect rule and safe
- Go back to HTTP

**Comment by clsferguson** [comment]
> I understand how this happens now.
> 
> If you go from HTTPS to HTTP, and never disabled the "GUI redirect rule", it is saved inside the configuration. It will still be validated even though the configuration checkbox is not visible.
> 
> I have reverted to HTTP, and since I had the GUI redirect rule disabled already and had saved that, I didnt get the validation bug.
> 
> So until this is fixed:
> 
> * Change to HTTPS
> * Disable the redirect rule and save
> * Go back to HTTP

Thank you, unfortunately I think I will need to wait for the fix. It will be a task to do that.

![image](https://github.com/user-attachments/assets/2199e5f0-dd0e-4bf2-9b99-e691d798edbe)

**Comment by Monviech** [comment]
The patch can be installed with:

’’’opnsense-patch -c plugins 72dfcfa’’’

It removes the whole WebGUI validation and will also be in the next version.
