### ISSUE TITLE
security/tailscale: support ipv6 advertised subnets

### ISSUE THREAD

**Issue by frezbo** [opnsense/plugins#4412]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [ ] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Support ipv6 advertised subnets for tailscale

**Comment by itz-Jana** [comment]
+1 on this, I was very excited to see the Tailscale Plugin appear, so a big thank you to the creator for adding that, but I can't use the Subnet Router because of this right now (My setup only uses IPv6).

I had a quick look at the plugin code and I didn't see any clear blockers as to adding IPv6 support. Tailscale also doesn't require any shenanigans with square brackets around IPv6 ips, like I had to implement when adding v6 support to Node Exporter, so it should just be a matter of also allowing v6 addresses in the form.

If the creator is not interested in looking into this, I could see if I can add support, but it would be a while until I'd have time for it.

**Comment by sheridans** [comment]
@itz-Jana you're quite right, just wanted the form field to allow IPv6 subnets
