### ISSUE TITLE
acme.sh/Let's Encrypt - Certificate Import and Revocation Needed

### ISSUE THREAD

**Issue by rootwyrm** [opnsense/plugins#519]
Been running into this one trying to effect a migration. When you click the trash bin, well, certificate goes away. However, this is decidedly NOT beneficial, even with short expiry certificates. It makes it impossible to issue a replacement certificate until the existing certificate (that you just deleted) expires.
The fix here should be fairly simple; just make the trash can also revoke the certificate before deleting. That way it can be recreated or created elsewhere as necessary.

The more difficult problem is implementing some form of Import mechanism for existing LE Certificates and accounts. Since I have been using LE extensively for a long time, I have a number of certificates I want to move into OPNsense for HAproxy use. There is currently no mechanism to import these certificates. If I simply drop them into `/var/db/acme/certs` or `/var/etc/acme-client/certs` they don't get picked up by the UI, which is undesirable. However, they DO get picked up by `acme.sh --home /var/etc/acme-client/home` when manually copied
```
root@neltharion:/var/etc/acme-client # acme.sh --list --home /var/etc/acme-client/home
Main_Domain        KeyLength  SAN_Domains  Created                       Renew
blog.rootwyrm.com  "4096"     no           Sat Nov  4 18:48:34 UTC 2017  Wed Jan  3 18:48:34 UTC 2018

```
Optimally, since this is an advanced function, requiring the user to deposit their existing certificates using scp or ssh should be the standard procedure. The feature here would be for the UI to properly pick these certificates and accounts up and take over management of them.

**Comment by fraenki** [comment]
> When you click the trash bin, well, certificate goes away. However, this is decidedly NOT beneficial, even with short expiry certificates. It makes it impossible to issue a replacement certificate until the existing certificate (that you just deleted) expires.

Please don't take this offensive: I'd argue that this is not a bug, it's a feature. To revoke a certificate, just use the revoke button. (Although I must admit that I _never_ revoke LE certs and can't say for sure that this is still working, but it was working at some point during development.)

Revoking a cert in OPNsense involves running acme.sh (in the background) and it is not guaranteed to succeed. Depending on what is configured in the GUI, the recovation may fail (or other border cases may prevent this task from completing).

That's why I think it would be problematic to depend on a successful revocation for the "remove" button. And that's the main reason why I've initially split "remove" and "revoke" into separate functionalities/buttons.

> The more difficult problem is implementing some form of Import mechanism for existing LE Certificates and accounts.

While the idea isn't wrong and would be beneficial for _some_ people, I'm not going to work on this. If someone else wants to work on this feature, I'd gladly review pull requests.
