### ISSUE TITLE
net/zerotier: Add support for self-hosted instances

### ISSUE THREAD

**Issue by 06chaynes** [opnsense/plugins#523]
Is it possible to add support for either DIY network controllers or at least self-hosted instances of ZerTier Central? If so, what kind of effort do you foresee this taking to add?

**Comment by flantel** [comment]
I would like to see this also. Existing support is really nice, but we run our own controllers.

**Comment by flantel** [comment]
If it is any help, when I was modifying my Ansible playbooks to support both my.zerotier.com API and my own controller, I only needed to change the following:

1. Add a header X-ZT1-Auth for the API key instead of Authorization
2. Use URL /api for zerotier and /controller for custom controller
3. Anything in the config array on zerotier is in the main array in custom controller.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Comment by alpharde** [comment]
Although I can't help with the issue itself, it would be good if I could at least set this manually. Controller will sometimes get wonky if opnsense is rebooted with the controller being inside the network, I guess it would be better to run it on the firewall itself.
