### ISSUE TITLE
security/acme-client: add support for Google Cloud DNS API

### ISSUE THREAD

**Issue by DanMc85** [opnsense/plugins#549]
Reference thread: https://forum.opnsense.org/index.php?topic=7170.0

Is it possible to add support for Google Domains API in ACME client GUI for DNS based validation?
https://support.google.com/domains/answer/3290350?hl=en&ref_topic=3251230

Would be great if it could be supported for the DNS TXT record automation tokens. Especially since it is required for the wildcard certs which are right around the corner.

**Comment by fraenki** [comment]
Unfortunately, Google Domains API isn't currently supported by [Neilpang/acme.sh](https://github.com/Neilpang/acme.sh) and a feature request was even abondoned: https://github.com/Neilpang/acme.sh/issues/180.

We'll have to wait until support is added to acme.sh. I'm closing this issue for the time being. Feel free to reopen this issue once this requirement is met.

**Comment by funar** [comment]
Support for Google Cloud DNS is pending.  Hopefully we'll have this soon. See: https://github.com/Neilpang/acme.sh/pull/1623

**Comment by KyleJ61782** [comment]
Google Cloud DNS is now supported by upstream. Perhaps now it could be added?

**Comment by fraenki** [comment]
Here's the bad news: In order to use acme.sh with Google Domains, the [gcloud](https://cloud.google.com/sdk/gcloud/) command-line tool is required. Unfortunately, it's not available on *BSD systems.
But I've downloaded the Linux version and it seems that gcloud is just a python2 tool, so I might be able to adjust it so that it's usable on FreeBSD. No promises though...

**Comment by fraenki** [comment]
This will be available in the upcoming release 1.24 of our acme plugin.

Note that several steps are required in order to get this working:
- requires acme.sh 2.8.2, which is **not released yet** (because [this](https://github.com/Neilpang/acme.sh/commit/145b1f4fb3cbeafa167d86f8f6004df194e5cd55#diff-870083a216c5cf4e55de49b3ce70d6fa) bugfix is required)
- you need to install the new os-google-cloud-sdk plugin in OPNsense (available in the next release)
- you must create a [service account key](https://cloud.google.com/iam/docs/creating-managing-service-account-keys) using the GCP Console
- you must enable the [Cloud Resource Manager API](https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview)
- finally paste the full JSON key in the OPNsense GUI (Services: Let's Encrypt: Validation Methods)

Not exactly user-friendly, but it looks like there's no other way to do it when using Google Cloud DNS.

**Comment by dpieski** [comment]
Hey, sorry for posting on a closed issue, but Google Cloud DNS and Google Domains DNS are two different things. OP titled for Google Cloud DNS but the question was directed to Google Domains DNS. 

For clarification:
Google Cloud DNS support was added.
There is no support for Google Domains DNS.

**Comment by fraenki** [comment]
@dpieski Unfortunately, Google Domains DNS is not supported by acme.sh, so that wasn't an option. If this ever changes, feel free to open a new issue and we'll add support for it in our LE plugin.

**Comment by nathan40** [comment]
Is this still unsupported? I have been looking for documentation, but am having a hard time finding documentation that shows how to setup Google Cloud DNS API with the ACME Client on OPNSense.

**Comment by fraenki** [comment]
AFAICT, it is still supported. Please head over to the [forum](https://forum.opnsense.org/) to ask for support.
