### ISSUE TITLE
Automatic backup via WebDAV(S) / FTP(S) [ / SMB / NFS]

### ISSUE THREAD

**Issue by Addy90** [opnsense/plugins#591]
Currently, automatic backup is only possible on proprietary Cloud of Google. For security reasons, it should at least be possible to sync via WebDAV(S) on self-installed Nextcloud / ownCloud Installations and maybe also on self-hosted FTP(S) servers (for example in the local network, or secured over internet).

In the best case, SMB / NFS is also supported, in case of local RAID systems, but what I really need is WebDAVS synchronization for Nextcloud. Better stay safe than sorry, right?

(Maybe I should have posted this at core not plugins, if so, my fault, sorry, but I am not sure if this is a core functionality or plugin maybe? Then it is right here...)

**Comment by fabianfrz** [comment]
@Addy90 config backup is a core feature. I will close this ticket because it belongs to core - please create a new one there.

I can create a script for Nextcloud (WebDAV) but I dislike the idea of SMB on OPNsense. FTP is not encrypted which is not a good idea for a config file containing lots of passwords and FTP is known to have issues with firewalls and NAT devices. I am not sure about NFS.

There is or was some code in development to upload the config file via SCP (SSH) and I do have a script for SFTP which will very likely not be included in a base install of OPNsense due to its dependencies.
