### ISSUE TITLE
Just some tips !

### ISSUE THREAD

**Issue by noobscode** [opnsense/plugins#638]
Hi Guys! I work as an IT-Architect and we administrate several thousands of networks and we see a trend where customers are using OPNsense. I've been trying out this firewall os for a few weeks now and I must say that I like it. Tho I was a bit dissapointed that some of the things I really was looking for was missing. I am patient and think some of theese ideas might help you out! keep up the good work!

For the nesxt release, here are some ideas:

- Better statistics for IDS / IPS from where you can see a list of IP/Host/Attacker with something like a Pie Chart showing the top 25/50/100 top attackers by IP and port. Trends are important to keep in mind.
This way the user really gets a visual feeling of how good your software are at blocking attackers and unwanted traffic. Would love this as an widget in the lobby. Sexy stuff

- When clicking the " i " on an IP in the firewall logs in live view for example. Add the IP reputations to check if an IP might be blacklisted

- A way to do Quick Actions on an IP like a "Quick release", "Check status" or "Quick Block"
Great if you need to do some troubleshooting or locked your cell phone out using the carriers network.

- Have a section for some advance rules regarding block actions. After so and so many attempts on blocked or non existing port block the IP and added to "Some List"

- Add general reporting. Using tasks the user can generate reports with custom criterias like.
Monthly traffic usage, Blocked statistics, maby even hardware info like average usage of ram diskspace processor etc. Theese reports are sent by email every day/week/month/year
Now OPNSense is not only a Firewall tool but also giving you good statistics and information more now than ever.

- On the spam protection end. I can not find any information telling if the spam engine actually block anything. Also it would be nice to have a way to release theese held emails. Not everything is spam.

Theese are just some ideas for you to have! Love the view, real nice and slick!

Best regards

**Comment by mimugmail** [comment]
Hi @noobscode and welcome to the show! :) 

Since this project is driven by volunteers it might lack some features known in commercial products like the resporting. Technically it shouldn't be a problem since you can also create nice (pie-)charts via fluentd and graylog, but as always it's all about priorities. 
IMHO point 2-4 are more easier doable when aliases- and firewall-code is API enabled (where are core devs currently on it). Reporting is a low prio task I think, you should open an issue in core repo regarding IDS, perhaps it's easy to implement.
Regarding spam protection it's ATM only block spam before catching up to not get in a lawful problems. You can view statistics when you configure HAProxy to redirect to localhost port 11332, it's the GUI from rspamd. If you know this product and have ideas how to make it better you are very welcome so we can improve this service. 

Hope to read some more ideas from you since it's also my wish to make it nearly feature complete with a Sophos SG! 👍

**Comment by fabianfrz** [comment]
@mimugmail it is TCP/11334, TCP/11332 is milter as far as i know.

**Comment by mimugmail** [comment]
yep, bad guessing :)

**Comment by fabianfrz** [comment]
I usually use because this is the simplest solution.
```bash
ssh root@IP_OF_OPNSENSE -L 11334:localhost:11334 
```
This command should forward the rspamd GUI port to localhost so you can access it like you would work directly on the firewall and the connection is well encrypted.

@mimugmail explained it right. Messages are not stored because they are blocked before entering the system. The reason is that this way, the operator is not liable for deleted or lost spam in Europe.

If we would accept it, the message must be made available to the user because the user is liable for (not) reading it. This is quite risky anyway because rspamd does also scan the message for malware or blacklist file extensions, so it does more than just scanning for spam.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
