### ISSUE TITLE
net/haproxy: dropdown sort order

### ISSUE THREAD

**Issue by StrikerTwo** [opnsense/plugins#687]
Just a small request:
The entries in the drop down fields (e.g. backend -> server, frontend -> certificate) don't seem to be ordered in any way when you just open the dropdown without searching for anything.
It would be nice if those entries were sorted by creation date descending.

My workflow for a new web site or service is
- create certificate in Let's Encrypt
- create real server
- create backend, select the server I just created
- create rule
- create frontend, select both the backend and the rule and the certificate I just created

If the newest entries were always displayed first, it would save me a couple of clicks.
If I search for something, obviously the search results should be ordered alphabetically.

**Comment by fraenki** [comment]
Most of these items will have alphanumeric sorting in the upcoming os-haproxy 2.15 release, thanks to @AdSchellevis who implemented this in https://github.com/opnsense/core/issues/3251.

Note that _some_ fields are not sorted _on-purpose_: Especially rules are not sorted, because the sort order determines _when_ a rule is executed (see #582 for further details).

**Comment by fichtner** [comment]
note this isn't coupled to the 2.15 but to the core version. 19.1.2 will skip this patch, but will likely hit 19.1.3.

**Comment by fraenki** [comment]
@fichtner Ahhhh sad, I was hoping to see this in 19.1.2 :-/
