### ISSUE TITLE
security/acme-client: restart actions box in "edit certificate" form displays only 10 actions

### ISSUE THREAD

**Issue by DonMcCoy** [opnsense/plugins#713]
Hi,
On edit certificate form, when clicking the restart actions box, to choose the restart actions, only 10 maximum restart actions are displayed:

![image](https://user-images.githubusercontent.com/18079656/41503747-f75aed10-71db-11e8-96c0-ffa0f9919af2.png)

after some investigation, it turned out to be that the tokenize plugin which is responsible for listing the actions, is set to display a maximum of 10 dropdown elements (data-nbdropdownelements="10"), as seen here:

![image](https://user-images.githubusercontent.com/18079656/41503758-35bedf26-71dc-11e8-9e51-0bcee5b84932.png)

sadly I couldn't locate where this attribute is being set (data-nbdropdownelements), any info how should go around this?

**Comment by fraenki** [comment]
AFAICT this is the expected behaviour for this input type. You'll find this in several places/plugins in OPNsense. If you have a suggestion for a change, maybe open a proposal in opnsense/core. :)

How to use such input fields:
Start typing the name of the "restart action" and it will appear. If the "restart action" cannot be properly selected, you're hitting bug #2381.
