### ISSUE TITLE
net/siproxd: add WAN interface as TextField

### ISSUE THREAD

**Issue by mimugmail** [opnsense/plugins#807]
or add tun interfaces to InterfaceField. These would be my solution for siproxd, when VoIP traffic should go over OpenVPN or OpenConnect. Type is InterfaceField, but this works only with assigned interfaces like WAN or LAN. Also @fabianfrz requested this several time regarding FRR/Quagga plugin, so you can use dynamic routing via VPN tunnels. 

As a quick solution I could/would/want make a new field (hidden in advanced section) and name it Override WAN, only a text field where you can put "ocvpn0" or "ovpnc0" with an additional if clause in templating.

If I remember correctly there were some issues with such a feature in core @fichtner said, esp. when there are more VPN interfaces but only a tun group is selectable .. now idea how @AdSchellevis thinks about this? It would make life easier for some plugins :)

**Comment by AdSchellevis** [comment]
@mimugmail if the device numbers are predictable, we could probably list them in the interface field type, the plugin should probably only register the devices in the configuration so you can filter them in the usual way (from the config xml).

**Comment by mimugmail** [comment]
@AdSchellevis thx! Do you have a config snippet of this usual way? :)

**Comment by AdSchellevis** [comment]
@mimugmail ping me on irc when I'm around, probably easier to explain.

**Comment by mimugmail** [comment]
Great, will do :)

**Comment by AdSchellevis** [comment]
ok, the idea is to align functionality to how GRE interface work now. 

Create a new interface, then using assignments to expose them to other components (which disables ip assignment).

**Comment by AdSchellevis** [comment]
Before I'm going to change anything in core, I would like to describe the proposed solution here briefly.

Since all interfaces support interface groups, it might be a good idea to add tunnel interfaces to a special group (`__tunnel__` for example, which can't be added from the webui), so we can teach `legacy_interfaces_details()` to parse the group list as well and use this information in both the interface assignment code (e.g. https://github.com/opnsense/core/blob/master/src/www/interfaces.php#L1738) and the hooks underneath that filter on `gre` and `gif` at the moment.

When adding "tunnel" interfaces, we can lock the ip assignment and set "interface locking" to prevent removal. 

Advantage is, that it's rather easy to push interfaces into the group when creating the interfaces (which is usually handled in the plugin code) and new types which should be configurable using ifconfig will remain the same.


@fichtner @mimugmail what do you think? If we're going to do this, we should add the issue to core and pick it up from there.

**Comment by mimugmail** [comment]
Good idea! But I'm a bit unsure regarding ZeroTier, I think there was a discussion to assign this interface and use static IPs:

https://docs.opnsense.org/manual/how-tos/zerotier.html?highlight=zerotier#interface-assignment

**Comment by AdSchellevis** [comment]
@mimugmail the plugin author can decide in this way, when the group is not set, it remains as it is.

**Comment by fichtner** [comment]
It’s probably a good idea. I can’t wrap my head around just yet though. There‘s beef I have with the interface assignments in general that can have a multitude of unintended side effects, most of it feels wrong to begin with so a simpler approach is better indeed. :)

**Comment by mimugmail** [comment]
Sidenote: 
Assgining a Interface, adding Lock and don't enabling it helps with MVC InterfaceField code to use it for templating, but for NAT (legacy code) I can't set the interface

**Comment by mimugmail** [comment]
@AdSchellevis I think this one resolves my problems:
https://github.com/opnsense/core/commit/b26ae32f1809b27d9d7a9234e7831c95fcc8511e

It was related to OpenConnect which wasn't excluded, my other problems were with Wireguard so also affected. Wasn't aware of this hack, sorry for wasting your time.

**Comment by fichtner** [comment]
dark magic :D
