### ISSUE TITLE
Monit: Sender address not imported from notifications

### ISSUE THREAD

**Issue by woftor** [opnsense/plugins#820]
When I click "import system notification" in the Settings of monit everything is imported from notifications, except for the sender address. I don't see a field for it too. The workaround described in the post below works (from:email@address in Alert Settins-Mail Format), but this has a consequence: You cannot customize "Subject" anymore in Mail Format.

According to below posts a fix should be in place: is it broken or did I miss something?
Just started to use OPNsense, so don't know if this has actually worked.

OPNsense 18.7.1_3-amd64

This issue seems the same as mine:
https://github.com/opnsense/plugins/issues/145
Reported as fixed by this commit:
https://github.com/opnsense/plugins/pull/148

**Comment by fbrendel** [comment]
The fix was only for the import during the plugin installation. Assuming a fresh clean Monit configuration it had added a new alert entry with the sender address.

But now it is merged into core.
@fichtner 
What if alerts are already configured?
Change all? Keep existing Mail Format? Or add/change only the From address?
And is it still worth it since we will replace the notification with Monit?

Anyway you cannot set the Mail Format as described in the [Monit Documentation](https://mmonit.com/monit/documentation/monit.html#Message-format).
The subject has to be on one line.
So the Mail Format field must be a textbox.

**Comment by AdSchellevis** [comment]
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.
