### ISSUE TITLE
security/acme-client: Possible to update https HAProxy frontend with new cert for SSL offloading?

### ISSUE THREAD

**Issue by mklvr** [opnsense/plugins#967]
The acme-client integration with opnsense is pretty great. One thing that would be extremely useful is if upon certificate validation, the certificate could be added to the "SSL Offloading" certificates list for an HAProxy frontend. Currently, this functionality is either not present or not working.

**Comment by fraenki** [comment]
> upon certificate validation, the certificate could be added to the "SSL Offloading" certificates list for an HAProxy frontend

Hm, this functionality is currently not available. However, it's possible to automatically reload HAProxy after an _existing_ certificate was renewed. Does _this_ sound useful?

I'm asking because I don't really get the use case. Maybe you can describe how this would save lots and lots of time in your use case. :)

**Comment by fraenki** [comment]
@mklvr Got it. Have you considered writing a small script and do this task through the OPNsense API? I'm aware of the following API clients (but haven't tested them):

https://github.com/mtreinish/pyopnsense
https://github.com/fabianfrz/OPNsense_client_lib

**Comment by fraenki** [comment]
I'm closing this, because nobody is working on it and the API would be the preferred way to automate these things. However, contributions are welcome. If anyone wants to work on this, please open a pull-request and reference this issue. :)
